Tests for DaoCross
sorrentum/sorrentum pull request #171
Opened 2023-04-25 19:15 UTC by samarth9008

2023-04-27 11:33 UTC, tamriq commented
Do the tests pass on your side when u run `sudo brownie test test/test_dao_cross_sol.py` ?  Because on my side i have gas estimation error for most of them.

```
E            ValueError: Gas estimation failed: 'VM Exception while processing transaction: revert'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.
```
<img width="1087" alt="Screenshot 2023-04-27 at 15 29 41" src="https://user-images.githubusercontent.com/43115975/234849173-bafd1e30-3762-40df-86ef-e8f2b63c9177.png">
<img width="1041" alt="Screenshot 2023-04-27 at 15 32 10" src="https://user-images.githubusercontent.com/43115975/234849701-34f0204f-f57e-44db-8538-8fc72d0e2922.png">

2023-04-27 13:09 UTC, samarth9008 commented
It did but let me figure out the error.

2023-04-27 13:48 UTC, samarth9008 commented
![image](https://user-images.githubusercontent.com/58821247/234880991-e3c1c01b-764e-4a00-a919-694c5376e152.png)

The reason I guess for this error is whenever I try to run your tests in docker from my system, it gets block in the `mempool` and does not execute so I have to mention `"gas_price": "60 gwei"` to run it successfully. However I think `"gas_price": "60 gwei"` is not needed while running tests in your environment. So maybe you can try by remoing them. FYI, the above screenshot is excluding your `match_orders` test.

2023-04-27 14:15 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
>  def test_match_orders(daocross, base_token):
Feel free to remove this test as it was used as an example for u.

2023-04-27 14:20 UTC, samarth9008 commented
> I reran the container and the tests and gas error disappeared. But this one left. <img alt="Screenshot 2023-04-27 at 18 11 43" width="1053" src="https://user-images.githubusercontent.com/43115975/234888732-7de4f9db-b314-43f3-a8cf-12e472b5fa28.png">
> 
> The review is in progress, will try to figure out why this test fails on my side

I already updated the code for the assert statement of this code. The new code will run successfully.

2023-04-27 14:23 UTC, samarth9008 commented on defi/dao_cross/test/test_dao_cross_sol.py
>  def test_match_orders(daocross, base_token):
Removed it.

2023-04-27 17:30 UTC, tamriq requested changes
Great job! Some changes requested

2023-04-27 17:30 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    Checks wheather the `newBuyOrder` event was emitted or not.
wheather -> whether

2023-04-27 17:30 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    Checks the functionality of `getChainlinkFeedPrice()` fucntion.
In fact here we check if our mock contract MockV3Aggregator that we set-up in price_oracle() function was mocked correctly. But why not :) Let's just explain that in the description.

2023-04-27 17:30 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    """
Use simple # comments inside the function.

2023-04-27 17:30 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    assert base_token.balanceOf(accounts[1]) == 5 * 10**18
Add more comments before assertions. E.g. here we can have `Check if buyer received the desired amount of tokens.`

2023-04-27 17:30 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +
Let's also test the different cases for matchOrders function. Check that the orders are filtered out, the return transfers, the transfers with leftovers etc.

2023-04-27 22:21 UTC, samarth9008 commented on defi/dao_cross/test/test_dao_cross_sol.py
> +         daocross.buyOrder(baseToken, quantity, limitPrice, depositAddress, {"from": accounts[1], "value": 100000000000*5, "gas_price": "60 gwei"})
I am facing error on this. Do I have to run it inside a cmamp container or anything that I am missing?

2023-04-27 22:50 UTC, samarth9008 commented on defi/dao_cross/test/test_dao_cross_sol.py
> +
I thought you already tested the matchOrders function but I will add more tests of it.

2023-04-28 12:22 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +         daocross.buyOrder(baseToken, quantity, limitPrice, depositAddress, {"from": accounts[1], "value": 100000000000*5, "gas_price": "60 gwei"})
You need to run it outside a container, just from the repo root

2023-04-28 14:21 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +
E.g. when the limit price does not fit the the clearing price and we fill the return transfer.

2023-04-28 14:32 UTC, samarth9008 commented on defi/dao_cross/test/test_dao_cross_sol.py
> +         daocross.buyOrder(baseToken, quantity, limitPrice, depositAddress, {"from": accounts[1], "value": 100000000000*5, "gas_price": "60 gwei"})
![image](https://user-images.githubusercontent.com/58821247/235175986-1bb85584-05b7-4a51-afae-a7c57eda0e75.png)

Is this the expected output of linter? Because the file is not being linted.

2023-04-28 14:43 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +         daocross.buyOrder(baseToken, quantity, limitPrice, depositAddress, {"from": accounts[1], "value": 100000000000*5, "gas_price": "60 gwei"})
Oh seems like something happened, this is not a usual behaviour. We can lint later in this case

2023-04-28 17:17 UTC, samarth9008 commented on defi/dao_cross/test/test_dao_cross_sol.py
> +
I have not explicitly code `matchOrders` functions while testing. Although it is called by `onSwapTime` function, I placed the orders and checked the balance in the end.

2023-05-01 20:00 UTC, tamriq requested changes
Good job! Also don't forget to change matchOrders -> processOrders function name

2023-05-01 20:00 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    Check if the ethers passed with function call is greater than or equal to full price.
"Check whether the amount of ETH transferred with the function call meet or exceed the total amount user wants to spend."

2023-05-01 20:00 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    Check if the balance of this DaoCross contract is increased after the sell order is placed.
"Check if the contract receives the correct amount of ETH from submitted sell orders."

2023-05-01 20:00 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    Check if the sell order with limit price Greater than latest price is not placed.
Check if the tokens are returned to the user is the desired sell price is greater than the actual token price.

2023-05-01 20:00 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    Check if the buy order with limit Price less than latest price is not placed.
Check if the ETH are returned to the user is the desired buy price is less than the actual token price.

2023-05-01 20:00 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    base_token.transfer(accounts[4], 2 * 10**18, {"from": accounts[0], "gas_price": "60 gwei"})
What about using a loop for sell orders? 
E.g.
```
n_tokens =  [2, 5, 3]
account_ind = [4, 5, 6]
for n, ind in zip(n_tokens, account_ind):
    # Transfer the token to the users that will participate sell order.
    base_token.transfer(accounts[ind], n * 10**18, {"from": accounts[0], "gas_price": "60 gwei"})
    # Approve the transfers for the contract.
    base_token.approve(daocross, n * 10**18, {"from": accounts[ind], "gas_price": "60 gwei"})
    # Submit sell order.
    daocross.sellOrder(base_token.address, n * 10**18, 100000000000, accounts[ind], {"from": accounts[ind], "gas_price": "60 gwei"})
 ```

2023-05-01 20:00 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +
let's also check that buyers got their extra money for 1.5 token back

2023-05-03 15:45 UTC, samarth9008 commented
> Good job! Also don't forget to change matchOrders -> processOrders function name

I guess there was no need to change anything in the test scripts because as I said, the `onSwapTime` function is calling `processOrders`, so in my test scripts I am calling the `onSwapTime` function and let the code do all the processing of the `processOrders` function and I check the balance in the end. Although I have covered all the possibilities of `filtersOrders` and `matchOrders` function, if anything is remaining please let me know.

2023-05-08 07:51 UTC, tamriq approved these changes
Two small details and we can merge!

2023-05-08 07:51 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    #Check that user that wanted to buy 5 tokens, gets only 3.5 tokens.
NIT: let's have a space after '#' in every comment. Also please check if all comments end with "."

2023-05-08 07:51 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> -    # Execute the swap
e.g. here we lost "."

2023-05-08 17:15 UTC, tamriq commented on defi/dao_cross/test/test_dao_cross_sol.py
> +
Last step: let's remove all empty lines from the code. If the code really needs to be separated, replace the empty line with the comment describing the next code block.

2023-05-08 21:03 UTC, tamriq approved these changes

2023-05-08 21:05 UTC, tamriq commented
Cool, we can merge. Once we fix linter of python files let's lint this

2023-05-08 21:05 UTC, merged

2023-05-14 16:06 UTC, gpsaggese reviewed
@DanilYachmenev can you help @samarth9008 get the code follow our standards?

@tamriq let's be stricter with the review on the cosmetic stuff

2023-05-14 16:06 UTC, gpsaggese commented on defi/dao_cross/test/test_dao_cross_sol.py
>  import pytest
Can we do a run of linter now that it works?

Feel free to ask @DanilYachmenev

2023-05-14 16:06 UTC, gpsaggese commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    initial_price = 100000000000 # This value should be scaled to the appropriate number of decimals
The comment should go before.

Also you can write it as 

initial_price = 100_000_000_000

or as 100e9 to make it simpler to parse

2023-05-14 16:06 UTC, gpsaggese commented on defi/dao_cross/test/test_dao_cross_sol.py
> +from brownie import DaoCross, accounts, Contract, MockV3Aggregator, MockERC20, reverts
We prefer to use 

import brownie

instead of the from ... import

2023-05-14 16:06 UTC, gpsaggese commented on defi/dao_cross/test/test_dao_cross_sol.py
> +def test_buyOrder_baseToken_address(daocross, base_token):
Why not type hints?

2023-05-14 16:06 UTC, gpsaggese commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    assert base_token.balanceOf(daocross.address) == quantity
self.assertEqual(

2023-05-26 14:35 UTC, DanilYachmenev reviewed
Sorry for delayed review, just found it out

But here it is, @samarth9008, a small code style lesson)
Pls go through all the comments, ask if smth is unclear and lets make this test file a bit more of "our" style

Just create another branch and PR, just refer this one there
ask question here

2023-05-26 14:35 UTC, DanilYachmenev commented on defi/dao_cross/test/test_dao_cross_sol.py
> +def test_buyOrder_baseToken_address(daocross, base_token):
Looked for some documentation on unit test but have not found it
Will do a detailed look

But see, here is our convention

1) For unit tests we use `pytest` but not directly
We already have a lib that has a lot of useful tools for unit testing `helpers.hunit_test`
Check it out briefly

But what I suggest is to look at reference code at some other test files, where test classes are inherited from that lib
`defi/tulip/test/test_order_matching.py`
`defi/tulip/test/test_optimize.py`

2) While looking at the test files, you can see that there is a certain approach to name test classes and their methods (which are the actual tests)
- Tests that are closely related usually belong to 1 test class
- A test class name is usually build in the following pattern:
```
class TestFunctionName1(hunitest.TestCase):
```
- test methods are usually just numbered or reflect the action that they test

So in this case I'd do
```
class TestBuyOrder1(hunitest.TestCase):
    """
    Check that DaoCross orders purchase is being implemented correctly.
    """
    
    def test_base_token_address1() -> None:
    ...
    def test_base_token_address2() -> None:
```
smth like this
but mind the names carefully

2023-05-26 14:35 UTC, DanilYachmenev commented on defi/dao_cross/test/test_dao_cross_sol.py
> +         daocross.buyOrder(baseToken, quantity, limitPrice, depositAddress, {"from": accounts[1], "value": limitPrice*5, "gas_price": "60 gwei"})
what do we assert here?
or is it just a 'smoke' test (the one that just checks if the call passes)

if possible, assert the output using `hdbg` lib

2023-05-26 14:35 UTC, DanilYachmenev commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    Check whether the amount of ETH transferred with the function call meet or exceed the total amount user wants to spend.
All the lines should be < 80 symbols
just for the beauty (this is enough reason, right?)

2023-05-26 14:35 UTC, DanilYachmenev commented on defi/dao_cross/test/test_dao_cross_sol.py
> +def test_buyOrder_passedEther(daocross, base_token):
try to not being to specific in the function name is it is not really necessary
here I mean specifying that you pass ether exactly
the test seems the same with the precious one, so it can have the same name, but with just another digit at the end

2023-05-26 14:35 UTC, DanilYachmenev commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    assert daocross.orders(1)[0] == 1
is it asserting the length as the docstring specifies?

in any case, use `helpers.hdbg` lib instead of direct asserts everywhere, always
here
```
hdbg.dassert_eq(0, daocross.orders(0)[0])
hdbg.dassert_eq(1, daocross.orders(1)[0])
```

2023-05-26 14:35 UTC, DanilYachmenev commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    Buy 2.5 tokens for 100000000000 WEI.
good to add a short specific explanation of what happens in the test
but here I cant really get it yet (ok to explain here in the comment just for me)

but if you do this - do same in every other test
or do not do it if this is not very necessary and clear from the code

2023-05-26 14:35 UTC, DanilYachmenev commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    daocross.buyOrder(base_token.address, 5 * 10**18, limitPrice, accounts[1], {"from": accounts[1], "value": limitPrice*5, "gas_price": "60 gwei"})
Usually we try to avoid placing param values right to the call
For ex I'm not familiar with the code at all and the only thing I get is `limitPrice` because you basically named it
So pls do the same for all the other values in the call like for `5 * 10**18`, `accounts[1]`, etc
in other words, avoid nested computations

2023-05-26 14:35 UTC, DanilYachmenev commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    limitPrice = 100000000000
do not use camel case in param and function names

so do -> `limit_price`

2023-05-26 14:35 UTC, DanilYachmenev commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    ethAddress = "0x0000000000000000000000000000000000000000"
thiiiiis is what Im talking about

2023-05-26 14:35 UTC, DanilYachmenev commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    tx = daocross.buyOrder(base_token.address, quantity, limitPrice, depositAddress, {"from": accounts[1], "value": 100000000000*5, "gas_price": "60 gwei"})
1) what is `tx`? give more informative name

2) specify the dict that goes as the last param separately as well (and name it better)
```
some_dict = {
    "from": depositAddress,
    "value": limitPrice*5,
    "gas_price": "60 gwei"
}
tx = ...
```

2023-05-26 14:35 UTC, DanilYachmenev commented on defi/dao_cross/test/test_dao_cross_sol.py
> +    assert base_token.balanceOf(accounts[6]) == 0
refactor with all the comments I've already left

but here in terms of comments
lets not be too specific in such cases
remember, you almost never need to use hard-coded values and actual code name in the comments and socstrings

so
```
...
# Get the amount of tokens that the buyers have got and the sellers have sold.
buy_token_amount1 = ...
buy_token_amount2 = ...
...
sell_token_amount1 = ...
...
# Check that the amount of bought and sold tokens is correct.
hdbg.dassert_eq(3.5*10**18, buy_token_amount1)
...
```