Add initial version of github_permission.py
sorrentum/sorrentum pull request #248
Opened 2023-05-12 22:04 UTC by patel954

2023-05-13 16:17 UTC, gpsaggese commented
Good starting point @patel954 

@DanilYachmenev can you also pls take a look?
From a high level view
- let's point @patel954 to one of our scripts and to the template we use ./dev_scripts/script_skeleton.py
- pass params from command line
- more functions to describe the flow
- run the linter

2023-05-13 16:47 UTC, samarth9008 requested changes

2023-05-13 16:47 UTC, samarth9008 commented on dev_scripts/github_permission.py
> +github_account_id_column = "GITHUB_ACCOUNT_ID_COLUMN_NAME_HERE"
From what I see in your code, you are downloading the gsheet and then reading that file. Instead can you try implementing in a way that we pass the usernames as a command line arguments such python script.py user1 user2.....

2023-05-13 21:14 UTC, patel954 commented
I have updated the script as per your details and now you can run the code using python script.py username1 username2 ... and let me know if there is any other changes required.

2023-05-13 23:27 UTC, gpsaggese commented
The code is not bad, but doesn't follow how we do things. @samarth9008 has not worked long enough with us to know how we do things. In general, when somebody new is on-boarded we need more precise specs about the interface and what scripts to look at about how we do things, from one of the core teams. Then @samarth9008 can take over and next time he knows how to write specs.

@DanilYachmenev can you pls write down specs pointing at examples of how the code should be architected? @PomazkinG can also help.

2023-05-16 20:53 UTC, samarth9008 approved these changes

2023-05-17 13:23 UTC, DanilYachmenev reviewed
Soooo, here is the first round from me
After you do, pls, try to check it with actually running it for yourself probably

Overall comments
- Read the coding style [doc](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md))
- Run linter (read [this](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md))
- Publish a script logs outcomes here so we could see that it works
- Good job making a working code! Lets just learn some boring but important formatting - you'll get it soon, you'll feel how it helps

FYI @samarth9008

2023-05-17 13:23 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +github_usernames = args.usernames
All these should go under `_parse()` function, see [dev_scripts/notebooks/publish_notebook.py](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/notebooks/publish_notebook.py) and [dev_scripts/replace_text.py ](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/replace_text.py)for ref code.

Please, describe the passed args as it is done there and see how they are processed in the mentioned ref code  
```
...
parser.add_argument(
        "--usernames",
        action="store",
        required=True,
        default=None,
        help="Space-separated GitHub  usernames to check and invite",
    )
 ...
```

2023-05-17 13:23 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +# Process each GitHub username
Good job with commenting the code

2023-05-17 13:23 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +
Avoid empty spaces in the code
Read about it and other nits at out [Coding Style Guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md#replace-empty-lines-in-code-with-comments)

2023-05-17 13:23 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +for github_username in github_usernames:
Everything below this line should go in `_main` function
See the mentioned reference files for ref

2023-05-17 13:23 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    if status_code == 404:
Make `if-else` clauses complete
Read [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md#make-if-then-else-complete)

2023-05-17 13:23 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +        collaborator_permissions_url = collaborator_check_url + "/permission"
Use `.join` instead of `+~ for strings
This is a better approach and good tone ([link](https://stackoverflow.com/questions/39675898/is-python-string-concatenation-bad-practice))

2023-05-17 13:23 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +            print(f"{github_username} is already a collaborator with {current_permission_level} permission level.")
Use `_LOG` instead of `print` here and below
read [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md#logging)

2023-05-22 14:31 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +import argparse
Please, press `Resolve conversation` button under each comment that you have fixed.
This will help me to understand, which ones are already implemented and which are not yet

And it will also make the process much easier for you, because as I see for now, you could omit some of the comments unintentionally

2023-05-22 14:42 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    ```
Extend the example with an actual script run example that works

ofc after you finish the code

2023-05-22 14:50 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +)
these should go inside functions bodies, since they are just used once

2023-05-22 14:50 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    print(message)
You do not need this one
See how `_LOG` is used in the reference code https://github.com/sorrentum/sorrentum/pull/248#discussion_r1196488780

especially look at the lines that do
```
...
_LOG = logging.getLogger(__name__)
...
_LOG.debug("line='%s'", line)
```
etc

2023-05-22 14:50 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +def check_collaborator(github_username):
Add [type hints](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md#use-type-hints) to function params and output

2023-05-22 14:50 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    """Check if a GitHub user is already a collaborator."""
Format docstrings correctly
for this look at the [docs](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md#format-docstrings-and-comments-as-markdown) and reference code (how it is done in other functions)

2023-05-22 14:50 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +
so here no need for empty space

2023-05-22 14:50 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    if status_code == 404:
Not implemeted, take a closer look pls

2023-05-22 14:54 UTC, DanilYachmenev reviewed
Pls read my previous comments, https://github.com/sorrentum/sorrentum/pull/248#pullrequestreview-1430586686, and comments again carefully

If you have any doubts - write questions right in here in the comments, I'll clarify everything you need (but pls read the docs and reference code before)
but yes, pls process all of them before re-requesting the review

2023-05-22 14:54 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    )
this should ho to `_parse` function
see https://github.com/sorrentum/sorrentum/pull/248#discussion_r1196488780

2023-05-22 14:54 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    """Main function."""
format docstring

2023-05-22 14:54 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +def main():
add type hints

2023-05-30 19:37 UTC, DanilYachmenev reviewed
Well, it seems like a quite big issue
but it is definitely a good training for making a working code and learning our code style

so pls, read the docs, reference code, do the comments
ask if smth is unclear

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +#!/usr/bin/env python
this should go as the 1st line, above all the docstrings

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    ```
```
> python dev_scripts/github_permission.py GITHUB_USERNAME
```

and btw did you check it? does the script work?
pls report logs as text

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    Check if a GitHub user is already a collaborator.
lets add params desc
see in other files

but usually it goes

```
"""
Docstring.

:param owner_username: owner username
:param repo_name: ...
"""
```

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    collaborator_check_endpoint: str = (
no need to add type hints inside the function

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +        "{collaborator}"
Use f-strings to insert params inside a string
see [here](https://peps.python.org/pep-0498/#:~:text=F%2Dstrings%20provide%20a%20way,which%20contains%20expressions%20inside%20braces.)

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    headers = {"Authorization": f"Bearer {access_token}"}
well, not sure if it gonna work
f-strings again

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    # If collaborator is already a collaborator, get their permission level.
place such comments under `if` statements
tradition yet unreflected in the docs

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +            )
And for logs we use `%s`
See `_LOG.debug` uses in any other file`

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +        )
build links using `.join` whenever possible
like here

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +            )
Factor out this in a separate helper function
Correct me if I'm wrong, but it seems a quite independent code block

Name it according to what it does, like `_check_permission_level` in this case

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +            else:
I believe this `else` is intended incorrectly, check it pls (since it is under `for` statement, not an `if`)

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +            )
btw i believe it would better go as `_LOG.info` since these are the functional reports, not just debug tools

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    access_token = "your_access_token"
Well, you definitely need a `_parse()` function and pass params with it
check out the ref code closely https://github.com/sorrentum/sorrentum/pull/248#discussion_r1200619144

let me know if it is unclear

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    main()
I beleive when you add `_parse` it will be as simple as
```
if __name__ == "__main__":
    _main(_parse())
```

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    """
well, `main()` is one of the few functions that does not need an intro)
lets remove it

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +                data = {"permission": "desired_permission_level_here"}
who is this `desired_permission_level_here`?

2023-05-30 19:37 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +            else:
Code below this block can be factored out to a helper function like 
```
def _send_invitation(owner_username, repo_name, github_username, headers):
```
lets do it to improve readability

2023-05-31 12:09 UTC, gpsaggese commented on defi/tulip/services/indexer/devops/Dockerfile
> +FROM python:3.7-slim
Yes, it looks like master is not merged with master.

@DanilYachmenev let's add this to the list of things to do before the review, suggesting to use `i git_merge_master`. The reviewer can also do it on the fly with a button on GitHub (just did)

2023-06-19 12:10 UTC, DanilYachmenev commented
@patel954 are you going to finish the code?

2023-06-19 12:18 UTC, patel954 commented
I was waiting for your reply to the comments I have added from your last review.

2023-06-19 12:27 UTC, DanilYachmenev commented
> I was waiting for your reply to the comments I have added from your last review.

well,

1) if you want your PR to be reviewed, read this one again carefully and treat your PR n GitHub as suggested
[La Planète sauvage](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md#save-reviewer-time)

2) If noone reviews your works for more than 3 days, well, ping us. It is your responsibility to keep an eye on your PR and promote work on it.
No need to be annoying, a couple days of awaiting is OK, since reviewers have quite a workload
but we also cannot track progress on every PR, especially when it is not treated according to our processes
the last action here was like 3 weeks ago - this is a lot

3) and where are the changes btw?
my last review is this one https://github.com/sorrentum/sorrentum/pull/248#pullrequestreview-1451624762
no other action, no any commits are reflected in the PR after that
Provide a link pls if I'm missing smth out

2023-06-19 14:01 UTC, patel954 commented
I am sorry @DanilYachmenev the comments were not pushed and that's why it did not showed up on your side.

2023-06-19 14:14 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    access_token = "your_access_token"
see how the `_parse()` function works in similar scripts
e.g. see see [dev_scripts/notebooks/publish_notebook.py](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/notebooks/publish_notebook.py)

```
def _parse() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "--file",
        action="store",
        required=True,
        type=str,
        help="The path to the ipynb file, a Jupyter URL, or a GitHub URL",
    )
    ...
```
so `file` param is being introduced in the mentioned way
check out other scripts like https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/replace_text.py for even more clarity on how to introduce params to the script (you do not need to read the full code, docstrings, use cases and `_parse` func are enough)

2023-06-19 14:15 UTC, DanilYachmenev commented on dev_scripts/github_permission.py
> +    access_token = "your_access_token"
If it does not work perfectly - double-check the format
if does not work again - commit with error logs

2023-06-23 13:10 UTC, patel954 commented
I have a tight schedule on weekdays. So, I will be completing this code by Sunday, the 25th of June.

2023-06-26 12:23 UTC, samarth9008 commented
Closing as #349 is being used now.

2023-06-26 12:23 UTC, closed without merging