SorrIssue244 ccxt version unit test
sorrentum/sorrentum pull request #317
Opened 2023-06-08 19:41 UTC by yiyunlei

This is for issue #244.
I finished the unit test for `currency_pairs = ["BTC/USDT"]`. 
Should I add a similar unit test for `currency_pairs = ["ETH/USDT"]`?

2023-06-08 21:36 UTC, DanilYachmenev reviewed
Very good!!
The test is working and passing
And I see that you really read docs and code, gj!

See the suggestions, mostly comments and placement

2023-06-08 21:36 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_version.py
> +class TestCcxtVersion1(hunitest.TestCase):
Overall the test class name should reflect what class or function it tests
In this case it is `CcxtExtractor` so I'd actually suggest you to not create a new test file and class here but move the test method to `TestCcxtExtractor1` in `im_v2/ccxt/data/extract/test/test_ccxt_extractor.py`, right after `test_download_ohlcv_websocket_kline_is_not_present()` method

2023-06-08 21:36 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_version.py
> +    def test_download_ohlcv_with_current_ccxt_version1(
lets not attach to ccxt version here to much since the goal is to check timestamp representations

so lets keep the used func name and also express what we check here -> `test_download_ohlcv_timestamp_representation1()`

2023-06-08 21:36 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_version.py
> +        change.
```
Verify that OHLCV data timestamps are correctly represented.
```

2023-06-08 21:36 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_version.py
> +        # Expected output: This is downloaded data with the CCXT version 2.1.80.
no need for this line one IMO, lets not be to specific

2023-06-08 21:36 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_version.py
> +        # Using Binanceus API because Binance API is not accessible.
But this one is a good comment, gj!
lets just rename `Binanceus` -> `Binance.US` for clarity

2023-06-08 21:36 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_version.py
> +        exchange_class.currency_pairs = ["BTC/USDT"]
Can we simply add another currency pair here like `"ETH/USDT"` (and update the goldens ofc)?

2023-06-09 12:28 UTC, jsmerix approved these changes
Nicely done, make sure to run linter if you haven't already and we can merge.

2023-06-09 17:17 UTC, yiyunlei commented
> Very good!! The test is working and passing And I see that you really read docs and code, gj!
> 
> See the suggestions, mostly comments and placement

Thank you!!
I'm really happy that I got praise for my work！

Based on your feedback, I updated the code and encountered a bug.
I left a comment in the issue #244

2023-06-09 17:18 UTC, yiyunlei commented
> Nicely done, make sure to run linter if you haven't already and we can merge.

Yes, I have run the linter.

2023-06-09 18:48 UTC, jsmerix requested changes
Noticed one small detail and let's also make sure the test is only present in one file, by the way it does not seems that the problem you described in https://github.com/sorrentum/sorrentum/issues/244#issuecomment-1584901453 is reproduced in github actions since the tests are passing

2023-06-09 18:48 UTC, jsmerix commented on im_v2/ccxt/data/extract/test/test_ccxt_version.py
> +)
Your test does not need CK S3 so let's remove this decorator

2023-06-09 19:45 UTC, yiyunlei commented
> Noticed one small detail and let's also make sure the test is only present in one file, by the way it does not seems that the problem you described in [#244 (comment)](https://github.com/sorrentum/sorrentum/issues/244#issuecomment-1584901453) is reproduced in github actions since the tests are passing

I copy-pasted the test to the file `test_ccxt_extractor.py` (it's original in the file `test_ccxt_version.py`) based on the feedback from @DanilYachmenev, I also think it's better to put it in the `test_ccxt_extractor.py`

<img width="817" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/c3bcc4e8-4465-4960-9474-86efbfebeae9">

So I keep the test in both files now for finding the bug and will delete `test_ccxt_version.py` once I fix the bug.

I run the command `pytest im_v2/ccxt/data/extract/test/test_ccxt_extractor.py::TestCcxtExtractor1::test_download_ohlcv_timestamp_representation1` in the docker and it failed. Could you try this?

Also, how can I run tests in GitHub actions? I didn't find it in docs.

2023-06-09 19:59 UTC, yiyunlei commented on im_v2/ccxt/data/extract/test/test_ccxt_version.py
> +)
I added this because I want to move the ccxt unit test to `test_ccxt_extractor.py` without any bugs. Since `test_ccxt_extractor.py` already has this decorator, I added it there and tried to locate the bug. In the end, I will only keep the test in `test_ccxt_extractor.py`.

2023-06-10 06:03 UTC, DanilYachmenev commented
> So I keep the test in both files now for finding the bug and will delete `test_ccxt_version.py` once I fix the bug.

Oh, actually no need to keep both even for now
Its OK to implement all the changes in the old lace and then move all the working code to another directly if you work inside 1 PR
All your previous commit versions are saved in specific commits, like [f16cf73](https://github.com/sorrentum/sorrentum/pull/317/commits/f16cf7387b8a1aa82a89958749e081088596c422)
<img width="866" alt="Снимок экрана 2023-06-10 в 12 58 06" src="https://github.com/sorrentum/sorrentum/assets/31514660/6f859f1e-64b7-4d63-9e68-3d4ce53d8999">

Since your code is already pretty neat, lets remove `test_ccxt_version.py`
In case we need to revert it, you can always access with in the previous commit versions

> I run the command `pytest im_v2/ccxt/data/extract/test/test_ccxt_extractor.py::TestCcxtExtractor1::test_download_ohlcv_timestamp_representation1` in the docker and it failed. Could you try this?

Could you post error logs here pls? So we could we what is the problem?

> Also, how can I run tests in GitHub actions? I didn't find it in docs.

In order to run GitHub actions tests you just need to convert a draft to a PR that is ready for review (right button)
They are not running for drafts but for PRs they will run automatically 
<img width="908" alt="Снимок экрана 2023-06-10 в 13 01 25" src="https://github.com/sorrentum/sorrentum/assets/31514660/b52099a3-2e04-4267-afb2-13a3463f4730">

2023-06-10 06:18 UTC, DanilYachmenev reviewed
almost there
lets do these nits, fix the error and then pass to GP

2023-06-10 06:18 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +        exchange_class.currency_pairs = ["BTC/USDT"]
formatting nit
if some value is being repeatedly used in the code, set is as a param, so in case it changes, you do not forget to update all the calls

so here
```
exchange_id = "binanceus"
currency_pair = "BTC/USDT"
exchange_class = imvcdexex.CcxtExtractor(exchange_id "spot")
exchange_class.currency_pairs = [currency_pair]
...
ccxt_data = exchange_class._download_ohlcv(
            exchange_id=exchange_id,
            currency_pair=currency_pair,
...
```

2023-06-10 06:18 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_version.py
> +        exchange_class.currency_pairs = ["BTC/USDT"]
Actually, does not seem that this suggestion is reasonable, since `_download_ohlcv` works only with 1 curr pair and `expected_output` signature just has no a column for currency pair - so mixing the signatures would be a mess

therefore, the test for 1 curr pair is enough IMO

2023-06-10 19:36 UTC, yiyunlei commented
Error logs:

The test `test_download_ohlcv_timestamp_representation1` can run successfully in the new file `test_ccxt_version.py`, but after I moved it to the `text_ccxt_extractor.py`, I got an unexpected bug.

- Test result when running the test in `test_ccxt_version.py`:
`pytest im_v2/ccxt/data/extract/test/test_ccxt_version.py::TestCcxtVersion1::test_download_ohlcv_timestamp_representation1`
```shell
im_v2/ccxt/data/extract/test/test_ccxt_version.py::TestCcxtVersion1::test_download_ohlcv_timestamp_representation1 (1.22 s) PASSED                                                           [100%]

=================================================================================== slowest 3 durations ===================================================================================
1.26s call     im_v2/ccxt/data/extract/test/test_ccxt_version.py::TestCcxtVersion1::test_download_ohlcv_timestamp_representation1
0.01s setup    im_v2/ccxt/data/extract/test/test_ccxt_version.py::TestCcxtVersion1::test_download_ohlcv_timestamp_representation1
0.00s teardown im_v2/ccxt/data/extract/test/test_ccxt_version.py::TestCcxtVersion1::test_download_ohlcv_timestamp_representation1
```

- Test result when running the test in `test_ccxt_extractor.py`:
`
pytest im_v2/ccxt/data/extract/test/test_ccxt_extractor.py::TestCcxtExtractor1::test_download_ohlcv_timestamp_representation1
`
```shell
======================================================================================== FAILURES =========================================================================================
____________________________________________________________ TestCcxtExtractor1.test_download_ohlcv_timestamp_representation1 _____________________________________________________________
Traceback (most recent call last):
  File "/app/im_v2/ccxt/data/extract/test/test_ccxt_extractor.py", line 262, in test_download_ohlcv_timestamp_representation1
    ccxt_data = exchange_class._download_ohlcv(
  File "/app/im_v2/ccxt/data/extract/extractor.py", line 187, in _download_ohlcv
    range(
TypeError: only integer scalar arrays can be converted to a scalar index
=================================================================================== slowest 3 durations ===================================================================================
0.15s call     im_v2/ccxt/data/extract/test/test_ccxt_extractor.py::TestCcxtExtractor1::test_download_ohlcv_timestamp_representation1
0.01s setup    im_v2/ccxt/data/extract/test/test_ccxt_extractor.py::TestCcxtExtractor1::test_download_ohlcv_timestamp_representation1
0.00s teardown im_v2/ccxt/data/extract/test/test_ccxt_extractor.py::TestCcxtExtractor1::test_download_ohlcv_timestamp_representation1
================================================================================= short test summary info =================================================================================
FAILED im_v2/ccxt/data/extract/test/test_ccxt_extractor.py::TestCcxtExtractor1::test_download_ohlcv_timestamp_representation1 - TypeError: only integer scalar arrays can be converted t...
```

The related code in `extrator.py`:
```python
        # Convert datetime into ms.
        start_timestamp = start_timestamp.asm8.astype(int) // 1000000
        end_timestamp = end_timestamp.asm8.astype(int) // 1000000
        duration = self._sync_exchange.parse_timeframe("1m") * 1000
        all_bars = []
        # Iterate over the time period.
        # Note: the iteration goes from start date to end date in milliseconds,
        # with the step defined by `bar_per_iteration` parameter.
        # Because of this, the output can go slightly over the end date.
        for t in tqdm.tqdm(
            range(
                start_timestamp,
                end_timestamp + duration,
                duration * bar_per_iteration,
            )
        ):
```
@DanilYachmenev

2023-06-10 19:59 UTC, yiyunlei commented
I still get this error for now when I run this unit test in the docker, and I can't test in the GitHub actions since GitHub actions tests are not available on Sorrentum yet.

2023-06-11 11:45 UTC, DanilYachmenev commented
> Error logs:

This is indeed a complicated error that is related to the mocking approach
I myself actually is not an expert in this

@jsmerix, could you ptal?

I've run the test with some logs added for the params that go to the `range` in `_download_ohlcv()` and the problem is definitely in computing `duration` at line 180:
`duration = self._sync_exchange.parse_timeframe("1m") * 1000`
param logs:
```
(0.02 s) duration <MagicMock name='ccxt.binanceus().parse_timeframe().__mul__()' id='140105328842400'>
start_timestamp 1666224060000
end_timestamp 1666224300000
end_timestamp + duration []
duration * bar_per_iteration <MagicMock name='ccxt.binanceus().parse_timeframe().__mul__().__mul__()' id='140105330215760'>
```


So as you can see, `duration` is not parsed and seems like it requires timeframe parsing, like it is done for `test_download_ohlcv1`:
```
        # Mock a call to ccxt's `parse_timeframe method` called inside `_fetch_ohlcv`.
        with umock.patch.object(
            exchange_class._sync_exchange, "parse_timeframe", create=True
        ) as parse_timeframe_mock:
            parse_timeframe_mock.return_value = 60
            # Run.
            ohlcv_data = exchange_class._download_ohlcv(
            ...
``` 

When I simply done the same in the test, all the values turned into int variables
However, an empty df is returned, so I'm questioning what else should be done to download the data correctly in this case
param logs:
```
(0.03 s) duration 60000
start_timestamp 1645660800000
end_timestamp 1645747200000
end_timestamp + duration 1645747260000
duration * bar_per_iteration 30000000
```
output df is empty, test fails:
```
exp = r"""
Empty DataFrame
Columns: [timestamp, open, high, low, close, volume, end_download_timestamp]
Index: []
"""
```

My guess on why the same code now fails is that in `TestCcxtExtractor1` there is mock call to CCXT, but not sure
```
class TestCcxtExtractor1(hunitest.TestCase):
    # Mock calls to external providers.
    ccxt_patch = umock.patch.object(imvcdexex, "ccxt", spec=ccxt)
```

So this is where I could get so far
What else could we do to proceed with debugging and do a fix?

2023-06-12 15:13 UTC, jsmerix commented
@yiyunlei I'd put the test into a new test class (new class, same file) and see if it passes, no reason to lose sleep over this.

2023-06-12 22:14 UTC, yiyunlei commented
I now understand the 'superslow' in the issue #244 description, as this unit test needs to download data through an API.

So, how can I make this unit test a superslow test? I couldn't find any doc about it. 
I think this will be the final step for this task.

2023-06-14 13:30 UTC, yiyunlei commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +    def test_download_ohlcv_timestamp_representation1(
`pytest` is imported

2023-06-14 13:48 UTC, yiyunlei commented on .gitignore
> +.DS_Store
How about moving the comment to a new line? 
Because comments must start at the beginning of a line and a line with a comment at the end does not work. 
Resource: https://stackoverflow.com/a/8865858/18517831
<img width="862" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/ba93f4c3-989d-4d89-bb16-77ac7ec41977">

Or should I open a new issue for it?

2023-06-14 14:25 UTC, DanilYachmenev commented
> @jsmerix Could you unblock this merge?

merge button is only for GP here)

but the button is being unlocked only when you resolve all the conversations

2023-06-14 14:25 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +        # Download real OHLCV data using ccxt.
No, just in the comments we use it capitalized 
in names everything os ok

2023-06-14 14:27 UTC, DanilYachmenev commented on .gitignore
> +.DS_Store
well, yes, lets move it above the code line then

2023-06-14 14:29 UTC, yiyunlei commented
> > @jsmerix Could you unblock this merge?
> 
> merge button is only for GP here)
> 
> but the button is being unlocked only when you resolve all the conversations

Thanks, but there is a requested change from @jsmerix, and I have addressed it.

<img width="856" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/91919a1e-aacc-4d1a-b38d-6352e426cf97">
<img width="601" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/bc08535d-80aa-42ab-88b2-516ca5a841e4">

2023-06-14 14:29 UTC, yiyunlei commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +        # Download real OHLCV data using ccxt.
Oh thanks, I misunderstood.

2023-06-14 14:47 UTC, yiyunlei commented
Resolved all the conversations and updated code.

2023-06-14 14:55 UTC, jsmerix requested changes
Let\s add the same test for `ETH/USDT`. Make sure we do not have a naive copy paste solution rather utilize some helper function

2023-06-14 14:55 UTC, jsmerix commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +        currency_type = "spot"
nit detail: rename the variable `currency_type -> asset_type` (internal convention)

2023-06-14 14:58 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +        """
1 more nit
do
```
# pylint: disable=line-too-long
expected_output = r"""
...
"""
# pylint: enable=line-too-long
```
to please the linter

2023-06-15 09:06 UTC, jsmerix commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +        currency_type = "spot"
That works as well

2023-06-15 20:24 UTC, yiyunlei commented
> 

Finished and tests passed.

2023-06-15 20:24 UTC, yiyunlei commented
> Let\s add the same test for `ETH/USDT`. Make sure we do not have a naive copy paste solution rather utilize some helper function

Finished and tests passed.

2023-06-15 20:29 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +    def test_download_ohlcv_timestamp_representation1(
avoid nested functions, especially when they are so big - difficult to review and edit

instead do an independent `_helper()` method and use in corresponding tests
see `Test_compute_duration_df` in `helpers/test/test_hpandas.py` for ex

2023-06-15 20:56 UTC, yiyunlei commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +    def test_download_ohlcv_timestamp_representation1(
Finished

2023-06-15 20:57 UTC, yiyunlei commented
Used independent _helper() and use two tests for two currency pairs. Also, tests passed.

2023-06-15 21:03 UTC, DanilYachmenev reviewed
good job! LGTM

a tiny nit to adhere standarts though, pls do

2023-06-15 21:03 UTC, DanilYachmenev commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +        # Prepare expected output
a tiny nit: end comment with dots`.`
check others too

2023-06-15 21:10 UTC, yiyunlei commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +        # Prepare expected output
No problem, I will pay more attention to these details.

2023-06-16 09:36 UTC, jsmerix requested changes
A few details left, bare with us, the first PRs always have this back-and-forth vibe.

2023-06-16 09:36 UTC, jsmerix commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +    def test_download_ohlcv_timestamp_representation_helper(
nit: private non-test method should start with underscore `_test_download_ohlcv_timestamp_representation_helper`

2023-06-16 09:36 UTC, jsmerix commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +        Verify that OHLCV data timestamps are correctly represented.
Based on the observations of our code base we should improve test case docstrings so it is easier to understand what the test is doing, basically reiterating what the original specs required

In this case:
```
"""
Verify that OHLCV data timestamps are correctly represented.

1. Perform a historical download of OHLCV data for a given time period and currency pair
2. Compare it to previously downloaded data using a specific CCXT version. This test ensures we can detect a change in interface (i.e. timestamp representation in this case) upon upgrading the library version.
"""
```

2023-06-16 09:36 UTC, jsmerix commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +        expected_output = expected_output.strip()
Was this line necessary? (It might have been, I am just asking)

2023-06-16 17:37 UTC, yiyunlei commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +    def test_download_ohlcv_timestamp_representation_helper(
Don't start with an underscore here because I followed the example `helpers/test/test_hpandas.py`. This example doesn't begin with an underscore for a similar helper.
<img width="430" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/955f4fd1-b8f0-4d86-81d1-1a4e2f24d660">
Just to make sure which rule to follow.

2023-06-16 17:51 UTC, jsmerix commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +    def test_download_ohlcv_timestamp_representation_helper(
Sure why not, as I said, it's a nit-picky remark, we can keep it your way, fine by me, let's if GP sneaks in with a decisive opinion.

2023-06-16 17:56 UTC, yiyunlei commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +        expected_output = expected_output.strip()
Actually, not necessary. I'll delete it.

2023-06-16 18:03 UTC, yiyunlei commented on im_v2/ccxt/data/extract/test/test_ccxt_extractor.py
> +    def test_download_ohlcv_timestamp_representation_helper(
`_test_download_ohlcv_timestamp_representation_helper` is better IMO, so I'll use this one for now.

2023-06-16 21:14 UTC, yiyunlei commented
The linter placed the helper function at the end.

2023-06-19 09:07 UTC, jsmerix approved these changes
Ready to merge, well done.

2023-06-19 11:32 UTC, gpsaggese reviewed
Good work

2023-06-19 11:32 UTC, merged

2023-06-19 15:17 UTC, yiyunlei commented
@DanilYachmenev @jsmerix Thanks for all the reviews! They helped me a lot and also enhanced my understanding of code style and how to write clean, understandable code.