Sorrtask298 rename get docker cmd to get docker run cmd
sorrentum/sorrentum pull request #331
Opened 2023-06-15 13:00 UTC by zli00185

2023-06-15 15:23 UTC, samarth9008 commented
Does your script work as expected? If so, push those files too where replacement has happened.

2023-06-15 16:06 UTC, zli00185 commented
The directory path will change if I run it locally. Do I keep the local path or the one from Juypter notebook?

2023-06-15 16:17 UTC, samarth9008 commented on dev_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
> +dir_names="/Users/leosmacbook/Desktop/Sorretum_Intern"
This dir name doesn't work for us as it us local to your system. Update the script accordingly. Take a look at other scripts.

2023-06-15 16:18 UTC, samarth9008 commented
> The directory path will change if I run it locally. Do I keep the local path or the one from Juypter notebook?

Whats the need of using jupyter notebook in this?

2023-06-15 16:30 UTC, DanilYachmenev commented on dev_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
> +dir_names="/Users/leosmacbook/Desktop/Sorretum_Intern"
And also, I see no reason to use it here at all
in fact in current shape the changes will be done only in the specified dir

read `replace_text.py` to see how params do work

2023-06-15 16:36 UTC, zli00185 commented
I though we would use the path from docker container since that is same for everyone.

2023-06-15 18:19 UTC, samarth9008 commented on dev_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
> +dir_names="/Users/leosmacbook/Desktop/Sorretum_Intern"
@zli00185 When you make any changes according to the comments, please click the Resolve button. When submit a PR add reviewers so that they are notified.

2023-06-15 18:24 UTC, DanilYachmenev reviewed
no need to exclude the script itself

when nit is fixed, lgtm

2023-06-15 18:24 UTC, DanilYachmenev commented on dev_scripts/cleanup_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
> +curr_file="/amp/dev_scripts/cleanup_scripts dev_scripts/cleanup_scripts"
no need for this one either

2023-06-15 18:24 UTC, DanilYachmenev commented on dev_scripts/cleanup_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
> +    --exclude_dirs "$curr_file"
and no need for this as well

2023-06-16 13:56 UTC, zli00185 commented on dev_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
> +dir_names="/Users/leosmacbook/Desktop/Sorretum_Intern"
okay

2023-06-16 14:06 UTC, samarth9008 commented
You committed wrong changes. Now your old and new both are same so basically nothing will be replaced. You needed to remove currfiles and exclude dir. After doing that test your script again. If it works then only push it.

2023-06-16 15:34 UTC, samarth9008 commented
Modify your script correctly. Create a dummy file to test it. If it works, delete the dummy file and only push the new scripts. Now you cannot test on the previous files because they are already replaced.

2023-06-16 15:38 UTC, samarth9008 requested changes

2023-06-16 15:38 UTC, samarth9008 commented on dev_scripts/cleanup_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
> -    --new "_get_docker_run_cmd" \
The `--old` and `--new` has same args. So this is not correct.

2023-06-16 15:38 UTC, samarth9008 commented on dev_scripts/cleanup_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
Remove empty space.

2023-06-16 15:46 UTC, samarth9008 commented on dev_scripts/cleanup_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
> -    --new "_get_docker_run_cmd" \
Nothing changed over here.

2023-06-16 15:47 UTC, zli00185 commented on dev_scripts/cleanup_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
> -    --new "_get_docker_run_cmd" \
The file itself will get rename as well. So I need the version before running it, right?

2023-06-16 15:48 UTC, samarth9008 commented on dev_scripts/cleanup_scripts/SorrTask298_rename_get_docker_cmd_to_get_docker_run_cmd.sh
> -    --new "_get_docker_run_cmd" \
Yes.

2023-06-16 15:50 UTC, samarth9008 approved these changes

2023-06-17 13:45 UTC, merged