Create Development_workflow.md
sorrentum/sorrentum pull request #338
Opened 2023-06-20 18:42 UTC by dchoi127

Didn't realize issue was assigned to me. My apologies

2023-06-20 18:51 UTC, dchoi127 commented
Hmm. The code blocks don't seem to be converted nicely.

2023-06-21 14:17 UTC, samarth9008 commented
Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh). Refer that file to generate TOC.

2023-06-21 16:39 UTC, samarth9008 requested changes
You need to make a lot of improvements in this PR. The content which should be inside the code blocks is outside and vice-versa. Although it seems like I have to reviewed your PR completely but the mistakes are same and repeated everywhere. Go through the whole doc and make improvements everywhere where required. Do not limit it to just my comments.

2023-06-21 16:39 UTC, samarth9008 commented on docs/Development_workflow.md
> +i git_merge_master
i git_merge_master -> `i git_merge_master`

2023-06-21 16:39 UTC, samarth9008 commented on docs/Development_workflow.md
> +all the code is merged.
I am not sure if the formatting of this section is correct, although it is mentioned this way in the doc. Wdyt @DanilYachmenev ?

2023-06-21 16:39 UTC, samarth9008 commented on docs/Development_workflow.md
> +### Using git
From here, the whole new section begin but you have included them in code formatting which should end on the line 635 but not on 662. Refer to doc to get a clear idea. The index on the left side of the doc can give you proper idea.

2023-06-21 16:39 UTC, samarth9008 commented on docs/Development_workflow.md
> +## Systematic code transformation
This is also a new section.

2023-06-21 16:39 UTC, samarth9008 commented on docs/Development_workflow.md
> +## Generate a local `amp` Docker image
This section comes under `docker` section.

2023-06-21 16:39 UTC, samarth9008 commented on docs/Development_workflow.md
> +```
This whole section should go inside code formatting. Refer to the doc.

2023-06-21 16:39 UTC, samarth9008 commented on docs/Development_workflow.md
> +> exit
This should be inside the code block.

2023-06-21 16:39 UTC, samarth9008 commented on docs/Development_workflow.md
> +You should test that the package is installed for your user, e.g.,
This is not inside the code blocks.

2023-06-21 16:39 UTC, samarth9008 commented on docs/Development_workflow.md
> +> print(foobar.**version**)"
Inside the code blocks.

2023-06-22 01:20 UTC, dchoi127 commented
Im not sure what the Github Actions section is supposed to be, but I believe I have changed the issues described.

2023-06-22 17:26 UTC, samarth9008 reviewed
I understand you implemented something as-in from the doc but here are some improvements.

2023-06-22 17:26 UTC, samarth9008 commented on docs/Development_workflow.md
> +# Detailed instructions
This is not a new section. Lets add it under `Publish a notebook`. So, `# Detailed instructions` -> `## Detailed instructions`

2023-06-22 17:26 UTC, samarth9008 commented on docs/Development_workflow.md
> +If you don't have them, you need to re-run `source dev_scripts/seten.sh` in all
`source dev_scripts/seten.sh` -> `source dev_scripts/setenv.sh`

2023-06-22 17:26 UTC, samarth9008 commented on docs/Development_workflow.md
> +'s3://alphamatic-data/notebooks/Task40_Optimizer.20210717_010806.html'
Code formatting.

2023-06-22 17:26 UTC, samarth9008 commented on docs/Development_workflow.md
> +> [https://github.com/cryptomtc/cmamp.git](https://github.com/cryptomtc/cmamp.git)
Code format.

2023-06-22 17:26 UTC, samarth9008 commented on docs/Development_workflow.md
> +### Set-up
`### Set-up` -> `## Set-up`

2023-06-22 17:26 UTC, samarth9008 commented on docs/Development_workflow.md
> +> git remote add public [git@github.com](mailto:git@github.com):alphamatic/amp
`git remote add public [git@github.com](mailto:git@github.com):alphamatic/amp` -> `git remote add public git@github.com:alphamatic/amp`

2023-06-22 17:26 UTC, samarth9008 commented on docs/Development_workflow.md
> +```
This whole under one code block.

2023-06-22 17:26 UTC, samarth9008 commented on docs/Development_workflow.md
> +> git fetch origin; git fetch public
Code format

2023-06-22 17:26 UTC, samarth9008 commented on docs/Development_workflow.md
> +> [git@github.com](mailto:git@github.com):cryptomtc/cmamp.git
`[git@github.com](mailto:git@github.com)` -> `git@github.com`

2023-06-22 17:26 UTC, samarth9008 commented on docs/Development_workflow.md
> +> /Users/saggese/src/amp1/dev_scripts/integrate_repos/setup.sh
```
cd  ~/src/amp1
source /Users/saggese/src/amp1/dev_scripts/integrate_repos/setup.sh

cd ~/src/cmamp1
source /Users/saggese/src/amp1/dev_scripts/integrate_repos/setup.sh
```

2023-06-22 17:26 UTC, samarth9008 commented on docs/Development_workflow.md
> +im/ccxt/data/load/test/test_loader.py
amp needs two tests disabled
im/ccxt/data/load/test/test_loader.py
im/ccxt/data/load/test/test_loader.py

Different lines.

2023-06-26 14:29 UTC, samarth9008 requested changes
Not every comment is addressed. If you have doubts ask under that comments but pls implement all the changes and then only request for a review.

2023-06-26 14:29 UTC, samarth9008 commented on docs/Development_workflow.md
> +
Can you pls remove these empty spaces from top?

2023-06-26 14:29 UTC, samarth9008 commented on docs/Development_workflow.md
> +- [Detailed instructions](#detailed-instructions)
This is not a heading. I understand it was starting with # in the doc but you can include the whole the code block.

2023-06-26 14:29 UTC, samarth9008 commented on docs/Development_workflow.md
> +- by listing running containers, e.g., run `docker ps` outside the container
Same indentation. Should be a sub-section of `Copy your Container ID. You can find it`.

2023-06-26 14:29 UTC, samarth9008 commented on docs/Development_workflow.md
> +`docker commit da8f3bb8f53b 665840871993.dkr.ecr.us-east-1.amazonaws.com/cmamp:local-julias`
Let's move them slightly to the right so they look like they are under the  `- Commit image` section.

2023-06-26 14:29 UTC, samarth9008 commented on docs/Development_workflow.md
> +branch
Implement this as I said.

2023-06-26 19:22 UTC, samarth9008 reviewed
Some improvements on whole doc. 

1. Start a new line with a bullet point. Just the way you did for `Implementation details` section. Run the linter again to generate a new TOC. 
2. On the top of the files add the name of the doc. Refer to other doc for clear idea.

2023-06-26 19:22 UTC, samarth9008 commented on docs/Development_workflow.md
> +
This whole inside a code block.

2023-06-26 19:22 UTC, samarth9008 commented on docs/Development_workflow.md
> +      for changes
Slide all of them to right so they look like a sub section. Remove unnecessary space.

2023-06-26 19:22 UTC, samarth9008 commented on docs/Development_workflow.md
> +- Run dev_tools on the dev server
Remove spaces.

2023-06-27 06:04 UTC, dchoi127 commented on docs/Development_workflow.md
> +- Run dev_tools on the dev server
By spaces do you mean empty lines?

2023-06-27 12:56 UTC, samarth9008 commented on docs/Development_workflow.md
> +- Run dev_tools on the dev server
Yes

2023-06-27 22:29 UTC, dchoi127 commented
Implementing changes but also made sure to indent code blocks so that it matches the corresponding bullet point. 

For some reason running the linter puts empty lines in some places. Over the course of me implementing the changes the linter script was ran multiple times and I had to manually redo the work multiple times because I didn't realize it was the linter script causing the empty lines (thought it was me just missing them).

2023-06-27 23:41 UTC, gpsaggese commented
In general we just let the linter do its thing.

Can you explain what's the problem with the white lines?

2023-06-28 01:35 UTC, dchoi127 commented
> In general we just let the linter do its thing.
> 
> Can you explain what's the problem with the white lines?

I was advised to delete unnecessary white spaces (empty lines). In the process of doing that I had ran the linter script to regenerate the TOC and seems to have added empty lines between code blocks. Is that okay?

2023-06-28 09:20 UTC, DanilYachmenev commented
@dchoi127 `lint_md.sh` does this in some cases
check how the file looks in the preview mode
if spaces are not reflected there and bullet list looks good, I'd say it is OK to leave it as is here

however, in general, especially in the code, avoid leaving empty lines

2023-06-28 09:40 UTC, DanilYachmenev reviewed
almost there actually, see the comments

2023-06-28 09:40 UTC, DanilYachmenev commented on docs/Development_workflow.md
> +Get the official branch name corresponding to an Issue
Take it out of the code block:
```
- Get the official branch name corresponding to an Issue
    ```
    > ...
```

2023-06-28 09:40 UTC, DanilYachmenev commented on docs/Development_workflow.md
> +  ```
all the tripple backticks should be either followed by `python` or `bash` - corresponding  to where the command is called
so here it should be like
```
    ```python
    from...
```

do this for every other code block

usually most commands that are preceeded with `>` and include git commands like `cd`,  `git` etc., invokes like `i`, `invoke` or script calls are run in `bash` and this is the case for most other code blocks in this file

2023-06-28 09:40 UTC, DanilYachmenev commented on docs/Development_workflow.md
> +## Munge list of failed tests
remove since these are related to unit test doc and here they are simply empty

2023-06-28 09:40 UTC, DanilYachmenev commented on docs/Development_workflow.md
> +  im/ccxt/data/load/test/test_loader.py
dir names (`amp`, `cmamp` etc.) and filenames (`helpers/lib_tasks.py`, `im/ccxt...`) should be put in backticks as code, change everywhere

2023-06-28 09:40 UTC, DanilYachmenev commented on docs/Development_workflow.md
> +  Build the local image (and update Poetry dependencies, if needed).
add `#` before the comment

2023-06-28 17:45 UTC, dchoi127 commented
Implemented the changes. What is fast tests?

2023-06-28 20:01 UTC, DanilYachmenev commented
> Implemented the changes. What is fast tests?

hmm, weird that they fail here actually
they are not related to your changes and actually should not even impact `sorrentum` PRs IIRC
@gpsaggese do you know what could be the reason behind it?

2023-06-28 20:02 UTC, samarth9008 approved these changes

2023-06-28 20:22 UTC, gpsaggese commented
I was trying to get the tests to pass in this repo. You can ignore it

2023-06-28 20:24 UTC, merged