Added markdown file
sorrentum/sorrentum pull request #339
Opened 2023-06-21 05:41 UTC by lokashrinav

I'm pushing the branch with my code. Am I supposed to create a pull request?

2023-06-21 05:42 UTC, lokashrinav commented
It says that there are no conflicts with the base branch. Can I squash and merge this?

2023-06-21 12:35 UTC, samarth9008 commented
> It says that there are no conflicts with the base branch. Can I squash and merge this?

No you cannot and you should never.

Go through this doc. https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md

Also name your PR according to the Issue.

I will review it shortly.

2023-06-21 13:39 UTC, lokashrinav commented
@samarth9008 Alright thanks! Just checked out that only team leaders can squash and merge. I'll rename the PR in a second.

2023-06-22 19:38 UTC, samarth9008 commented
If you want your PR to reviewed by us

Go through this doc. https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md 

Make changes accordingly.

2023-06-22 21:13 UTC, samarth9008 requested changes
- Anything that start on the new line in doc will begin with the bullet points.
- Every new line will begin with bullet points which you have to add on the whole doc.
- Refer the linter to add TOC in the files automatically.

2023-06-22 21:13 UTC, samarth9008 commented on super.md
> +Given that both explanations are valid, we allow both styles.
Improve the formatting according to the doc.

2023-06-22 21:13 UTC, samarth9008 commented on super.md
> +- E.g., we use `test/foobar_test_case.py` or `test/foobar_utils.py`
Improve the formatting according to the doc.

2023-06-22 21:13 UTC, samarth9008 commented on super.md
> +- Any time we can break a file into smaller pieces, we should do that since this helps control the dependencies.
Improve the formatting of this whole section. Refer to the doc.

2023-06-22 21:13 UTC, samarth9008 commented on super.md
> +A package has a special `__init__.py` exporting public methods
Same for this.

2023-06-23 17:38 UTC, samarth9008 commented
Change the location of your file to `docs/`. Also change the name to what it represents.

2023-06-26 06:52 UTC, lokashrinav commented on super.md
> +E.g., referring to package from a different package looks like
Hello @samarth9008. Sorry if this is a dumb question but where do I implement your changes from? Should I create a codespace?

2023-06-26 12:20 UTC, samarth9008 commented on super.md
> +E.g., referring to package from a different package looks like
In the same file on the same branch. Implement the changes and push it again. Make sure all the changes are reflected.

2023-06-28 08:57 UTC, lokashrinav commented
#329

2023-06-30 15:48 UTC, samarth9008 commented
Any updates on this? @lokashrinav

2023-07-01 13:26 UTC, lokashrinav commented
@samarth9008 Hey Samarth. I'm trying to fix a bug myself related to my usage of the linter. My understanding is that the linting did not properly work, and I'm just trying to uncover why. I don't wish to interrupt any important work as you are likely busy, but would you like me to paste my commands and outputs on the terminal for you to check it out?

2023-07-02 12:03 UTC, gpsaggese commented
@lokashrinav the linter is quite complex to run and debug. You can file a bug with a nice bug report as per our doc (reproducible example, command line, output) and then we can prioritize.
Then you can fix the issue manually to get your work done.

2023-07-03 18:24 UTC, lokashrinav commented
@gpsaggese Alright thanks. I'm doing that right now

2023-07-04 17:02 UTC, samarth9008 commented
Any updates?? @lokashrinav

2023-07-07 03:20 UTC, lokashrinav commented
@samarth9008 I'll have it done by tomorrow

2023-07-08 04:10 UTC, lokashrinav commented
@samarth9008 I made a few edits. If you have the time, would it be possible for you to check them out?

2023-07-10 12:43 UTC, samarth9008 commented
pls go through this doc https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md

2023-07-10 13:01 UTC, samarth9008 requested changes
Any new line the doc will start with a bullet point in md file. Run the linter again after making changes.

2023-07-10 13:41 UTC, samarth9008 commented
Look at the rendered md file after you create it. Make sure the formatting and content is same as the doc.

2023-07-12 13:28 UTC, samarth9008 commented
Don't forget to run the linter.

2023-07-12 13:33 UTC, samarth9008 commented
pls go through this doc https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md. Do it carefully.

2023-07-13 13:22 UTC, DanilYachmenev commented on docs/Python_Imports_and_packages
name should be `Python_Imports_and_packages.md`
otherwise it is commited as a simple text file

2023-07-13 13:56 UTC, DanilYachmenev commented on docs/Python_Imports_and_packages.md
> +    - hide in which file the actual code is, so that we can reorganize the code without having to change all the client code
start each bullet point from capital letter(unless it is a code)

2023-07-13 13:56 UTC, DanilYachmenev commented on docs/Python_Imports_and_packages.md
> +        - E.g., im_v2/common/data/client/data_frame_im_clients.py
put file paths and code objects in backticks `

2023-07-13 13:56 UTC, DanilYachmenev commented on docs/Python_Imports_and_packages.md
> +    2. Code from a package should import other packages, instead of importing directly the file
replace all the numeric bullet points with just `-`

2023-07-13 13:56 UTC, DanilYachmenev commented on docs/Python_Imports_and_packages.md
> +    - Any import inside a function is just a temporary hack waiting to create problems.
remove dots at the end of bullet points for consistency

2023-07-13 13:56 UTC, DanilYachmenev commented on docs/Python_Imports_and_packages.md
> +            ```
extra empty line

2023-07-13 13:56 UTC, DanilYachmenev commented on docs/Python_Imports_and_packages.md
> + - To justify 2., one can interpret that unit tests are tied to specific files, so they should be kept in sync with the low-level code and not with the public interface. In fact, we already allow uni
run `lint_md` after implementing the comments. it should wrap lines to 80-chars limit

2023-07-14 01:32 UTC, lokashrinav commented on docs/Python_Imports_and_packages.md
> +    2. Code from a package should import other packages, instead of importing directly the file
@DanilYachmenev I can't do it for all of the document because then it'll mess up the following. The paragraphs below the points rely on the numeric bullet points. Should I keep it as is?:     

1. Import the package when testing code exported from the package
        - E.g., in `market_data/test/market_data_test_case.py` you can import the package even if it's included
            ```python
            import market_data as mdata
            … mdata.AbstractMarketData …
            ```
    2. Import the files directly with the code and not the package
        - E.g.,
            ```python
            import market_data.abstract_market_data as mdabmada
            … mdabmada.AbstractMarketData …
            ```
 - To justify 1., one can argue that unit tests are clients of the code and should import packages like any other client
 - To justify 2., one can interpret that unit tests are tied to specific files, so they should be kept in sync with the low-level code and not with the public interface. In fact, we already allow unit tests to call private functions, acknowledging that unit tests are not regular clients
 - Given that both explanations are valid, we allow both styles

2023-07-14 10:07 UTC, DanilYachmenev commented on docs/Python_Imports_and_packages.md
> +  4. Hgit (Git requires accessing env vars and system calls)
`hdbg`, `hintrospection`, etc iow all the `h*` type words are actually code references that should be put in backticks and start from a lowercase letter

check and fix everywhere in the file

btw here numbers are ok to use

2023-07-14 10:07 UTC, DanilYachmenev commented on docs/Python_Imports_and_packages.md
> +      ```
what I dont like that after these the text style changes drastically, you can see it in when reviewing code at GH

we suggestion would be to remove unnecessary empty lines between examples and bullet points, remove bool text and try to achieve the state at which text below this line would not be colored and perceived as python
<img width="587" alt="Снимок экрана 2023-07-14 в 17 05 24" src="https://github.com/sorrentum/sorrentum/assets/31514660/4341f8f1-93b8-47c1-a702-4b65071ba359">

2023-07-14 10:07 UTC, DanilYachmenev commented on docs/Python_Imports_and_packages.md
rename to `Imports_and_packages.md` in order to comply with the name

2023-07-14 10:07 UTC, DanilYachmenev commented on docs/Python_Imports_and_packages.md
> +    2. Code from a package should import other packages, instead of importing directly the file
https://github.com/sorrentum/sorrentum/pull/339#discussion_r1263543785

2023-07-17 08:06 UTC, DanilYachmenev commented on docs/Imports_and_packages.md
> +  import cycle
do it like 
```
- A library can only import libs that are "below" it or on the same level
    - E.g., `henv` can import `hdbg`, `hprint`, and `hio`, but it cannot import `hgit`
    - While importing a lib on the same level, make sure you are not creating an import cycle
```

2023-07-17 08:06 UTC, DanilYachmenev commented on docs/Imports_and_packages.md
Add a hyperlink ref to this file to `/docs/README.md` file in `Project management` section as the last point
```
- Imports and packages
    - How to import code, use packages, and resolve circular dependencies
```

2023-07-19 18:26 UTC, samarth9008 requested changes

2023-07-19 18:26 UTC, samarth9008 commented on docs/Imports_and_packages.md
> +       functions, acknowledging that unit tests are not regular clients
Keep this in line with `- To avoid churning client code when code is moved among files, we allow unit
  tests to both:` There are two different points. You have mixed both of them and are not complete.

2023-07-19 18:26 UTC, samarth9008 commented on docs/Imports_and_packages.md
> +  - In other terms, test files are always leaves of the import graph
Look at the doc for formatting

2023-07-25 17:40 UTC, samarth9008 commented
Whats the status @lokashrinav ?

2023-07-25 21:10 UTC, samarth9008 commented
Resolve the conflict. We have moved the readme file to root of the repo.

2023-07-26 13:34 UTC, samarth9008 requested changes

2023-07-26 13:34 UTC, samarth9008 commented on docs/Imports_and_packages.md
> +  lint_detect_cycles. By default, it will run on the whole repo, which takes a
-> `i lint_detect_cycles`

2023-07-26 13:34 UTC, samarth9008 commented on docs/Imports_and_packages.md
> +       functions, acknowledging that unit tests are not regular clients
These two points should switch their position.

2023-07-27 18:08 UTC, DanilYachmenev reviewed
lgtm

2023-07-27 18:14 UTC, samarth9008 approved these changes
LG

2023-07-27 18:36 UTC, merged