Tools - Profiling gdoc to md
sorrentum/sorrentum pull request #435
Opened 2023-07-20 15:41 UTC by Ro0k1e

Issue [#428](https://github.com/sorrentum/sorrentum/issues/428)

2023-07-20 19:15 UTC, samarth9008 commented
Also add @DanilYachmenev as a reviewer. Assign this PR to yourself.

2023-07-20 19:29 UTC, samarth9008 requested changes

2023-07-20 19:29 UTC, samarth9008 commented on docs/Tools_Profiling.md
> +# Profiling end-to-end a command line
You add name of the file over here which is `Tools - Profiling`. This will be first in TOC.

2023-07-20 19:29 UTC, samarth9008 commented on docs/Tools_Profiling.md
> +- [Memory profilers](#memory-profilers)
The index should look like this. Modify the heading in the doc and run the linter again to generate the TOC on its own.
![image](https://github.com/sorrentum/sorrentum/assets/58821247/5720ccc7-8d04-4573-91db-da61fe03accf)

2023-07-20 19:29 UTC, samarth9008 commented on docs/Tools_Profiling.md
> +```
No need for this extra spaces in between inside the code format. Improve it everywhere.

2023-07-20 19:29 UTC, samarth9008 commented on docs/Tools_Profiling.md
> +amp/dev_scripts/run_profiling.sh
Lets add this in code format.

2023-07-20 19:29 UTC, samarth9008 commented on docs/Tools_Profiling.md
> +time_memory_profiling_example.ipynb notebook.
time_memory_profiling_example.ipynb -> `time_memory_profiling_example.ipynb`

2023-07-20 19:29 UTC, samarth9008 commented on docs/Tools_Profiling.md
> +<img src="Tools_Profiling_figs/image1.png" style="width:6.5in;height:12.5in" />
Both images are not displayed

2023-07-24 14:04 UTC, DanilYachmenev commented on docs/Tools_Profiling.md
> +`%prun magic uses cProfile under the hood, so we can use it in the notebook instead: `
put only `%prun` in backticks so the text following it is not formatted as code

2023-07-25 06:09 UTC, closed without merging

2023-07-25 12:46 UTC, gpsaggese commented
Not sure I understand what happened here. Why was the PR closed?

2023-07-25 17:36 UTC, DanilYachmenev commented
@Ro0k1e just a reminder for further work - you should never merge changes to the master by yourself ok?
Only integrators are responsible for this
Just in case

2023-07-25 17:38 UTC, Ro0k1e commented
> @Ro0k1e just a reminder for further work - you should never merge changes to the master by yourself ok? Only integrators are responsible for this Just in case

Sure! Thank you so much for the reminder and sorry for the confusion. What I meant was a pull request.

2023-07-25 19:02 UTC, gpsaggese commented
> > Not sure I understand what happened here. Why was the PR closed?
> 
> Hi GP!
> 
> To deal with issue #428, I created a branch [SorrIssue428_Tools_Profiling_gdoc_to_md](https://github.com/sorrentum/sorrentum/tree/SorrIssue428_Tools_Profiling_gdoc_to_md) to be merged to the master and this PR. Yesterday I found that there were some changes to the master, and the branch was not up-to-date. I was afraid that merging the branch to the master might introduce some outdated files to the master, so I closed this PR, deleted the old branch, and created a new one with the same name based on the updated master. The new PR can be found here: #452.

I understand
1) Git allows you to do all these things seamlessly, without creating new branches. E.g., you could have just merge master and accept your branch in case of conflicts
- Pls put some time in studying https://github.com/gpsaggese/umd_data605/blob/main/lectures/02.1%20-%20Git%2C%20Data%20Pipelines.pdf and the Git book. It will pay 10x
2) You can add an explanation (like this) in the PR before closing. Otherwise people wonder what the heck happened? (principle of least surprise)

@DanilYachmenev I've updated the merging rules so we should not have rogue merges. Let's monitor and improve the rules for a pacific coexistence.

2023-07-25 19:10 UTC, Ro0k1e commented
> > > Not sure I understand what happened here. Why was the PR closed?
> > 
> > 
> > Hi GP!
> > To deal with issue #428, I created a branch [SorrIssue428_Tools_Profiling_gdoc_to_md](https://github.com/sorrentum/sorrentum/tree/SorrIssue428_Tools_Profiling_gdoc_to_md) to be merged to the master and this PR. Yesterday I found that there were some changes to the master, and the branch was not up-to-date. I was afraid that merging the branch to the master might introduce some outdated files to the master, so I closed this PR, deleted the old branch, and created a new one with the same name based on the updated master. The new PR can be found here: #452.
> 
> I understand
> 
> 1. Git allows you to do all these things seamlessly, without creating new branches. E.g., you could have just merge master and accept your branch in case of conflicts
> 
> * Pls put some time in studying https://github.com/gpsaggese/umd_data605/blob/main/lectures/02.1%20-%20Git%2C%20Data%20Pipelines.pdf and the Git book. It will pay 10x
> 
> 2. You can add an explanation (like this) in the PR before closing. Otherwise people wonder what the heck happened? (principle of least surprise)
> 
> @DanilYachmenev I've updated the merging rules so we should not have rogue merges. Let's monitor and improve the rules for a pacific coexistence.

Understood! Thank you so much for the help!