Sorr task538 centralize input validation when running etl scripts
sorrentum/sorrentum pull request #552
Opened 2023-08-24 20:53 UTC by Sameep2808

Task #538 @DanilYachmenev I have created the new file and transferred the functions as per the issue

2023-08-24 21:27 UTC, DanilYachmenev reviewed
sg, couple moments

2023-08-24 21:27 UTC, DanilYachmenev commented on im_v2/common/data/qa/validate_input_args.py
> +#!/usr/bin/env python
remove
this one is needed only for scripts, and this is a lib file

2023-08-24 21:27 UTC, DanilYachmenev commented on im_v2/common/data/qa/validate_input_args.py
> +Centralizing checking logical dependencies between values of various arguments
-> `Centralize ...`

2023-08-24 21:27 UTC, DanilYachmenev commented on im_v2/common/data/qa/validate_input_args.py
> +    :param vendor: string to get the vendor
-> `:param vendor: vendor name`

2023-08-24 21:27 UTC, DanilYachmenev commented on im_v2/common/data/qa/validate_input_args.py
> +    """
add also `:return: vendor data extractor`

2023-08-24 21:27 UTC, DanilYachmenev commented on im_v2/common/data/qa/validate_input_args.py
> +def validate_vendor_arg(
@jsmerix should we maybe give it a different name?
it seems that this function now is rather about getting extractor than just validation

2023-08-25 07:17 UTC, jsmerix requested changes

2023-08-25 07:17 UTC, jsmerix commented on im_v2/common/data/qa/validate_input_args.py
> +def validate_vendor_arg(
If this module is for validation then only validations (assertions) belong here. 
This function should only check:
- if vendor belongs to one of the three supported
- If `universe_part` is included when  the vendor arg is `crypto_chassis`

Having a function which returns the correct instance is also useful but should belong to a different module, okay for me to file a follow-up.

2023-08-25 09:58 UTC, DanilYachmenev commented on im_v2/common/data/qa/validate_input_args.py
> +def validate_vendor_arg(
git it, thx

```
def validate_vendor_arg(vendor: str, args: argparse.Namespace) -> None:
    """
    Validate vendor args.
    
    :param vendor: vendor name
    :param args: ETL script args
    """
    hdbg.dassert_in(vendor, ["binance", "ccxt", "crypto_chassis"], msg=f"Vendor {vendor} is not supported.")
    if vendor == "crypto_chassis":
        if not args.get("universe_part"):
            raise RuntimeError(
                f"--universe_part argument is mandatory for {vendor}"
            )
```

@Sameep2808 lets implement the changes here
update the script accordingly (run this function first and then init extractor)

2023-08-25 19:20 UTC, Sameep2808 commented
@DanilYachmenev did the required changes you can have a look now

2023-08-25 19:29 UTC, jsmerix approved these changes

2023-08-27 10:14 UTC, DanilYachmenev reviewed
1 nit and lgtm

2023-08-27 10:14 UTC, DanilYachmenev commented on im_v2/common/data/extract/download_bulk.py
> -        hdbg.dfatal(f"Vendor {vendor} is not supported.")
lets keep these lines
`if` clauses should always be completed with `else`
https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md#make-if-elif-else-complete

2023-08-27 16:34 UTC, Sameep2808 commented
> lets keep these lines `if` clauses should always be completed with `else` https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md#make-if-elif-else-complete

@DanilYachmenev I just thought that would have been a DRY with [this](https://github.com/sorrentum/sorrentum/pull/552/files#:~:text=else%3A,not%20supported.%22)

2023-08-27 17:10 UTC, Sameep2808 commented
> lets keep these lines `if` clauses should always be completed with `else` https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md#make-if-elif-else-complete

I thought that `else` would be DRY with [this](https://github.com/sorrentum/sorrentum/pull/552/files#:~:text=hdbg.dassert_in,not%20supported.%22%2C)

2023-08-27 23:58 UTC, gpsaggese commented
> > lets keep these lines `if` clauses should always be completed with `else` https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md#make-if-elif-else-complete
> 
> I thought that `else` would be DRY with [this](https://github.com/sorrentum/sorrentum/pull/552/files#:~:text=hdbg.dassert_in,not%20supported.%22%2C)

This is a valid point, but in this case the DRY principle succumbs to keeping the code maintainable. 

I would write the code like:

```python
    hdbg.dassert_in(
        vendor,
        ["binance", "ccxt", "crypto_chassis"],
        msg=f"Vendor {vendor} is not supported.",
    )
    if vendor == "crypto_chassis":
        if not args.get("universe_part"):
            raise RuntimeError(
                f"--universe_part argument is mandatory for {vendor}"
            )
    elif vendor == "ccxt":
        # Do something or raise NotImplementedError
    elif vendor == "crypto_chassis":
        # Do something or raise NotImplementedError
    else:
        raise ValueError("Invalid error vendor='${vendor}'")
```

Assume that you add another vendor, then we centralize the assertion and add a new vendor to assertion.
Then we need to go and update all the if-then-else everywhere.
Surely we will miss one. With your solution you will get a silent error (return a `None`), the solution above will at least assert and you can find that there is a missing branch.

If the code in each branch I would actually remove the `dassert`.
The `dassert` is mainly to fail quickly, but it is redundant. So you need a way to keep the redundancy in sync, hence the `else`.

From docs/Reading_List.md
```
# Coding

- [The Pragmatic Programmer](https://www.amazon.com/Pragmatic-Programmer-Journeyman-Master/dp/020161622X)
  - Aka the Black Book
  - Reading (and really internalizing) this book is equivalent to the experience
    you can gain by coding for 20 years
  - It will change your life

- [Code Complete: A Practical Handbook of Software Construction, Second
  Edition](https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670)
  - Likely the only decent product ever made by Micro$oft
```

2023-08-28 01:43 UTC, Sameep2808 commented
> Assume that you add another vendor, then we centralize the assertion and add a new vendor to assertion.
> Then we need to go and update all the if-then-else everywhere.
> Surely we will miss one. With your solution you will get a silent error (return a `None`), the solution above will at least assert and you can find that there is a missing branch.

> If the code in each branch I would actually remove the `dassert`.
> The `dassert` is mainly to fail quickly, but it is redundant. So you need a way to keep the redundancy in sync, hence the `else`.

@gpsaggese Thanks for clarifying I understood why the `else` should be implemented. Will keep this in mind for the future implementation.

Just one clarification. 

> ```python
>     elif vendor == "ccxt":
>         # Do something or raise NotImplementedError
>     elif vendor == "crypto_chassis":
>         # Do something or raise NotImplementedError
>     else:
>         raise ValueError("Invalid error vendor='${vendor}'")
> ```

The above part is already implemented [here](https://github.com/sorrentum/sorrentum/blob/edbd2a2133ace3e5e250a93b6d3f06826f80b64a/im_v2/common/data/extract/download_bulk.py#L82C9-L96C58) just after this function is called. As discussed earlier in this issue this function that we are implementing is just for validation purpose. And hence the remaining else if were transferred back to `im_v2/common/data/extract/download_bulk.p`. But do let me know if you want me to transfer it back and I'll make the needed changes.

2023-08-28 11:08 UTC, DanilYachmenev reviewed
lgtm

2023-08-28 19:46 UTC, gpsaggese commented
Let's make the changes for this bug and I've filed a follow up bug #557

2023-09-12 17:03 UTC, jsmerix approved these changes

2023-09-12 17:03 UTC, merged