Sorr task561 allow saving exchange data to local directory
sorrentum/sorrentum pull request #562
Opened 2023-08-29 21:08 UTC by Sameep2808

@jsmerix I have implemented a draft of the `dst_dir` argument and `validate_dst_dir_arg` function and updated the file `im_v2/common/data/extract/extract_utils.py::process_downloaded_historical_data` to handle local downloads.

Just need few clarifications before I move forward:
1. Do you want the `validate_dst_dir_arg` function in `im_v2/common/data/extract/download_bulk.py` file or do you want me to create a different file` im_v2/common/data/qa/validate_input_args.py` like I created in task #538.
2. Should the validate function raise an error or should it only give warning and go ahead
3. Do you want me to implement a save_csv function for local which can handle `incremental` arg or the current way is fine.

2023-08-30 08:52 UTC, jsmerix requested changes
Well executed, mostly small stuff and conventions that we need to polish.

2023-08-30 08:52 UTC, jsmerix commented on im_v2/common/data/extract/download_bulk.py
> +            raise RuntimeError(f"--s3_path argument present")
To your first question yes this goes inside `im_v2/common/data/qa/validate_input_args.py`
To the second question - raising an error is better so the way you created is the correct way.

2023-08-30 08:52 UTC, jsmerix commented on im_v2/common/data/extract/download_bulk.py
> +                    'csv' or 'parquet'")
Let's create the list of supported formats as a constant, this way you have centralized solution when we decide to support a new format.
- if checks a presence in the list
- `RuntimeError` references the list
- Also a nit picky detail is that `ArgumentError` is probably better here.

2023-08-30 08:52 UTC, jsmerix commented on im_v2/common/data/extract/extract_utils.py
> +            hdbg.dfatal(f"Unsupported `{args['data_format']}` format!")
To your third question - as we can see this code lost its structure and became a bit convoluted over time as the features started to pile on, but it's fine for now, let's leave `save_csv` as is and the cleanup for some other time.

2023-08-30 08:52 UTC, jsmerix commented on im_v2/common/data/extract/test/test_extract_utils.py
> +                number_of_seconds=4,
Overall well implemented can you just rather use `CcxtExctractor`, The Chassis one is no longer actively used so it is better not to create any new code referencing it.

2023-08-30 08:52 UTC, jsmerix commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        actual_df = actual_df.drop(["knowledge_timestamp"], axis=1)
You should rather mock setting the knowledge timestamp otherwise you are not testing full behavior.

2023-08-30 08:52 UTC, jsmerix commented on im_v2/common/data/extract/test/test_extract_utils.py
> +            "end_timestamp": "2022-01-01 01:00:00",
Nit picky - we always try to timestamps with timezone wherever possible.

2023-08-30 08:52 UTC, jsmerix commented on im_v2/common/data/extract/test/test_extract_utils.py
> +            "s3_path": f"s3://test/",
This shouldn't be here right - shouldn't the validator function catch this?

2023-08-30 08:52 UTC, jsmerix commented on im_v2/common/data/extract/test/test_extract_utils.py
> +            "action_tag": "downloaded_1sec",
Nit picky since this is just a test but ohlcv data are `downloaded_1min`

2023-08-30 08:52 UTC, jsmerix commented on im_v2/common/data/extract/test/test_extract_utils.py
> +            "universe_part": 1,
When you replace for CcxtExtractor these will no longer be present.

2023-08-30 08:52 UTC, jsmerix commented on im_v2/common/data/extract/test/test_extract_utils.py
> +            'csv_test/2021-12-31 23:00:00_2022-01-01 01:00:00.csv'
It is better to use variables instead of hardcoding the timestamps in the string - you set fixed variables at the top of the test and then use them across the test, this way you can generalize to multiple test cases easily.

2023-08-30 22:52 UTC, Sameep2808 commented
@jsmerix I made one change in each of these files as assert test were failing due to addition of new argument I hope that's fine.
Files: `im_v2/ccxt/data/extract/test/test_ccxt_download_bulk.py` `im_v2/ccxt/data/extract/test/test_download_exchange_data_to_db_exchange.py`
`im_v2/crypto_chassis/data/extract/test/test_chassis_download_bulk.py`

2023-08-30 23:11 UTC, Sameep2808 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +            "s3_path": f"s3://test/",
@jsmerix Yes the validator function would have caught this but the test is written in `im_v2/common/data/extract/test/test_extract_utils.py` to test changes to` process_downloaded_historical_data() `and `download_historical_data()` functions.

While the validator function is called in `im_v2/common/data/extract/download_bulk.py` just before `download_historical_data()` [here](https://github.com/sorrentum/sorrentum/pull/562/files#:~:text=imvcdqviar.validate_dst_dir_arg(args)) and the testcases for running main from `download_bulk.py` are in `im_v2/ccxt/data/extract/test/test_ccxt_download_bulk.py` and `im_v2/ccxt/data/extract/test/test_download_exchange_data_to_db_exchange.py` hence didn't cover.
But do let me know if you want me to cover this as well will do.

2023-08-31 15:58 UTC, jsmerix commented on im_v2/common/data/extract/extract_utils.py
> +            hdbg.dfatal(f"Unsupported `{args['data_format']}` format!")
Yeah, why not.

2023-08-31 16:01 UTC, jsmerix commented
> hence didn't cover.
But do let me know if you want me to cover this as well will do.

@Sameep2808 let't test `_main` of `download_bulk` as well, no problem reusing test case with the same params, just applying it to the entire flow, therefore we end up with a test case which is as close to the actual script call as possible. Then we will go to final review and merge.

2023-08-31 17:18 UTC, Sameep2808 reviewed
@jsmerix I have made the required changes. Can you check and lmk if any other changes are needed?

2023-08-31 17:41 UTC, jsmerix requested changes
Final nits, @Sameep2808 let's also confirm that the script call now woks (with `binanceus` arg for you)

2023-08-31 17:41 UTC, jsmerix commented on im_v2/common/data/extract/test/test_extract_utils.py
> +            return_value=get_simple_crypto_chassis_mock_data(
A nit since this is a test but in order to avoid confusion let's generate ccxt style data and not use `get_simple_crypto_chassis_mock_data` since in reality you would not mix these two.

2023-08-31 17:41 UTC, jsmerix commented on im_v2/common/data/extract/test/test_extract_utils.py
> +            return_value=get_simple_crypto_chassis_mock_data(
Same as above.

2023-08-31 18:04 UTC, Sameep2808 reviewed
@jsmerix I made the required changes.

Regarding the script call Im still facing the same error even after using `binanceus`

Error message (Terminal):
```
INFO: > cmd='im_v2/common/data/extract/download_bulk.py --end_timestamp 2022-08-08T00:00:00+00:00 --start_timestamp 2022-08-01T00:00:00+00:00 --exchange_id binanceus --universe v3 --data_type ohlcv --vendor ccxt --contract_type futures --s3_path s3://cryptokaizen-data-test --download_mode bulk --downloading_entity manual --action_tag downloaded_1min --data_format csv --dst_dir tmp'
INFO: Saving log to file '/app/im_v2/common/data/extract/download_bulk.py.log'
13:55:01 - INFO  dataset_schema_utils.py _get_dataset_schema_file_path:38 Loading dataset schema file: /app/data_schema/dataset_schema_versions/dataset_schema_v3.json
13:55:01 - INFO  dataset_schema_utils.py get_dataset_schema:73          Loaded dataset schema version v3
13:55:01 - INFO  extractor.py __init__:40                               CCXT version: 2.1.80
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 620, in fetch
    response.raise_for_status()
  File "/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 451 Client Error:  for url: https://fapi.binance.com/fapi/v1/exchangeInfo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "im_v2/common/data/extract/download_bulk.py", line 107, in <module>
    _main(_parse())
  File "im_v2/common/data/extract/download_bulk.py", line 103, in _main
    _run(args)
  File "im_v2/common/data/extract/download_bulk.py", line 84, in _run
    exchange = imvcdexex.CcxtExtractor(
  File "/app/im_v2/ccxt/data/extract/extractor.py", line 55, in __init__
    self.currency_pairs = self.get_exchange_currency_pairs()
  File "/app/im_v2/ccxt/data/extract/extractor.py", line 110, in get_exchange_currency_pairs
    return list(self._sync_exchange.load_markets().keys())
  File "/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1431, in load_markets
    markets = self.fetch_markets(params)
  File "/venv/lib/python3.8/site-packages/ccxt/binance.py", line 1468, in fetch_markets
    response = getattr(self, method)(query)
  File "/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/venv/lib/python3.8/site-packages/ccxt/binance.py", line 5583, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2625, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 639, in fetch
    raise ExchangeError(details) from e
ccxt.base.errors.ExchangeError: binanceus GET https://fapi.binance.com/fapi/v1/exchangeInfo
```

Error Message (link:  https://fapi.binance.com/fapi/v1/exchangeInfo)
```
code	0
msg	"Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
```

2023-09-13 03:19 UTC, Sameep2808 reviewed
Master merged into the branch

2023-09-13 06:50 UTC, jsmerix approved these changes

2023-09-13 06:50 UTC, merged