Use str_to_timestamp() instead of timestamp_as_str_to_timestamp()
sorrentum/sorrentum pull request #585
Opened 2023-10-11 17:06 UTC by jainamp14

#584 
- Replaced timestamp_as_str_to_timestamp() with str_to_timestamp()

2023-10-11 17:31 UTC, rheenina requested changes
High-level comments, will do another iteration after they're fixed

2023-10-11 17:31 UTC, rheenina commented on dev_scripts/use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh
> +#!/bin/bash -xe
Rename the file and place it under `dev_scripts/cleanup_scripts` as mentioned here https://github.com/sorrentum/sorrentum/issues/584#issuecomment-1756021573

2023-10-11 17:31 UTC, rheenina commented on oms/reconciliation.py
> +def str_to_timestamp(
this name should be changed

2023-10-11 17:31 UTC, rheenina commented on oms/reconciliation.py
> +def str_to_timestamp(
let's take a look at examples of using script (my bad not to give links but docs in the script is good enough IMO).

Here's a good example of how script can be used: https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/cleanup_scripts/CMTask3514_rename_predictions.20230124.sh

Since we cannot exclude this file, we need to use regex of what to replace.

2023-10-11 17:31 UTC, rheenina commented on oms/reconciliation.py
> +            if str_to_timestamp(system_run_start_timestamp, tz=tz)
`str_to_timestamp` is located in `hdatetime.py` and not in this file (renaming doesn't count, it's the wrong move). Is this code going to fail in this case, wdyt?

2023-10-11 17:31 UTC, rheenina commented on dataflow_amp/system/Cx/Cx_dump_market_data.py
> +    start_timestamp = oms.str_to_timestamp(start_timestamp_as_str)
you take function from another file -- import also changes

2023-10-11 18:41 UTC, jainamp14 commented
> High-level comments, will do another iteration after they're fixed

I am sorry but I am confused can you please explain what I need to do again for the 3 conversations I have left to resolve? Because I have already changed their names from timestamp_as_str_to_timestamp to str_to_timestamp so what is it that I did wrong or needs to be adjusted?

2023-10-12 04:03 UTC, rheenina commented on oms/reconciliation.py
> +def str_to_timestamp(
> this name should be changed

Sorry, here's a typo --> should not be changed

2023-10-12 04:26 UTC, rheenina commented
> I am sorry but I am confused can you please explain what I need to do again for the 3 conversations I have left to resolve? Because I have already changed their names from `timestamp_as_str_to_timestamp` to `str_to_timestamp` so what is it that I did wrong or needs to be adjusted?

https://github.com/sorrentum/sorrentum/issues/584#issuecomment-1758890258

2023-10-12 17:15 UTC, rheenina reviewed
GJ! See some suggestions

2023-10-12 17:15 UTC, rheenina commented on dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh
> +
add `dir_names="amp/dev_scripts/cleanup_scripts dev_scripts/cleanup_scripts"`

2023-10-12 17:20 UTC, rheenina commented on oms/notebooks/Master_multiday_system_reconciliation.py
>  #       extension: .py
did you run notebook? If so, revert changes because notebook full of errors in the output, then apply these changes but do not re-run notebook. Just save.

to revert file to its previous state, use:
```
git checkout master oms/notebooks/Master_multiday_system_reconciliation.py
```
```
git checkout master oms/notebooks/Master_multiday_system_reconciliation.ipynb
```

2023-10-13 12:36 UTC, rheenina requested changes

2023-10-13 12:36 UTC, rheenina commented on dataflow_amp/system/Cx/Cx_dump_market_data.py
> +
linter messed up, could pls place backticks back

2023-10-13 12:36 UTC, rheenina commented on dataflow_amp/system/Cx/Cx_dump_market_data.py
> +        start_timestamp_as_str, tz="America/New_York"
`tz` is a positional argument in `hdateti.str_to_timestamp()`, that means it should be pass as:
```
start_timestamp = hdateti.str_to_timestamp(
        start_timestamp, tz
    )
```
define tz above `start_timestamp` and pass to both.

2023-10-13 12:36 UTC, rheenina commented on dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh
> +  --exclude_dirs "dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh"
not fully addressed ->  ` --exclude_dirs "$dir_names"`

2023-10-13 12:36 UTC, rheenina commented on dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh
> +  --exclude_dirs "dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh"
check everywhere below

2023-10-13 12:36 UTC, rheenina commented on oms/notebooks/Master_multiday_system_reconciliation.py
> +        start_timestamp_as_str, tz = "America/New_York"
`tz` is a positional argument in `hdateti.str_to_timestamp()`, that means it should be pass as:
```
start_timestamp = hdateti.str_to_timestamp(
        start_timestamp, tz
    )
```
define tz above `start_timestamp` and pass to both.

2023-10-13 12:36 UTC, rheenina commented on oms/notebooks/Master_multiday_system_reconciliation.py
> +        start_timestamp_as_str, tz = "America/New_York"
don't forget to save notebook after these changes

2023-10-13 12:36 UTC, rheenina commented on oms/reconciliation.py
> +        start_timestamp_as_str, tz="America/New_York"
`tz` is a positional argument in `hdateti.str_to_timestamp()`, that means it should be pass as:
```
start_timestamp = hdateti.str_to_timestamp(
        start_timestamp, tz
    )
```
define tz above `start_timestamp` and pass to both.

2023-10-13 12:36 UTC, rheenina commented on oms/reconciliation.py
> +            if hdateti.str_to_timestamp(system_run_start_timestamp, tz=tz)
tz is a positional argument for this function

2023-10-13 12:36 UTC, rheenina commented on oms/reconciliation.py
> +            if hdateti.str_to_timestamp(system_run_start_timestamp, tz=tz)
same as above

2023-10-13 12:36 UTC, rheenina commented on dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh
> +#!/bin/bash -xe
does the script work as expected?

2023-10-13 15:40 UTC, jainamp14 commented on oms/reconciliation.py
> +            if hdateti.str_to_timestamp(system_run_start_timestamp, tz=tz)
Just want to make sure this should not be changed right as you mentioned in one of the previous conversation.

2023-10-13 16:24 UTC, rheenina commented on oms/reconciliation.py
> +            if hdateti.str_to_timestamp(system_run_start_timestamp, tz=tz)
it should be `hdateti.str_to_timestamp(system_run_start_timestamp, tz)`

2023-10-13 16:25 UTC, rheenina commented on oms/reconciliation.py
> +            if hdateti.str_to_timestamp(system_run_start_timestamp, tz=tz)
we do not change only `def timestamp_as_str_to_timestamp(...)`, i.e. line where func is defined

2023-10-13 16:49 UTC, rheenina requested changes
Do not forget to run linter before each review for every newly changed file.

2023-10-13 16:49 UTC, rheenina commented on dataflow_amp/system/Cx/Cx_dump_market_data.py
> +    # Defined tz to pass time zone into function.
Good call to add a comment but IMO we don't need it here because it is crystal clear what we do here and there's no any other explanation why we do this; or there's no too much code to separate it with a simple comment. So remove.

2023-10-13 16:49 UTC, rheenina commented on dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh
> +#!/bin/bash -xe
we need to check script by running it

2023-10-13 16:49 UTC, rheenina commented on dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh
> +
remove one empty line

2023-10-13 16:49 UTC, rheenina commented on oms/notebooks/Master_multiday_system_reconciliation.py
> +    # Defined tz to pass time zone into function.
remove the comment

2023-10-13 16:49 UTC, rheenina commented on oms/notebooks/Master_multiday_system_reconciliation.py
> +        start_timestamp_as_str, tz)
run linter for this file + save notebook

2023-10-13 16:49 UTC, rheenina commented on oms/reconciliation.py
> +        start_timestamp_as_str, tz)
run linter

2023-10-13 16:49 UTC, rheenina commented on oms/reconciliation.py
> +    # Defined tz to pass time zone into function.
remove

2023-10-13 16:49 UTC, rheenina commented on oms/reconciliation.py
> +            if hdateti.str_to_timestamp(system_run_start_timestamp, tz=tz)
> tz is a positional argument for this function

do not addressed, fix

2023-10-13 16:49 UTC, rheenina commented on oms/reconciliation.py
> +            if hdateti.str_to_timestamp(system_run_start_timestamp, tz=tz)
above tz is defined as UTC therefore we do not need to re-assign it, just make it positional in the function call

2023-10-13 16:49 UTC, rheenina commented on oms/reconciliation.py
> +            if hdateti.str_to_timestamp(system_run_start_timestamp, tz=tz)
not addressed see https://github.com/sorrentum/sorrentum/pull/585/files#r1358200803

2023-10-13 16:49 UTC, rheenina commented on oms/reconciliation.py
> +            if hdateti.str_to_timestamp(system_run_start_timestamp, tz=tz)
same here https://github.com/sorrentum/sorrentum/blob/02ce7a9298805d3094957b5dbe5e5b92bd5da4be/oms/reconciliation.py#L611

2023-10-13 17:08 UTC, rheenina commented
Also rename PR as it mentioned here https://github.com/sorrentum/sorrentum/issues/584#issuecomment-1756021573

2023-10-16 15:59 UTC, jainamp14 commented on dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh
> +#!/bin/bash -xe
It works

2023-10-16 17:45 UTC, rheenina commented on dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh
> +#!/bin/bash -xe
How much time it takes approx?

2023-10-16 18:16 UTC, rheenina commented on dataflow_amp/system/Cx/Cx_dump_market_data.py
> +The script saves market data from the DB to a file. ```
leave backticks for the very last round of review. It's painful always point to them and fix.

2023-10-16 18:23 UTC, jainamp14 commented
> Please, address this one as well [#585 (comment)](https://github.com/sorrentum/sorrentum/pull/585#issuecomment-1761836251) If you don't know how or don't understand lmk

Ohh sorry I didn't see that but yea I am not sure how to rename PR can you please suggest how I can do that once I have already created the PR but from next task, I will make sure name it correct!

2023-10-16 18:25 UTC, jainamp14 commented
The script was running when I ran but once I made changes I haven't ran it because it had already replaced the text and some manually so I wasn't sure how to ensure that it worked for those.

2023-10-16 18:26 UTC, rheenina commented
> > Please, address this one as well [#585 (comment)](https://github.com/sorrentum/sorrentum/pull/585#issuecomment-1761836251) If you don't know how or don't understand lmk
> 
> Ohh sorry I didn't see that but yea I am not sure how to rename PR can you please suggest how I can do that once I have already created the PR but from next task, I will make sure name it correct!

Just click the `edit` button and enter a new name. Issue or PRs can be renamed any time if it's needed.
 
<img width="1258" alt="Снимок экрана 2023-10-16 в 23 24 31" src="https://github.com/sorrentum/sorrentum/assets/68428519/01ac2feb-934d-4c54-b318-92d6d8f35abf">

2023-10-16 18:38 UTC, rheenina commented on dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh
> +#!/bin/bash -xe
as for https://github.com/sorrentum/sorrentum/pull/585#issuecomment-1765054809
1. To test script, create new branch and the script.
2. Check changes using `git diff` or `git diff {file_name}`
3. If changes are not as you expected, then drop all changes being in the root dir and using git:
```
git restore -W .
```
4. Modify the sh-script and go the p.1 until it works.

I suggest, to create a new sh-file and add it to git. It won't be reverted while using cmd above.

2023-10-17 10:27 UTC, gpsaggese commented on oms/reconciliation.py
> +            if hdateti.str_to_timestamp(system_run_start_timestamp, tz)
The TODO at 590 should be removed

2023-10-19 18:25 UTC, rheenina commented on oms/reconciliation.py
> +            if hdateti.str_to_timestamp(system_run_start_timestamp, tz)
@jainamp14 let's address this comment

2023-10-23 17:56 UTC, jainamp14 commented on dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh
> +#!/bin/bash -xe
I checked the script it works and everything got renamed properly! I hope its good from your side :)

2023-10-31 18:48 UTC, shab95 commented
@rheenina 
Pinging as I can't re-request a review from you right now.

I think I fixed the tests you wanted here.  I think the issue was that the hdateti.str_to_timetamp function was called without a datetime format. Please let me know if there are any other issues.

2023-10-31 20:34 UTC, rheenina commented on oms/notebooks/Master_multiday_system_reconciliation.ipynb
> +    "    tz = \"America/New_York\"\n",
@shab95 add also here `datetime_format = "%Y%m%d_%H%M%S"` and I will merge it after

2023-11-02 12:44 UTC, gpsaggese reviewed
LGTM

2023-11-03 15:41 UTC, merged

2023-11-03 15:42 UTC, rheenina commented
@PomazkinG let's integrate this PR into cmamp once we have time