SorrTask542_Make_convert_to_multiindex_public_and_move_to_a_general_lib_2
sorrentum/sorrentum pull request #587
Opened 2023-10-17 16:59 UTC by jainamp14

- #542 
- Converted function from private to public
- Ran the script to update function calls

2023-10-19 18:24 UTC, rheenina requested changes
gj! see some suggestions.

Small but a very useful advice. When you write a unit test, ensure that test checks exactly what a function returns. E.g.: if function converts an index into a multi-index, the test should check if this change was perform successfully by the function.

2023-10-19 18:24 UTC, rheenina commented on dataflow/core/utils.py
> +    del df[asset_id_col]
-> `df.drop(columns=[asset_id_col], axis=1, inplace=True)`

2023-10-19 18:24 UTC, rheenina commented on dataflow/core/utils.py
> +    # Copied from `_load_multiple_instrument_data()`.
no need for this comment

2023-10-19 18:24 UTC, rheenina commented on dataflow/notebooks/gallery_synthetic_data_example.py
> +df = dtfcorutil.convert_to_multiindex(df, "asset_id")
should be accessible through `dtfcore` since `import dataflow.core as dtfcore` imports everything inside `dataflow.core` package. So -> `dtfcore.convert_to_multiindex`

2023-10-19 18:24 UTC, rheenina commented on dataflow/notebooks/gallery_synthetic_data_example.py
> +df = dtfcorutil.convert_to_multiindex(df, "asset_id")
-> dtfcore.convert_to_multiindex

2023-10-19 18:24 UTC, rheenina commented on dataflow/notebooks/tutorial_dataflow.py
> +converted_data = dtfcorutil.convert_to_multiindex(
-> dtfcore.convert_to_multiindex

2023-10-19 18:24 UTC, rheenina commented on dataflow/notebooks/tutorial_dataflow.py
> +converted_data = dtfcorutil.convert_to_multiindex(data_hist, "asset_id")
-> dtfcore.convert_to_multiindex

2023-10-19 18:24 UTC, rheenina commented on dataflow/system/source_nodes.py
> +            self.df = dtfcorutil.convert_to_multiindex(
-> dtfcore.convert_to_multiindex

2023-10-19 18:24 UTC, rheenina commented on dataflow/system/source_nodes.py
> +            df = dtfcorutil.convert_to_multiindex(df, self._asset_id_col)
-> dtfcore.convert_to_multiindex

2023-10-19 18:24 UTC, rheenina commented on research_amp/cc/notebooks/CMTask1704_Get_raw_CC_data.py
> +    converted_resampled_df = dtfcorutil.convert_to_multiindex(
-> dtfcore.convert_to_multiindex

2023-10-19 18:24 UTC, rheenina commented on research_amp/cc/notebooks/CMTask1704_Get_raw_CC_data.py
> +    converted_data = dtfcorutil.convert_to_multiindex(df, "full_symbol")
-> dtfcore.convert_to_multiindex

2023-10-19 18:24 UTC, rheenina commented on dataflow/core/utils.py
> +    Transform a df like: ```
let's slightly modify this:
```
Transform a DataFrame into a multi-indexed one.

:param df: a non-multi-indexed DataFrame
    E.g.:
   \```
                               id close  volume
    end_time
    2022-01-04 09:01:00-05:00  13684    NaN       0
    2022-01-04 09:01:00-05:00  17085    NaN       0
    2022-01-04 09:02:00-05:00  13684    NaN       0
    2022-01-04 09:02:00-05:00  17085    NaN       0
    2022-01-04 09:03:00-05:00  13684    NaN       0
    ```
```
"\\" before backticks is not needed, used to escape

2023-10-19 18:24 UTC, rheenina commented on dataflow/core/utils.py
> +    Return a df like:
and this one:
```
:return: a multi-indexed DataFrame where the `asset_id` column is removed
    E.g.:
    ```
                                    close       volume
                              13684 17085  13684 17085
    end_time
    2022-01-04 09:01:00-05:00   NaN   NaN      0     0
    2022-01-04 09:02:00-05:00   NaN   NaN      0     0
    2022-01-04 09:03:00-05:00   NaN   NaN      0     0
    2022-01-04 09:04:00-05:00   NaN   NaN      0     0
    ```
```

2023-10-19 18:24 UTC, rheenina commented on dataflow/core/utils.py
> +    Note that the `asset_id` column is removed.
remove this one

2023-10-20 14:37 UTC, jainamp14 commented on dataflow/core/test/test_utils.py
> +import numpy as np
`Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/app/dataflow/core/test/test_utils.py", line 69, in test_1
    result_df = dtfcorutil.convert_to_multiindex(df, 'id')
  File "/app/dataflow/core/utils.py", line 377, in convert_to_multiindex
    hpandas.dassert_series_type_is(df[asset_id_col], np.int64)
NameError: name 'np' is not defined

=========================================================================================== slowest 3 durations ============================================================================================

0.01s call     dataflow/core/test/test_utils.py::Test_convert_to_multiindex::test_1
0.00s setup    dataflow/core/test/test_utils.py::Test_convert_to_multiindex::test_1
0.00s teardown dataflow/core/test/test_utils.py::Test_convert_to_multiindex::test_1
========================================================================================= short test summary info ==========================================================================================
FAILED dataflow/core/test/test_utils.py::Test_convert_to_multiindex::test_1 - NameError: name 'np' is not defined`

Yea it wasn't an issue with the test_utis.py file I needed import numpy in the utils.py file which is fixed.

2023-10-20 22:27 UTC, rheenina commented on dataflow/core/test/test_utils.py
> +import numpy as np
Then just remove line `from numpy import *`

2023-10-24 20:38 UTC, DanilYachmenev commented
obsolete

2023-10-24 20:38 UTC, closed without merging