Issue51 create brownie test script for time lock contract
sorrentum/sorrentum pull request #61
Opened 2023-03-17 22:11 UTC by samarth9008

2023-03-22 13:04 UTC, gpsaggese reviewed
Very good first PR. 
1) Pls add me and @tamriq and @DanilYachmenev as reviewers otherwise we don't know that it's ready
2) We will publish tools and conventions to use

2023-03-22 13:04 UTC, gpsaggese commented on defi/tokens/test/test_time_lock.py
> +@pytest.fixture(scope="module")
@tamriq can you run the linter on this code?

Also can you help @samarth9008 get set up with:
- our conventions

I've filed a bug to start publishing our docs and linter.

2023-03-22 13:04 UTC, gpsaggese commented on defi/tokens/test/test_time_lock.py
> +@pytest.fixture(scope="module")
At high level we want to comment each unit test to explain what it does and we always use type hints.

@tamriq can help. Can you point @samarth9008 to an example of unit test that is "perfect" according to our standards and convention?

2023-03-23 08:17 UTC, tamriq commented on defi/tokens/test/test_time_lock.py
> +@pytest.fixture(scope="module")
Sure. I ran linter on this code and committed the result, but for the future, to run linter u need to:
- activate the environment from the root:
```
~/src/sorrentum$ >source dev_scripts/setenv_amp.sh
```
- docker login & pull
```
(amp.client_venv) ~/src/sorrentum$ >i docker_login
(amp.client_venv) ~/src/sorrentum$ >i docker_pull
```
- run linter
```
(amp.client_venv) ~/src/sorrentum$ >i lint --files="defi/tokens/test/test_time_lock.py"
```

2023-03-23 08:38 UTC, tamriq commented on defi/tokens/test/test_time_lock.py
> +@pytest.fixture(scope="module")
Also with brownie tests you don't need to explicitly import contracts and accounts (`from brownie import MockERC20, TokenTimelock, accounts`). And let's don't import reverts and chain but do `brownie.reverts` and `brownie.chain` instead to keep things clear.

2023-03-23 08:48 UTC, tamriq commented on defi/tokens/test/test_time_lock.py
> +@pytest.fixture(scope="module")
Yes, let's use typing https://docs.python.org/3/library/typing.html. 
Also I think this example of test from our codebase can be considered as well documented. https://github.com/sorrentum/sorrentum/blob/master/im_v2/test/test_im_lib_tasks.py

2023-03-24 12:24 UTC, tamriq requested changes

2023-03-24 12:24 UTC, tamriq commented on defi/tokens/contracts/MockERC20.sol
> +    uint256 public max_supply;
Let's use camelCase in solidity files. `maxSupply` in the constructor we can call `_maxSupply` and rename `max_supply` to `maxSupply`

2023-03-24 12:24 UTC, tamriq commented on defi/tokens/test/test_time_lock.py
> +#Deploy the MockERC20 contract
Let's use triple quoted strings instead of comments.
E.g. 
```
def test_addParticipant_requireAmount(time_lock, accounts):
    """
    Check whether the participant amount equals to 0 before being added
    """
```

2023-03-24 16:24 UTC, samarth9008 commented on defi/tokens/contracts/MockERC20.sol
> +    uint256 public max_supply;
Made required changes.

2023-03-24 16:24 UTC, samarth9008 commented on defi/tokens/contracts/MockERC20.sol
> +        require(initialSupply <= MAXIMUM_SUPPLY, "Premint amount is more than maximum supply");
Made required changes

2023-03-24 16:24 UTC, samarth9008 commented on defi/tokens/test/test_time_lock.py
> +#Deploy the MockERC20 contract
Made required changes

2023-03-27 13:43 UTC, tamriq approved these changes
Good job, final fixes and we can merge

2023-03-27 16:14 UTC, samarth9008 commented on defi/tokens/test/test_time_lock.py
> +    Checks the flow of releaseTokens function
Done.

2023-03-28 06:54 UTC, merged

2023-03-28 12:47 UTC, gpsaggese reviewed
Good testing but still a bit of work to get our conventions

@DanilYachmenev can you also pls review just to keep everyone in the loop?

2023-03-28 12:47 UTC, gpsaggese commented on defi/tokens/test/test_time_lock.py
> +def time_lock(mock_token, TokenTimelock, accounts):
@tamriq @samarth9008 any reason why we don't use type hints here?

2023-03-28 12:47 UTC, gpsaggese commented on defi/tokens/test/test_time_lock.py
> +    Checks whether the participant has been added.
-> Check

PEP8 suggests imperative mode

2023-03-28 12:47 UTC, gpsaggese commented on defi/tokens/test/test_time_lock.py
> +    assert (
-> self.assert since assert are not guaranteed to be left at certain optimization levels(asserts are for invariant in the code)

2023-03-28 12:47 UTC, gpsaggese commented on defi/tokens/test/test_time_lock.py
> +
two empty lines

2023-03-28 12:47 UTC, gpsaggese commented on defi/tokens/test/test_time_lock.py
> +
no empty line or maybe a comment