Adding conventions doc for sorrentum contributors
sorrentum/sorrentum pull request #644
Opened 2024-01-29 21:55 UTC by Shaunak01

This convention document is to be followed by Sorrentum contributors. 
 #Updated the conventions doc and linter is run.

FYI @samarth9008 @gpsaggese

2024-01-29 21:56 UTC, samarth9008 commented
Did you run the linter? Bcz running it would generate a Table of content and also format the file which is not done right now

The command to run the linter is

```
i lint --files sorrentum_sandbox/all.data605.conventions.md
```

2024-01-29 22:32 UTC, Shaunak01 commented
Yes I did run the exact command and there were no errors as such. I will go through the output carefully to see what might have happened while linter ran.

2024-01-31 21:54 UTC, samarth9008 requested changes
Highly recommend to read the code of other small md files. Look how the text are arranged. How the sections are formed. How everything is written in a bullet points which also enhances the readability for the reader.

2024-01-31 21:54 UTC, samarth9008 commented on sorrentum_sandbox/all.data605.conventions.md
> +## Convention Sections
Can remove this heading

2024-01-31 21:54 UTC, samarth9008 commented on sorrentum_sandbox/all.data605.conventions.md
> +### 1. Building the Coding Environment
Make this heading start with 2 hashes as we removed the previous one. Similarly adjust below everywhere.
`### 1. Building the Coding Environment` -> `## 1. Building the Coding Environment`

2024-01-31 21:54 UTC, samarth9008 commented on sorrentum_sandbox/all.data605.conventions.md
> +    To clone the repo, use the cloning command described in the Github official documentation
Make them a bullet points. Not sure why they are in box. Probably bcz you are using 4 hashes but as per the previous modification it will convert to 3 hashes. We never go to four hashes. Its better to convert it to a bullets point insted

```
- All the source code should go under ~/src (e.g., /Users/<YOUR_USER>/src on a Mac PC)
- The path to the local repo folder should look like this ~/src/{REPO_NAME}{IDX} where
    IDX is an integer
    REPO_NAME is a name of the repository
    To clone the repo, use the cloning command described in the Github official documentation
```

2024-01-31 21:54 UTC, samarth9008 commented on sorrentum_sandbox/all.data605.conventions.md
> +##### Sometimes it does not work.
Do not use these many hashes. Refer to the code of other docs to understand how we write the md file.

2024-01-31 21:54 UTC, samarth9008 commented on sorrentum_sandbox/all.data605.conventions.md
> +    ```
Even this is appearing in some kind of box which it is not supposed to

2024-01-31 21:54 UTC, samarth9008 commented on sorrentum_sandbox/all.data605.conventions.md
> +    ```
Same here box problem

2024-01-31 21:54 UTC, samarth9008 commented on sorrentum_sandbox/all.data605.conventions.md
> +
Again a box problem

2024-01-31 21:54 UTC, samarth9008 commented on sorrentum_sandbox/all.data605.conventions.md
> +#### Linter
Make a new section over here like `3. Linter` and adjust accordingly

2024-01-31 21:54 UTC, samarth9008 commented on sorrentum_sandbox/all.data605.conventions.md
> +being reviewed, the PR will be merged to the master branch by your reviewers
It should be a separate bullet points on a new line.

2024-02-01 14:19 UTC, samarth9008 approved these changes
Much better now. Good work!

2024-02-01 14:20 UTC, merged