SorrTask687 Improve all.development_documents.reference.md
sorrentum/sorrentum pull request #698
Opened 2024-02-27 04:21 UTC by nehalR777

@samarth9008 @gpsaggese , I have Fixed broken links in the documentation and added the codebase clean-up doc. I have also removed the references to dataflow , datapull and HTMLcov as requested here https://github.com/sorrentum/sorrentum/issues/687#issuecomment-1965681912

2024-02-27 04:32 UTC, nehalR777 commented
@gpsaggese sir , awaiting your review and approval on this. 
cc: @samarth9008 @sonaalKant

2024-02-28 14:48 UTC, samarth9008 requested changes
Good work! Small change.

2024-02-28 14:48 UTC, samarth9008 commented on docs/onboarding/all.development_documents.reference.md
> +- HTMLcov server
Lets delete if no link is there. Same for datapull and dataflow

2024-02-28 17:22 UTC, nehalR777 commented on docs/onboarding/all.development_documents.reference.md
> +- HTMLcov server
@samarth9008 , the changes have been made.

2024-02-28 18:01 UTC, nehalR777 commented
@samarth9008 , the changes have been made as requested , please review

2024-02-28 18:40 UTC, merged