SorrTask694_unit_test_get_service_resource
sorrentum/sorrentum pull request #700
Opened 2024-02-28 15:58 UTC by tkpratardan

Task #694 
@samarth9008 @sonaalKant 

Created a unit test to check the s3 service. 

Review request:
1. Am I headed in the right direction here?
2. Should I add more unit tests to check other services? If yes, could you mention what all services?

cc : @gpsaggese

2024-02-29 05:43 UTC, sonaalKant requested changes
Overall good job. Few things to take care for future:
- Run linter. (It will warn you with most of the nits I mentioned)
- Refer documentations for conventions that we follow.

2024-02-29 05:43 UTC, sonaalKant commented on helpers/test/test_haws.py
> +class test_get_service_resource(hunitest.TestCase):
-> `Test_get_service_resource`
refer https://github.com/sorrentum/sorrentum/blob/e841aaa34c71b200f5405e7257cc108a57086fd8/docs/coding/all.write_unit_tests.how_to_guide.md#conventions

2024-02-29 05:43 UTC, sonaalKant commented on helpers/test/test_haws.py
> +       #Creating a mock s3 bucket.
Nits. Indent correctly.

2024-02-29 05:43 UTC, sonaalKant commented on helpers/test/test_haws.py
> +
Remove blank spaces. Always run linter before pushing code, `i lint -f "fillename"`

2024-02-29 05:43 UTC, sonaalKant commented on helpers/test/test_haws.py
> +    def test_s3_resource(self):
Nits
-> `test1(self) -> None`

2024-02-29 05:43 UTC, sonaalKant commented on helpers/test/test_haws.py
> +    def aws_credentials(self):
Nits
-> `aws_credentials(self) -> None`

2024-02-29 22:51 UTC, tkpratardan commented
@sonaalKant 

Thank you for your review. I apologize for the issues. Will make sure to keep my code consistent with the conventions and formatting further on.

for now, I have made the required changes, and made the commit after running the file with linter. Could you please review it? Also please let me know if I have to add any more tests.

2024-03-01 15:37 UTC, samarth9008 requested changes
Good improvements. Few changes from my side.

2024-03-01 15:37 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        Test that haws.get_service_resource() correctly retrieves an S3
haws.get_service_resource() -> `haws.get_service_resource()`. 

Surrounded by backticks.

Also no `an` before s3

2024-03-01 15:37 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Creating a mock s3 bucket.
-> # Create mock `s3` bucket.

2024-03-01 15:37 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        buckets = list(s3_resource.buckets.all())
Add comment above line 38

```
# Get all `s3` buckets.
```

2024-03-01 15:37 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        self.assertIn("my-test-bucket", bucket_names)
Lets use our internal function for asserting

```
import helpers.hdbg as hdbg #import at the top
hdbg.dassert_in("my-test-bucket", bucket_names)
```

2024-03-01 15:37 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Assert
-> `# Check.`

2024-03-01 15:37 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        Mocked AWS Credentials for moto.
Credentials  -> credentials

2024-03-01 15:38 UTC, samarth9008 commented
Pls resolve the conversation if they are addressed

2024-03-02 02:45 UTC, tkpratardan commented
@samarth9008 
Thank you for pointing out the inconsistencies. I have made the changes, please verify.

2024-03-03 05:42 UTC, sonaalKant commented
LGTM.

2024-03-03 05:43 UTC, sonaalKant approved these changes

2024-03-04 00:55 UTC, samarth9008 reviewed
A question and LGTM

2024-03-04 00:55 UTC, samarth9008 commented on helpers/test/test_haws.py
> +_LOG = logging.getLogger(__name__)
Do we need it?

2024-03-04 01:36 UTC, tkpratardan commented on helpers/test/test_haws.py
> +_LOG = logging.getLogger(__name__)
Actually, no. I just followed the helpers/unit_test_skeleton.py. Should I remove it?

2024-03-04 01:39 UTC, samarth9008 commented on helpers/test/test_haws.py
> +_LOG = logging.getLogger(__name__)
If `_LOG` not used anywhere in the code and then lets remove it.

2024-03-04 23:52 UTC, tkpratardan commented on helpers/test/test_haws.py
> +_LOG = logging.getLogger(__name__)
Done, please check and verify.

2024-03-08 17:06 UTC, gpsaggese reviewed
LGTM

2024-03-08 17:06 UTC, merged