Added unit test case for update task definition
sorrentum/sorrentum pull request #709
Opened 2024-03-02 18:49 UTC by nehalR777

@samarth9008 @sonaalKant have written a unit test as per my assigned task here https://github.com/sorrentum/sorrentum/issues/697

2024-03-03 05:31 UTC, sonaalKant requested changes
Well done! Some nits to work on. Also, don't forget to run linter. `i lint -f <filename>`

2024-03-03 05:31 UTC, sonaalKant commented on helpers/test/test_haws.py
> +
Remove empty lines.

2024-03-03 05:31 UTC, sonaalKant commented on helpers/test/test_haws.py
> +        # Create a mock task definition
Nit : Add `.` after every comment.

2024-03-03 05:31 UTC, sonaalKant commented on helpers/test/test_haws.py
> +from unittest.mock import patch
import directly eg. `import unittest.mock as umock` then `umock.patch .. `

2024-03-03 05:34 UTC, nehalR777 commented
@sonaalKant , thanks for the quick review , will make the necessary changes and update you accordingly

2024-03-03 05:44 UTC, nehalR777 commented on helpers/test/test_haws.py
> +
@sonaalKant this has been addressed

2024-03-03 05:45 UTC, nehalR777 commented on helpers/test/test_haws.py
> +        # Create a mock task definition
@sonaalKant , this has been addressed as well

2024-03-03 05:57 UTC, nehalR777 commented on helpers/test/test_haws.py
> +from unittest.mock import patch
@sonaalKant , this has been taken care of

2024-03-03 08:46 UTC, sonaalKant commented on helpers/test/test_haws.py
> +
Remove all the empty lines from the function.

2024-03-03 15:41 UTC, nehalR777 commented on helpers/test/test_haws.py
> +
@sonaalKant resolved

2024-03-04 01:07 UTC, samarth9008 requested changes
Good work! Small nits.

2024-03-04 01:07 UTC, samarth9008 commented on helpers/test/test_haws.py
> +_LOG = logging.getLogger(__name__)
Do we need this?

2024-03-04 01:07 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        Mocked AWS Credentials for moto.
Credentials  -> credentials

2024-03-04 01:07 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        self.assertEqual(updated_image_url, new_image_url)
Lets use our internal function

```
import helpers.hdbg as hdbg # import at top
hdbg.dassert_eq(updated_image_url, new_image_url)
```

2024-03-04 01:22 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Mock the return value of get_ecs_client.
get_ecs_client -> `get_ecs_client`

2024-03-04 01:27 UTC, nehalR777 commented on helpers/test/test_haws.py
> +        Mocked AWS Credentials for moto.
@samarth9008 , this has been addressed

2024-03-04 01:28 UTC, nehalR777 commented on helpers/test/test_haws.py
> +        # Mock the return value of get_ecs_client.
@samarth9008 , done

2024-03-04 01:36 UTC, nehalR777 commented on helpers/test/test_haws.py
> +        self.assertEqual(updated_image_url, new_image_url)
@samarth9008 , done

2024-03-04 02:00 UTC, nehalR777 commented on helpers/test/test_haws.py
> +_LOG = logging.getLogger(__name__)
@samarth9008 fixed

2024-03-04 02:49 UTC, samarth9008 commented on helpers/test/test_haws.py
> +import logging
If logging is removed, then this import is not required. Right? Running the linter would have removed it.

2024-03-04 02:56 UTC, nehalR777 commented on helpers/test/test_haws.py
> +import logging
@samarth9008 , that's right! I'll make sure to use linter henceforth . This should be resolved now

2024-03-04 23:38 UTC, gpsaggese reviewed
Going in the right direction

2024-03-04 23:38 UTC, gpsaggese commented on helpers/test/test_haws.py
> +    def test1(self, mock_get_ecs_client) -> None:
type hint

2024-03-04 23:38 UTC, gpsaggese commented on helpers/test/test_haws.py
> +        # Mock data.
let's add a docstring explaining what we are testing in each test.

If not clear from the docs, pls update ./docs/coding/all.write_unit_tests.how_to_guide.md (in a different PR)

2024-03-05 02:16 UTC, nehalR777 commented on helpers/test/test_haws.py
> +    def test1(self, mock_get_ecs_client) -> None:
@gpsaggese sir , this has been added.

2024-03-05 03:22 UTC, gpsaggese commented on helpers/test/test_haws.py
> +        task_definition_name: str = "my-task-definition"
Those are automatically inferred by Python, so need for them.

If you run the linter it will tell you which are the missing type hints.

Can you pls read ./docs/coding/all.type_hints.how_to_guide.md and improve it if something is not clear?
You can do it in a different PR

2024-03-05 18:08 UTC, nehalR777 commented on helpers/test/test_haws.py
> +        task_definition_name: str = "my-task-definition"
@gpsaggese , sir this has been resolved . I will take a look at the documentation and make changes accordingly in a new PR.

2024-03-09 16:58 UTC, gpsaggese commented
Can you resolve the conflict so we can merge?

2024-03-09 18:37 UTC, samarth9008 requested changes
TODO(Samarth): Don't merge before creating a PR on cmamp and testing it over there also

2024-03-10 00:36 UTC, nehalR777 commented
@samarth9008 @gpsaggese I’ve resolved the merging conflicts , please do verify.

2024-03-11 12:12 UTC, merged