SorrTask696_unit_test_get_task_definition_image_url
sorrentum/sorrentum pull request #711
Opened 2024-03-03 22:27 UTC by 11swathi

I have written a unit test for get_task_definition_image_url, as per the task #696. Could you please review it and let me know if any changes required? @samarth9008

2024-03-04 01:29 UTC, samarth9008 requested changes
Run the linter before pushing the code

```
i lint --files "file1 file2..."
```

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +import tempfile
Why this import?

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +_LOG = logging.getLogger(__name__)
Do we need this?

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +from unittest.mock import patch
import directly eg. `import unittest.mock as umock` then `umock.patch .. `

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        Mocked AWS Credentials for moto.
Credentials  -> credentials

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        Test that get_task_definition_image_url retrieves correct image URL.
get_task_definition_image_url  -> `get_task_definition_image_url `

surrounded by backticks.

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Mock data
Add . after every comments.

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        old_image_url = "old_image_url"
Why do you want to name the variable as `old_image_url`? Is it going to be updated with `new_image_url` in the code? Looks confusing.

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +
No empty line in the code. Check everywhere.

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Mock the return value of get_service_client
get_ecs_client -> `get_ecs_client`

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Calling the function
No need for this comment as its readable in the code itself. Comments are for why the code is doing this work, instead of what it is doing.

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Assert
-> `# Check.`

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        assert image_url == old_image_url
Lets use our internal function

```
import helpers.hdbg as hdbg # import at top
hdbg.dassert_eq(image_url , old_image_url)
```

2024-03-04 01:29 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Create a mock task definition~
no `~` at the end of the comment.

2024-03-04 18:54 UTC, 11swathi commented
I ran the linter using this command `i lint --files "test_haws.py"` and got the below error.

```
(amp.client_venv) Swathis-MacBook-Pro:test swathibaskaran$ i lint --files "test_haws.py"
INFO: > cmd='/Users/swathibaskaran/src/venv/amp.client_venv/bin/invoke lint --files test_haws.py'
Traceback (most recent call last):
  File "/Users/swathibaskaran/src/venv/amp.client_venv/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/Users/swathibaskaran/src/venv/amp.client_venv/lib/python3.9/site-packages/invoke/program.py", line 398, in run
    self.execute()
  File "/Users/swathibaskaran/src/venv/amp.client_venv/lib/python3.9/site-packages/invoke/program.py", line 583, in execute
    executor.execute(*self.tasks)
  File "/Users/swathibaskaran/src/venv/amp.client_venv/lib/python3.9/site-packages/invoke/executor.py", line 140, in execute
    result = call.task(*args, **call.kwargs)
  File "/Users/swathibaskaran/src/venv/amp.client_venv/lib/python3.9/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/swathibaskaran/src/sorrentum1/helpers/lib_tasks_lint.py", line 280, in lint
    hlitauti.report_task()
  File "/Users/swathibaskaran/src/sorrentum1/helpers/lib_tasks_utils.py", line 117, in report_task
    hversio.check_version(container_dir_name)
  File "/Users/swathibaskaran/src/sorrentum1/helpers/hversion.py", line 52, in check_version
    code_version = get_changelog_version(container_dir_name)
  File "/Users/swathibaskaran/src/sorrentum1/helpers/hversion.py", line 135, in get_changelog_version
    hdbg.dassert_file_exists(changelog_file)
  File "/Users/swathibaskaran/src/sorrentum1/helpers/hdbg.py", line 785, in dassert_file_exists
    _dfatal(txt, msg, *args, only_warning=only_warning)
  File "/Users/swathibaskaran/src/sorrentum1/helpers/hdbg.py", line 142, in _dfatal
    dfatal(dfatal_txt)
  File "/Users/swathibaskaran/src/sorrentum1/helpers/hdbg.py", line 71, in dfatal
    raise assertion_type(ret)
AssertionError: 
################################################################################
* Failed assertion *
File '/Users/swathibaskaran/src/sorrentum1/helpers/test/changelog.txt' doesn't exist
################################################################################
```
Am I making any mistake? I couldn't figure out why. Do I have to add this file changelog.txt to the location?

2024-03-04 23:41 UTC, gpsaggese reviewed
Thorough review @samarth9008 

@11swathi pls update the ./docs/coding/all.write_unit_tests.how_to_guide.md with the stuff that wasn't clear (or re-read to internalize the doc and enjoy the gift from that fountain of wisdom)

Also pls run the linter to clean up the code

2024-03-05 14:53 UTC, samarth9008 commented
Can you try running from the root of the repo with full path to the file?

2024-03-05 16:05 UTC, gpsaggese commented on helpers/test/test_haws.py
> +    def test1(self, mock_get_service_client) -> None:
The interface needs the type hint.

2024-03-05 16:36 UTC, 11swathi commented on helpers/test/test_haws.py
> +    def test1(self, mock_get_service_client) -> None:
Updated type hint.

2024-03-06 14:34 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        task_definition_name: str = "my-task-definition"
@11swathi The simple rule, function parameters will require type hints so the reader and linter will understand what type of input we are providing. However when defining variables inside or outside the function do not require type hints as we can infer it implicitly

So `task_definition_name: str = "my-task-definition"` -> `task_definition_name = "my-task-definition"`

2024-03-07 14:52 UTC, 11swathi commented on helpers/test/test_haws.py
> +        task_definition_name: str = "my-task-definition"
Understood Professor @gpsaggese and @samarth9008, 

I need to use type hints at places when the linter can't automatically infer the type. In this case `def test1(self, mock_get_service_client: umock.Mock) -> None:` .  I don't have to use type hints for variables as it is already clear while defining them. 

Will make sure to check and use them correctly going forward. Thanks !

2024-03-08 18:38 UTC, gpsaggese commented on helpers/test/test_haws.py
> +        hdbg.dassert_eq(image_url, mock_image_url)
This should be a self.assertEqual and not dassert_*

- `dassert_*` is for testing invariants in code (including unit tests)
- `self.assert*` should be used only in unit tests to check the outcome of a test

Can you pls file a bug and add this to docs/coding/all.write_unit_tests.how_to_guide.md if it's not there? The section should be called `dassert_* vs self.assert_*`

2024-03-08 18:38 UTC, gpsaggese commented
Also now you need to merge the code in master

2024-03-08 18:40 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        hdbg.dassert_eq(image_url, mock_image_url)
My bad, I told them to change it

2024-03-08 18:50 UTC, gpsaggese commented on helpers/test/test_haws.py
> +        hdbg.dassert_eq(image_url, mock_image_url)
Np. Let's clarify/explain in the doc.

2024-03-09 18:36 UTC, samarth9008 requested changes
TODO(Samarth): Don't merge before creating a PR on cmamp and testing it over there also

2024-03-10 15:22 UTC, 11swathi commented
I have merged the code from master and resolved the conflicts. Could you please review and merge? @samarth9008 @sonaalKant

2024-03-11 12:16 UTC, gpsaggese commented
Can you merge with master?

2024-03-11 12:17 UTC, gpsaggese commented
> TODO(Samarth): Don't merge before creating a PR on cmamp and testing it over there also

The best approach is to merge in Sorrentum and then test in the integration of the PR or of the entire tree.
I don't think students can do the last 1% of getting things working in cmamp.

2024-03-11 12:39 UTC, merged