Fixing the warm-up issue 542
sorrentum/sorrentum pull request #712
Opened 2024-03-04 05:28 UTC by Jd8111997

Issue #542 

This is the command that I used to run linter on the primary files that I modified : 
```bash
i lint --files "dataflow/core/utils.py dataflow/core/test/test_utils.py dev_scripts/cleanup_scripts/SorrTask542_convert_to_multiindex.sh"
```
It's is only failing for amp_pylint on dataflow/core/utils.py file and it's failing on the code that were preexisting before and I haven't modified anything in that file except making the existing function public.
This is the output of linter for failing case:
```bash
amp_processjupytext......................................................Passed
amp_check_filename.......................................................Passed
amp_warn_incorrectly_formatted_todo......................................Passed
amp_flake8...............................................................Passed
amp_pylint...............................................................Failed
- hook id: amp_pylint
- exit code: 5

One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
INFO: > cmd='/app/linters/amp_pylint.py dataflow/core/utils.py dataflow/core/test/test_utils.py'
************* Module dataflow.core.utils
dataflow/core/utils.py:228: [R1704(redefined-argument-from-local), convert_to_multiindex] Redefining argument with the local name 'df'
dataflow/core/utils.py:277: [C0209(consider-using-f-string), convert_to_list] Formatting a regular string which could be a f-string
dataflow/core/utils.py:304: [C3001(unnecessary-lambda-assignment), get_forward_cols.<lambda>] Lambda expression assigned to a variable. Define a function using the "def" keyword instead.
dataflow/core/utils.py:304: [C0209(consider-using-f-string), get_forward_cols.<lambda>] Formatting a regular string which could be a f-string

amp_mypy.................................................................Failed
- hook id: amp_mypy
- exit code: 3

One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
INFO: > cmd='/app/linters/amp_mypy.py dataflow/core/utils.py dataflow/core/test/test_utils.py'
dataflow/core/utils.py:223: error: Need type annotation for 'dfs' (hint: "dfs: Dict[<type>, <type>] = ...")  [var-annotated]
dataflow/core/utils.py:399: error: Value of type "Optional[Match[str]]" is not indexable  [index]
dataflow/core/utils.py:403: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]

1
00:12:15 - INFO  lib_tasks_lint.py lint:409                             Parsing 'linter_output.txt'
00:12:15 - INFO  lib_tasks_lint.py lint:414                             Saved cfile in './linter_warnings.txt'
dataflow/core/utils.py:223:[amp_mypy] error: Need type annotation for 'dfs' (hint: "dfs: Dict[<type>, <type>] = ...")  [var-annotated]
dataflow/core/utils.py:228:[amp_pylint] [R1704(redefined-argument-from-local), convert_to_multiindex] Redefining argument with the local name 'df'
dataflow/core/utils.py:277:[amp_pylint] [C0209(consider-using-f-string), convert_to_list] Formatting a regular string which could be a f-string
dataflow/core/utils.py:304:[amp_pylint] [C0209(consider-using-f-string), get_forward_cols.<lambda>] Formatting a regular string which could be a f-string
dataflow/core/utils.py:304:[amp_pylint] [C3001(unnecessary-lambda-assignment), get_forward_cols.<lambda>] Lambda expression assigned to a variable. Define a function using the "def" keyword instead.
dataflow/core/utils.py:399:[amp_mypy] error: Value of type "Optional[Match[str]]" is not indexable  [index]
dataflow/core/utils.py:403:[amp_mypy] error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
```

All the other changes are made by cleaning code base script for updating function calls and imports.

2024-03-04 23:36 UTC, gpsaggese reviewed
Not bad as first PR. Keep pushing.

2024-03-04 23:36 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +        df = self.get_test_data()
Let's add comments to split the chunks of the code.
```
# Prepare inputs.
...
# Run the code.
...
# Check the output.
```

Can you propose a change to the doc to ./docs/coding/all.write_unit_tests.how_to_guide.md to explain this, if it's not there already?
You can do it in a different PR

2024-03-04 23:36 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +        Test that the function transforms the DataFrame correctly.
the -> a

2024-03-04 23:36 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +        )
We don't like copy/paste, not even in test code.
This can be factored out in an helper function.
You can ask @samarth9008 @sonaalKant how to do it.

Again feel free to improve the doc to clarify this

2024-03-04 23:36 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +        )
I'd add also a check_string to test even better.

2024-03-04 23:36 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +        )
Other tests for the corner cases should be a df with only one asset.

Think about what other corner cases there can be. You can/should look at the function.

What happens with an empty df?
What if asset_id_col doesn't exist?
What if there is no index?

Your goal is to find corner cases where the function doesn't behave properly. Otherwise you just test what you know already know that works, which is not great.

Again pls improve the doc with this wisdom pills.

2024-03-05 00:36 UTC, Jd8111997 commented
Thanks for the suggestions @gpsaggese , I will update the PR.

2024-03-05 05:02 UTC, Jd8111997 commented on dataflow/core/test/test_utils.py
> +        )
@samarth9008 @sonaalKant Can you please elaborate on this ?

2024-03-06 02:52 UTC, Jd8111997 commented on dataflow/core/test/test_utils.py
> +        )
@samarth9008 @sonaalKant Can you please let me know about this ?

2024-03-06 03:03 UTC, sonaalKant commented on dataflow/core/test/test_utils.py
> +        )
Just move the repetitive code to a helper function. Eg : `_test_convert_to_multiindex`  is a new method which takes input df, expected df and assert on mismatch.

2024-03-06 22:35 UTC, Jd8111997 commented
@sonaalKant @samarth9008, I have updated the PR incorporating all suggestions provided by  @gpsaggese

2024-03-09 18:25 UTC, samarth9008 commented
Resolve the conversation if they are addressed.

2024-03-09 18:35 UTC, samarth9008 requested changes
TODO(Samarth): Don't merge before creating a PR on cmamp and testing it over there also

2024-03-09 18:35 UTC, samarth9008 commented on research_amp/cc/notebooks/CMTask1704_Get_raw_CC_data.py
> +import dataflow.core.utils as dtfcorutil
No need of full import as we are outside the dataflow dir(package). The import in the above line will work. 

The idea is
When we are outside a package, e.g., `dataflow/core`, we import the whole package like we did here `import dataflow.core as dtfcore`. We do it even if we need to address only one function. The exception is for `helpers`, there're too much dependencies that can affect on a flow so we import it as modules even if we outside the package, e.g. `helpers.hgit`.

The opposite, if we would be inside the package, e.g., inside `dataflow`, we would import `import dataflow.core.utils as dtfcorutil` to prevent cycle imports that could ruin the code sometimes.

Simply saying, module is a py-file, package is a dir that contains py-files. Does it make sense?

Make changes everywhere

2024-03-11 19:21 UTC, Jd8111997 commented on research_amp/cc/notebooks/CMTask1704_Get_raw_CC_data.py
> +import dataflow.core.utils as dtfcorutil
Thanks @samarth9008 for the feedback. I updated the PR incorporating all your suggestion.

2024-03-14 17:51 UTC, gpsaggese commented
Going in the right direction.
As discussed, you need to resolve all the comments and ask for a new review.

2024-03-14 20:11 UTC, Jd8111997 commented
@sonaalKant @samarth9008 I resolved and addressed all feedback in my latest PR. Could you please review it again ?

2024-03-16 12:47 UTC, sonaalKant requested changes
Almost there.

2024-03-16 12:47 UTC, sonaalKant commented on dataflow/core/test/test_utils.py
> +    def test3(self) -> None:
Why -> None? when you are return boolean

2024-03-16 12:47 UTC, sonaalKant commented on dataflow/core/test/test_utils.py
> +        except AssertionError:
Instead of catching the Assertion error and returning True, get the error message and and assert_equal on expected error message. Otherwise this test case will pass if it fails on something else.

2024-03-16 12:47 UTC, sonaalKant commented on dataflow/core/test/test_utils.py
> +                                        ):
->
```
def assert_multiindex_columns_equal(
 self,
 expected_df_columns: pd.MultiIndex,
 actual_df: pd.DataFrame,
 ) -> None:
```

2024-03-17 12:15 UTC, gpsaggese reviewed
Good work. Few nits and then merge.

Let's push on this so we can move to the next one

2024-03-17 12:15 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +                                        expected_df_columns: pd.MultiIndex,
Linter

2024-03-17 12:15 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +        Compares the list of columns of actual df and and expected df.
-> Compare

2024-03-17 12:15 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +        expected_error_message = "\n################################################################################\n* Failed assertion *\nInstance of '(                              id close  volum
I would do ''' so you don't have to use \n and it can be formatted better

2024-03-17 12:15 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +
Linter

2024-03-17 12:15 UTC, gpsaggese commented on dataflow/core/utils.py
> +    Transform a df like: ```
You want an empty line before ``` for the linter to be happy

2024-03-18 04:22 UTC, Jd8111997 commented
Done, I also attached linter output for test_utils.py for your reference @gpsaggese.

2024-03-18 16:36 UTC, sonaalKant approved these changes
LGTM

2024-03-19 17:42 UTC, gpsaggese reviewed
Final tweaks and merge for me

2024-03-19 17:42 UTC, gpsaggese commented on linter_output.txt
> +The AM_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
No need to add this to the PR. FYI the GH action automatically compute this

2024-03-19 17:42 UTC, gpsaggese commented on dev_scripts/client_setup/requirements.txt
> +pyyaml == 5.3.1
Why is this needed?

2024-03-19 17:42 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +        Function that returns dummy dataframe with multiple asset id and
Return ...

2024-03-19 17:42 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +        " Function that returns dummy dataframe with single asset id and
No "

-> Return ...

2024-03-19 17:42 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +    def get_test_data() -> Tuple[pd.DataFrame, pd.MultiIndex]:
-> get_test_data_multiple_assets for symmetry

2024-03-19 17:42 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +        expected_error_message = '\n################################################################################\n* Failed assertion *\n1 <= 0\n###################################################
You can use r""" to make it look better

2024-03-19 17:42 UTC, gpsaggese commented on dataflow/core/test/test_utils.py
> +        expected_error_message = "\n################################################################################\n* Failed assertion *\nInstance of '(                              id close  volum
Same r""" to make it readable

2024-03-19 18:36 UTC, Jd8111997 commented on linter_output.txt
> +The AM_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
Alright!

2024-03-19 18:48 UTC, Jd8111997 commented on dev_scripts/client_setup/requirements.txt
> +pyyaml == 5.3.1
Because I was getting `pyyaml` dependency error while I was trying to build virtual environment so I have to manually add this in `requirements.txt`. I mentioned it here: [Issue](https://github.com/sorrentum/sorrentum/issues/668#issuecomment-1962759845l)

2024-03-19 19:07 UTC, Jd8111997 commented on dataflow/core/test/test_utils.py
> +        expected_error_message = '\n################################################################################\n* Failed assertion *\n1 <= 0\n###################################################
I tried using multi-line string formatting, but to improve readability, I also need to add indentations. However, since the `actual_error_message` does not contain any indentations, the `assert_equal` method will fail. I attempted to remove the indentations from the multi-line string, but it ended up looking even more unappealing. I have attached an image for your reference."
![oie_al2wAyCQsR1e](https://github.com/sorrentum/sorrentum/assets/22273421/14df3b77-bb82-47eb-8a33-a1cccd8eb526)

2024-03-19 19:18 UTC, Jd8111997 commented on dataflow/core/test/test_utils.py
> +        expected_error_message = '\n################################################################################\n* Failed assertion *\n1 <= 0\n###################################################
Okay, thanks for suggestion @samarth9008, I will try and let you know.

2024-03-19 20:08 UTC, Jd8111997 commented on dataflow/core/test/test_utils.py
> +        expected_error_message = '\n################################################################################\n* Failed assertion *\n1 <= 0\n###################################################
@samarth9008 This doesn't work, it ends up modifying message content.
![oie_uaTvufbEpxzz](https://github.com/sorrentum/sorrentum/assets/22273421/0ef38817-3603-40ab-b6d0-f0d61ffb01ec)

2024-03-20 17:57 UTC, Jd8111997 commented on dataflow/core/test/test_utils.py
> +        expected_error_message = '\n################################################################################\n* Failed assertion *\n1 <= 0\n###################################################
@samarth9008 @gpsaggese Do you have any other suggestion ?

2024-03-21 18:31 UTC, Jd8111997 commented on dev_scripts/client_setup/requirements.txt
> +pyyaml == 5.3.1
@gpsaggese Should I remove this ?

2024-03-22 19:06 UTC, sonaalKant commented on dataflow/core/test/test_utils.py
> +        expected_error_message = '\n################################################################################\n* Failed assertion *\n1 <= 0\n###################################################
Try this. `self.assert_equal(actual, expected, fuzzy_match=True)`

2024-03-22 19:27 UTC, Jd8111997 commented on dataflow/core/test/test_utils.py
> +        expected_error_message = '\n################################################################################\n* Failed assertion *\n1 <= 0\n###################################################
Thanks @sonaalKant, it worked!

2024-03-22 19:31 UTC, Jd8111997 commented on dev_scripts/client_setup/requirements.txt
> +pyyaml == 5.3.1
@sonaalKant Shall I remove this or keep it ?

2024-03-22 21:07 UTC, samarth9008 commented
@Jd8111997 Once the changes are resolved, always request the review from the person who requested the changes.

2024-03-22 21:09 UTC, samarth9008 commented on dev_scripts/client_setup/requirements.txt
> +pyyaml == 5.3.1
You can keep it.


@gpsaggese This is a usual dependency on sorrentum which is generating errors while building the env for new people. I would suggest we can keep it for now and can file follow-up to deal with this

@Jd8111997 Can you file an issue for this? No need to work on it. Just an issue.

2024-03-22 21:12 UTC, samarth9008 commented
Before merging I would suggest to create a PR in `cmamp` as we are touching a lot of core stuff

FYI @sonaalKant

2024-03-22 21:26 UTC, samarth9008 reviewed
Recommendation and question

2024-03-22 21:26 UTC, samarth9008 commented on dataflow/core/test/test_utils.py
> +        """
Take a look how I have created this exp msg. Make sure it looks like this for other test as well.

2024-03-22 21:26 UTC, samarth9008 commented on dataflow/notebooks/build_dag_with_different_approaches.how_to_guide.py
> +converted_data = dtfcore.utils.convert_to_multiindex(
Does `dtfcore.convert_to_multiindex(..)` works? Check everywhere.

If it doesn't add import with utils at the top and use that to call the function directly. Same approach everywhere.

2024-03-22 21:28 UTC, Jd8111997 commented on dev_scripts/client_setup/requirements.txt
> +pyyaml == 5.3.1
Absolutely @samarth9008.

2024-03-22 21:52 UTC, Jd8111997 commented on dataflow/core/test/test_utils.py
> +        """
Thanks, it did work!

2024-03-22 22:39 UTC, Jd8111997 commented on dataflow/notebooks/build_dag_with_different_approaches.how_to_guide.py
> +converted_data = dtfcore.utils.convert_to_multiindex(
@samarth9008 I am confused about this. So what are you saying is directly importing the whole package as ```dtfcore``` and calling ```convert_to_multiindex(..)``` everywhere ? Also what about your [previous suggestion](https://github.com/sorrentum/sorrentum/pull/712#discussion_r1518642013 ). Could you please elaborate on this ?

2024-03-26 20:19 UTC, Jd8111997 commented on dataflow/notebooks/build_dag_with_different_approaches.how_to_guide.py
> +converted_data = dtfcore.utils.convert_to_multiindex(
@samarth9008 any update on this ?

2024-03-26 20:22 UTC, samarth9008 commented on dataflow/notebooks/build_dag_with_different_approaches.how_to_guide.py
> +converted_data = dtfcore.utils.convert_to_multiindex(
> @samarth9008 I am confused about this. So what are you saying is directly importing the whole package as dtfcore and calling convert_to_multiindex(..) everywhere ?

Yes. If that doesn't work you can import the whole path to the file that contains the function.

2024-03-26 20:22 UTC, samarth9008 commented on dataflow/notebooks/build_dag_with_different_approaches.how_to_guide.py
> +converted_data = dtfcore.utils.convert_to_multiindex(
Basically removing the utils in between.

2024-03-28 04:27 UTC, Jd8111997 commented on dataflow/notebooks/build_dag_with_different_approaches.how_to_guide.py
> +converted_data = dtfcore.utils.convert_to_multiindex(
Done.

2024-03-29 20:14 UTC, merged