SorrTask692_unit_test_get_session
sorrentum/sorrentum pull request #714
Opened 2024-03-05 19:28 UTC by Er1-x

Task #692 
@samarth9008 @sonaalKant 
Create a session and create a new bucket with resource() and verify this new bucket with client().

Review request:
1. Am I test this boto3.session.Session() in a right way? Or maybe there is a formal way to verify that a Session is built up correctly.
2. Should I add some more test for other logic such as 'ck' ?
3. Is this ok to use resource() to test Session? I think this is a bit repetitive with #694

2024-03-07 19:03 UTC, Er1-x commented
@samarth9008 I have run linter on this file, can you pls help me review and merge this PR?

2024-03-07 22:19 UTC, gpsaggese commented on helpers/test/test_haws.py
> +
No need for empty lines.

2024-03-08 19:46 UTC, Er1-x commented on helpers/test/test_haws.py
> +        del os.environ["MOCK_AWS_ACCESS_KEY_ID"]
I think we need to tear down the mock system environment variables after the unit test. I'm not sure about this. I see similar code in test_s3.py

2024-03-08 20:37 UTC, Er1-x commented
@gpsaggese sir, I have resolved all the comments, run linter and fix the `dassert_*` \ `self.assert*` problem you mentioned in #711 . pls check and verify.

2024-03-08 20:38 UTC, Er1-x commented
> @gpsaggese sir, I have resolved all the comments, run linter and fix the `dassert_*` \ `self.assert*` problem you mentioned in #711 . pls check and verify.

Also, I have merged the master into my branch

2024-03-09 18:24 UTC, samarth9008 requested changes
TODO(Samarth): Don't merge before creating a PR on cmamp and testing it over there also

2024-03-09 18:24 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        del os.environ["MOCK_AWS_ACCESS_KEY_ID"]
Not needed you can remove it

2024-03-10 04:56 UTC, Er1-x commented
@samarth9008 @gpsaggese @sonaalKant
Fixed the nits and resolved the conflicts. Please verify

2024-03-10 06:54 UTC, Er1-x commented
> TODO(Samarth): Don't merge before creating a PR on cmamp and testing it over there also

I see the same comments on the other PRs, should we create PRs on cmamp or should we wait for you to assign these tasks?

2024-03-11 11:57 UTC, merged