SorrTask682_improve_hpandas_compare_dfs
sorrentum/sorrentum pull request #717
Opened 2024-03-06 23:40 UTC by tkpratardan

Task #682 
@samarth9008 @sonaalKant 

I have made changes and implemented the `pd.testing.assert_frame_equal()` in the required place. Please let me know if I am going in the right direction. Could you please review and let me know the required changes? 

I made a couple of changes to the logic of the code as well that I felt needed to fixed. Please let me know 

cc: @gpsaggese

2024-03-06 23:42 UTC, tkpratardan commented on helpers/hpandas.py
> -    The operation is not performed in place and the resulting df is returned.
These have been changed after linter

2024-03-06 23:44 UTC, tkpratardan commented on helpers/hpandas.py
>      zero_vs_zero_is_zero: bool = True,
Do we require `compare_nans` variable? As `assert_frame_equal()` does not allow us to specify the use case

2024-03-06 23:47 UTC, tkpratardan commented on helpers/hpandas.py
> +        df_diff = 100 * (df1 - df2) / df2.abs()
added `df2.abs()`. Because in the previous version of the code, `df2 has -2` and `df1 has -1` the percentage change would be `-50` where it should have been `50`. Let me know if this right?

2024-03-06 23:49 UTC, tkpratardan commented on helpers/hpandas.py
> +        if remove_inf:
Placed `remove_inf` before the checking for `assert_diff_threshold`  following the comments in the previous version. In the previous version the check would fail because `inf` is not removed, as it should be.

2024-03-07 21:43 UTC, gpsaggese reviewed
Nice. Your code is not bad and you are picking up the code style and our idioms quickly.

Keep improving and you are getting ready

2024-03-07 21:43 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +
No need for empty lines.

When you need an empty line is often an indication that you need to add a comment.

The unit tests should have a clear pattern

```
# Prepare inputs.
...
# Execute.
...
# Check output.
...
```

Can you file a bug to update ./docs/coding/all.write_unit_tests.how_to_guide.md with this
?

2024-03-07 21:43 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +        with self.assertRaises(AssertionError):
Let's check the output of the assertion 

Something like:
helpers/test/test_dbg.py:670

Can you pls file an issue to you to adding this to 
./docs/coding/all.write_unit_tests.how_to_guide.md

You can mark this resolved posting the pointer to the GH Issue

2024-03-07 21:43 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +        -Check test case when negative values in df2.
No -

2024-03-07 21:43 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +        returned when `index_is_datetime = True`. column1     column2 index
You need to add a verbatim

```

to make the linter not reflow the comment.

This is a pre-existing issue, but let's fix it

2024-03-08 17:25 UTC, gpsaggese commented on helpers/hpandas.py
> -    The operation is not performed in place and the resulting df is returned.
That's fine. Whoever wrote the code forgot to run the linter.

The best approach in these cases is to do a quick PR only running the linter so that your PR is clean.
Can you do this?

- You can create a PR SorrTask682_improve_hpandas_compare_dfs_1
with only running the linter
- Submit the PR (usually we allow to merge directly, but in this case we will do a quick review)
- Then merge master back into this PR
- Keep working on this PR

Sometimes this is called stacked PR workflow.

2024-03-08 17:25 UTC, gpsaggese commented on helpers/hpandas.py
> +    # Check value of `assert_diff_threshold` if exists.
This comment should go to line 1970

2024-03-08 17:25 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +    def test11(self) -> None:
The right approach is to do another stacked PR, where you merge the code with all the unit tests to "freeze" the behavior before changing the guts of the function.

Sometimes it's called "scaffolding the code with unit tests"

2024-03-09 18:52 UTC, samarth9008 reviewed
TODO(Samarth): Don't merge before creating a PR on cmamp and testing it over there also

2024-03-09 18:53 UTC, samarth9008 requested changes
TODO(Samarth): Don't merge before creating a PR on cmamp and testing it over there also

2024-03-10 22:46 UTC, tkpratardan commented on helpers/test/test_hpandas.py
> +    def test11(self) -> None:
@gpsaggese 
Thank you for pointing it out. 
I still have a question about the failing unit tests of other functions of hpandas. How do you suggest we fix it, if at all?

2024-03-11 12:47 UTC, tkpratardan commented on helpers/test/test_hpandas.py
> +
GH Issue #729

2024-03-13 05:24 UTC, sonaalKant commented on helpers/hpandas.py
> +        df_diff = 100 * (df1 - df2) / df2.abs()
@gpsaggese wdyt?

2024-03-14 20:00 UTC, gpsaggese reviewed
Not bad. But we need unit tests for all the corner cases

2024-03-14 20:00 UTC, gpsaggese commented on helpers/hpandas.py
> +        df_diff = 100 * (df1 - df2) / df2.abs()
I agree that the new code is correct.

2024-03-14 20:00 UTC, gpsaggese commented on helpers/hpandas.py
> +
No empty line

2024-03-14 20:00 UTC, gpsaggese commented on helpers/hpandas.py
> +        try:
The code is correct but difficult to read.

```
# Test and convert the assertion into a boolean `is_ok`.
is_ok = True
try:
      pd.testing...
except ...
      is_ok = False
# If it's not ok, raise or not depending on `only_warning`.
if not is_ok:
     hdbd._dfatal(...)
```

Also `msg` needs to specified like "df1=%s and df2=%s don't have compatible size"

2024-03-14 20:00 UTC, gpsaggese commented on helpers/hpandas.py
> +            try:
Same idiom as before

2024-03-14 20:15 UTC, tkpratardan commented on helpers/hpandas.py
> -        hdbg.dassert_eq(0, nan_diff_df.shape[0], msg=msg)
@gpsaggese @sonaalKant 
There is one corner case here. In the context of the new code, `compare_nans` is redundant because we cannot explicitly mention the comparison of just some particular invariants. The thing is, this is to some extent mitigated by the use of `only_warning` where only a warning is issued. But the consider the corner case with `only_warning = True`:

- df1 and df2 have NaNs at different locations. (which will raise an assertion but will not abort the function with only_warning switch)

- At a particular location, the difference between two elements in df1 and df2 has exceeded the limit established by `pd.testing.assert_frame_equal()`. This will also raise an assertion.

In our case, if we want to ignore NaN comparison, but not the difference threshold, we cannot specifically do that in the new implementation. 

Could you please let me know if this behavior is valid? Or should we work it around?

2024-03-14 21:25 UTC, tkpratardan commented on helpers/hpandas.py
> +        try:
@gpsaggese 
I understood the changes in the code structure, but I am not sure I followed the implementation of the message. Are you suggesting the we include the dataframes in the message through the custom `df_to_str()` that we built or the location/values of the elements where the comparison is failing?

2024-03-16 12:52 UTC, gpsaggese reviewed
Let's merge master with your 2 PRs, make the changes and merge.

We are close. This one was a bit difficult as first issue, but the work was not bad

2024-03-16 12:52 UTC, gpsaggese commented on helpers/hpandas.py
> -        hdbg.dassert_eq(0, nan_diff_df.shape[0], msg=msg)
Based on my interpretation, the problem is much simpler.
Now we use `compare_nans_in_dataframes` to decide if two dataframes are "compatible" from the nan point of view (based on some criteria that are in `compare_nans_in_dataframes`).

You just have to pass only_warning to dassert

```
        msg = "There are NaN values in one of the dataframes that are not in the other one."
        hdbg.dassert_eq(0, nan_diff_df.shape[0], msg=msg, only_warning=only_warning)
```

Makes sense?

2024-03-16 12:52 UTC, gpsaggese commented on helpers/hpandas.py
> +        try:
Correct. When you throw an assertion you need to give as much context as possible.
E.g., imagine the code runs for 3 hours and then asserts with a message like "The dfs have not compatible size", what do you do next? Change the assertion and run again for 3 hours? How many iterations it takes to fix?

You want to give as much info as possible so you can fix the bug in one iteration.
In this case printing the size might help a bit. Sometimes we dump the dfs to disk for further analysis, but in this case it's overkilling.

Makes sense?

2024-03-16 12:52 UTC, gpsaggese commented on helpers/hpandas.py
> +        df_diff = 100 * (df1 - df2) / df2.abs()
You can resolve this.

2024-03-16 13:03 UTC, tkpratardan commented on helpers/hpandas.py
> -        hdbg.dassert_eq(0, nan_diff_df.shape[0], msg=msg)
Yes

2024-03-16 15:59 UTC, gpsaggese commented on helpers/hpandas.py
> -        hdbg.dassert_eq(0, nan_diff_df.shape[0], msg=msg)
The issue is how to interpret the specs. I believe you are interpreting them in a more stringent that what they actually mean.

To be pragmatic:
- Let's merge the unit tests first, and then you can create a unit test for this case that you think it's problematic.
- Also it's too complicated to understand each other on GH. In these cases, we would do a quick call. We can set up an office hour to discuss all these issues needing high bandwidth.

2024-03-16 15:59 UTC, gpsaggese commented on helpers/hpandas.py
> +        try:
Ok. If you are ok, you can make this change and resolve this.

2024-03-17 06:51 UTC, tkpratardan commented on helpers/hpandas.py
> +        # Calculate the difference.
@gpsaggese 
Let me know if I am going in the right direction, and if this is how you expect the code structure to look like

2024-03-17 16:37 UTC, tkpratardan commented on helpers/hpandas.py
> -        hdbg.dassert_eq(0, nan_diff_df.shape[0], msg=msg)
@gpsaggese 
Sure. Thank you

2024-03-17 22:50 UTC, gpsaggese reviewed
Going in the right direction. Good work

2024-03-17 22:50 UTC, gpsaggese commented on helpers/hpandas.py
> +    :param only_warning: when `True` the function issues a warning instead of aborting
Reflow with linter

2024-03-17 22:50 UTC, gpsaggese commented on helpers/hpandas.py
> +    # Check value of `assert_diff_threshold` if exists.
-> , if it was passed.

2024-03-17 22:50 UTC, gpsaggese commented on helpers/hpandas.py
> +            assertion = e
You don't use `assertion`, so I wouldn't store it.

You can do `_ = e` to make the linter happy

2024-03-17 22:50 UTC, gpsaggese commented on helpers/hpandas.py
> +        # Check `is_ok` and raise an assertion depending on `only_warning`
Always `.` at the end of a comment

2024-03-17 22:50 UTC, gpsaggese commented on helpers/hpandas.py
> +        # Calculate the difference.
That's good.

2024-03-17 22:50 UTC, gpsaggese commented on helpers/hpandas.py
> +                    "df1=\n%s\n and df2=\n%s\n don't have compatible size",
-> are not equal.

2024-03-20 02:07 UTC, tkpratardan commented
@gpsaggese @sonaalKant 
Fixed the nits. Please verify.

2024-03-23 15:12 UTC, tkpratardan commented on helpers/hpandas.py
> +                    "df1=\n%s\n and df2=\n%s\n have pct_change more than `assert_diff_threshold`.",
@sonaalKant @gpsaggese 
I changed the assertion message here, which I feel gives more information. Let me know if this okay.

2024-03-23 16:48 UTC, tkpratardan commented on helpers/hpandas.py
> -        hdbg.dassert_eq(0, nan_diff_df.shape[0], msg=msg)
@gpsaggese 
I guess the problem would be clear now. As you can see, test8 is failing (NaN comparison) because of `only_warning = True` and no assertion is raised. However, to avoid the regression, if we setup `only_warning = False`, some of the testcases setup previously would fail because the element-wise difference between the two dfs is more than the threshold. So my point being, it would be difficult to control two types of comparisons with a single switch.

2024-03-24 01:33 UTC, tkpratardan commented on helpers/test/test_hpandas.py
> +        2022-01-01 21:04:00+00:00        185.862978     -765.280229       -153.498432     198.418808
@gpsaggese @sonaalKant 
Since we change the formula for calculating the pct_change (addition of df2.abs()). I also changed the values of a test case of another function that use using compare_dfs(). Let me know if this is okay.

2024-03-24 15:15 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +        2022-01-01 21:04:00+00:00        185.862978     -765.280229       -153.498432     198.418808
That's correct

2024-03-24 15:15 UTC, gpsaggese commented on helpers/hpandas.py
> +                    "df1=\n%s\n and df2=\n%s\n have pct_change more than `assert_diff_threshold`.",
No need to tag us. It's clear from the context.

Good change.

2024-03-24 15:15 UTC, gpsaggese commented on helpers/hpandas.py
> +                    _,
Unclear why you pass _ here.

Better to construct a message and then pass it, in fact I think the interface is being used in a weird way

dfatal(message: str, assertion_type: Optional[Any] = None)

I'll merge if all tests are passing, and then you can fix in a different PR

2024-03-24 15:15 UTC, merged

2024-03-24 17:02 UTC, tkpratardan commented on helpers/hpandas.py
> +                    _,
> dfatal(message: str, assertion_type: Optional[Any] = None)

Isn't hdbg.dfatal() used only for aborting (no `only_warning`)? I guess we need to construct if-else blocks based on the value of `only_warning` to use this. Did I understand this correctly?


> Better to construct a message and then pass it,

Sure, I will make this change.

> in fact I think the interface is being used in a weird way

I am not sure I can follow your point of view here. I used my intuition based on the guidelines to use this interface in this implementation, as I couldn't find examples of its usage. In this particular case, the assertion error was raised by `assert_frame_equal()`, and to print the error with modifications, I had to use _dfatal(). This is unlike the using hdbg function which uses _dfatal() internally 

> Unclear why you pass _ here.

Honestly, I couldn't understand the actual rationale as well. (:D)
I supposed it would mess up linter from your suggestion [here](https://github.com/sorrentum/sorrentum/pull/717#discussion_r1527632562). This whole change was to make the code more readable.