Add stages to DaoSwap contract to limit creation of new orders
sorrentum/sorrentum pull request #72
Opened 2023-03-26 04:48 UTC by KangmingL

Add stages to limit the creation of new sell/buy orders when OnSwapTime is in processing.

2023-03-27 16:18 UTC, tamriq requested changes
Good job! But let's change the direction

2023-03-27 16:18 UTC, tamriq commented on defi/dao_swap/contracts/DaoSwap.sol
> +        stage = Stages.Processing;
I just realised that when we change the stage from inside of `onSwapTime()` function, the new stage value is not written to blockchain until `onSwapTime()` is done. So it doesn't make sense :/ My bad. But I have another idea.
E.g. we can have `lockOrders` modifier that locks some functions while the modified function is running.
```
bool private locked;

    modifier lockOrders() {
        locked = true;
        _;
        locked = false;
    }
```
And use it with `onSwapTime`, so the modifier sets locked to true, runs the function, and then sets locked back to false. On the other hand, for sell and buy functions we can create modifier `isLocked`:
```
     modifier isLocked() {
        require(locked == false, "Unable to submit new orders while swap calculations are in progress" )
        _;
    }
```

Makes sense?

2023-04-02 15:07 UTC, KangmingL commented on defi/dao_swap/contracts/DaoSwap.sol
> +        stage = Stages.Processing;
Hi Toma, 
Thanks for your feedback!
I'm a bit confused because from my understanding we want to change the stage value after onSwapTime() is done. Also, what's the difference between using the modifier lockOrders() and changing stages at the beginning and the end of onSwapTime(), I think "_;" just means run the onSwapTime() function.

2023-06-23 10:29 UTC, DanilYachmenev commented
probably obsolete, moving to P1 for now

2023-08-30 16:12 UTC, samarth9008 commented
I believe not required anymore and also the logic of it is changed so closing. If needed we will reopen it.

2023-08-30 16:12 UTC, closed without merging