SorrTask695_unit_test_get_ecs_client
sorrentum/sorrentum pull request #720
Opened 2024-03-07 06:37 UTC by jayhsu0627

Task #695 

Created a unit test to check the ecs client. Pls help me review and merge.

Best!

2024-03-08 18:50 UTC, gpsaggese commented on helpers/test/test_haws.py
> +
no empty line.

2024-03-08 18:50 UTC, gpsaggese commented on helpers/test/test_haws.py
> +        # Create mock ecs client
. at the end of comments

ecs -> ECS since it's an acronym (see docs/coding/all.coding_style.how_to_guide.md:316)

Can you pls re-read the how to guide to internalize.

2024-03-08 18:50 UTC, gpsaggese commented on helpers/test/test_haws.py
> +        print(cluster_name)
docs/coding/all.coding_style.how_to_guide.md:755 ### Always use logging instead of prints

2024-03-08 18:50 UTC, gpsaggese commented on helpers/test/test_haws.py
> +        hdbg.dassert_in(test_cluster_name, cluster_name)
You can see the comment in 
https://github.com/sorrentum/sorrentum/pull/711#pullrequestreview-1925574939

2024-03-09 18:20 UTC, samarth9008 requested changes
TODO(Samarth): Don't merge before creating a PR on cmamp and testing it over there also

2024-03-12 12:11 UTC, samarth9008 commented
@Er1-x Can you complete this PR?

2024-03-12 13:53 UTC, Er1-x commented
> @Er1-x Can you complete this PR?

sure, I will start fixing these comments.

2024-03-12 15:27 UTC, jayhsu0627 commented on helpers/test/test_haws.py
> +
done

2024-03-12 15:30 UTC, jayhsu0627 commented on helpers/test/test_haws.py
> +        # Create mock ecs client
got it

2024-03-12 15:30 UTC, jayhsu0627 commented on helpers/test/test_haws.py
> +        print(cluster_name)
removed print()

2024-03-12 16:29 UTC, Er1-x commented
Fixing the nits:

2024-03-12 16:32 UTC, Er1-x commented
Fixing the nits:
1. Remove empty lines and all the print() functions.
2. Add `.` at the end of comments, change upper letters for acronym.
3. Change `dassert_*` to `self.assert*`.

2024-03-12 16:33 UTC, Er1-x commented
> Fixing the nits:
> 
> 1. Remove empty lines and all the print() functions.
> 2. Add `.` at the end of comments, change upper letters for acronym.
> 3. Change `dassert_*` to `self.assert*`.

Also I have run linter and merged master.

2024-03-12 21:05 UTC, samarth9008 requested changes
Good work! Some suggestions.

2024-03-12 21:05 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        test_cluster_name = "TEST-CLUSTER"
-> test-cluster

2024-03-12 21:05 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Create a client using tested function.
Create ECS client.

2024-03-12 21:05 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Check if the region and cluster name in the created cluster.
Check region and cluster name.

2024-03-12 21:05 UTC, samarth9008 commented on helpers/test/test_haws.py
> +    def test1(self) -> None:
Add one more test without any region

2024-03-12 21:25 UTC, jayhsu0627 commented
@samarth9008 I can resolve the follow-up issues.

2024-03-13 00:06 UTC, jayhsu0627 commented on helpers/test/test_haws.py
> +        test_cluster_name = "TEST-CLUSTER"
done

2024-03-13 00:06 UTC, jayhsu0627 commented on helpers/test/test_haws.py
> +        # Create a client using tested function.
done

2024-03-13 00:06 UTC, jayhsu0627 commented on helpers/test/test_haws.py
> +        # Check if the region and cluster name in the created cluster.
done

2024-03-13 00:08 UTC, jayhsu0627 commented on helpers/test/test_haws.py
> +    def test1(self) -> None:
Added.
Logic as follows: preserve the region for boto3.client but test the `get_ecs_client` w/o given region name. See if the region name was retrieved from `os.environ`

2024-03-13 18:42 UTC, Er1-x commented
@samarth9008 I've noticed there are codes that repeat themselves, do we need to refactor it like GP requested in #714 ?

2024-03-13 21:30 UTC, samarth9008 commented
> @samarth9008 I've noticed there are codes that repeat themselves, do we need to refactor it like GP requested in #714 ?

You can try implementing them in a separate PR. That would be actual a nice thing to do. I would do create a class like `haws_test_case` with common code and inherit into all other classes.

2024-03-13 21:35 UTC, samarth9008 requested changes

2024-03-13 21:35 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        with ECS.
```
Test that `haws.get_ecs_client()` correctly return a client to work with ECS within a specified region.
```

2024-03-13 21:35 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Create ECS client.
Create -> Get

2024-03-13 21:35 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        Without assigned a region to the created ECS client.
```
Test that `haws.get_ecs_client()` correctly return a client to work with ECS without a specified region.
```

2024-03-13 21:35 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Create ECS client.
Create -> Get

2024-03-13 21:35 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        self.assertIn(region, cluster_name)
Why region over here?

2024-03-13 21:35 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        region = "us-east-1"
Do we need to define it?

2024-03-13 21:35 UTC, samarth9008 commented on helpers/test/test_haws.py
> +    def test2(self) -> None:
This test should be without region but it is specified everywhere.

2024-03-16 12:31 UTC, samarth9008 commented
> > @samarth9008 I've noticed there are codes that repeat themselves, do we need to refactor it like GP requested in #714 ?
> 
> You can try implementing them in a separate PR. That would be actual a nice thing to do. I would do create a class like `haws_test_case` with common code and inherit into all other classes.

@Er1-x No need to work on this as it is done by other person on a different PR. You can focus on test db utils issue.

2024-03-16 18:54 UTC, Er1-x commented on helpers/test/test_haws.py
> +    def test2(self) -> None:
> This test should be without region but it is specified everywhere.

I'm not sure if I get your point correct. Did you mean that I should change the name of this function?

2024-03-16 19:49 UTC, Er1-x commented on helpers/test/test_haws.py
> +        region = "us-east-1"
> Do we need to define it?

I think we need it since `region` is used in boto3.client()

2024-03-18 23:22 UTC, samarth9008 requested changes
Implement the change before resolving the conversation

2024-03-18 23:22 UTC, samarth9008 commented on helpers/test/test_haws.py
> +    def test2(self) -> None:
No, Implement the calling of the testing function without specifying the region.

2024-03-21 12:20 UTC, samarth9008 reviewed
Two nits.

2024-03-21 12:20 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        os.environ["MOCK_AWS_DEFAULT_REGION"] = "us-east-1"
No need of this.

Inherit `Haws_test_case` instead of `hunitest.TestCase`

2024-03-21 12:20 UTC, samarth9008 commented on helpers/test/test_haws.py
> +        # Check region and cluster name.
-> `# Check cluster name.`

2024-03-21 12:39 UTC, Er1-x commented
> Two nits.

Fixed

> Two nits.

Fixed

2024-03-21 12:39 UTC, Er1-x commented
> Two nits.

Fixed

2024-03-21 12:44 UTC, samarth9008 approved these changes
LGTM

2024-03-21 22:37 UTC, gpsaggese commented on helpers/test/test_haws.py
> +    def mock_ecs_client(self, region: Optional[str] = None) -> None:
Need a * before `region`

2024-03-22 13:32 UTC, samarth9008 approved these changes
LG

2024-03-22 13:33 UTC, merged