SorrTask704_Script_to_simplify_referring_to_docs_in_reviews
sorrentum/sorrentum pull request #723
Opened 2024-03-07 22:27 UTC by nehalR777

@samarth9008 @gpsaggese  , An initial draft of jackdoc . Issue mentiond[ here ](https://github.com/sorrentum/sorrentum/issues/704)

2024-03-07 22:45 UTC, nehalR777 commented
@samarth9008 @gpsaggese , 
A snippet of the output 
![image](https://github.com/sorrentum/sorrentum/assets/70251231/6c3bb132-4f2c-4fdf-80e0-43d9d455d7ff)

2024-03-09 09:06 UTC, gpsaggese commented on dev_scripts/jackdoc.py
> +    parser.add_argument("search_term", help="Input to search in Markdown files")
- Let's add an option to specify a subdir `dir`
- The search term should be a regex

2024-03-09 18:19 UTC, samarth9008 requested changes

2024-03-09 18:19 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +DOCS_DIR = "/src/sorrentum1/docs"
I would suggest not to hardcode the directory path as we want to run it in different repo as well. A nice way would be to get the GIT root dir and join it with docs dir. Something like `os.path.join(GIT_ROOT, docs)`

2024-03-10 06:17 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +DOCS_DIR = "/src/sorrentum1/docs"
@samarth9008 @gpsaggese , I have got this fixed working on the other nits

2024-03-10 06:17 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +                        if search_term in line:
@gpsaggese sir, this has been resolved. Working on the other nits

2024-03-10 07:05 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +                with open(md_file, 'r') as f:
@gpsaggese sir , this has been addressed.

2024-03-10 23:03 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +
@gpsaggese sir , this has been addressed.

2024-03-10 23:10 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +        for file_path, line_num in found_in_files:
@gpsaggese , this has been taken care of.

2024-03-11 01:51 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +    parser.add_argument("search_term", help="Input to search in Markdown files")
@gpsaggese sir , this has been addressed as well.

2024-03-11 03:27 UTC, nehalR777 commented
@samarth9008 @gpsaggese  , I have resolved majority of the nits mentioned . Just need further clarification on some things.
Our output currently looks something like this:
![image](https://github.com/sorrentum/sorrentum/assets/70251231/46497c01-d2c3-4c93-aba3-4c2f3072ff6f)

-Just need a little more clarity on how our final output should look like . 
-Also would like to get a feedback on the resolved conversations.

2024-03-11 12:12 UTC, gpsaggese commented on dev_scripts/jackdoc.py
> +    try:
you should use hsystem.system_to_string

Actually there is a function that does this in hgit.get_client_root

2024-03-11 12:12 UTC, gpsaggese commented on dev_scripts/jackdoc.py
> +        print("Input found in the following Markdown files:")
Always use the logger see

docs/coding/all.coding_style.how_to_guide.md

Try to read more of the code in dev_tools to see how we do things

2024-03-11 12:12 UTC, gpsaggese commented on dev_scripts/jackdoc.py
> +                toc_flag = False  # Flag to indicate if we are within the TOC
It's better to create a function that removes the TOC, instead of processing in line.
Then you can more easily test the code.

2024-03-11 12:12 UTC, gpsaggese commented on dev_scripts/jackdoc.py
> +            url = "{}/{}#L{}".format(git_root, file_path[len(git_root) + 1:], line_num)
Uhm. There are os functions to do this. E.g., os.path.relpath

2024-03-13 00:14 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +            url = "{}/{}#L{}".format(git_root, file_path[len(git_root) + 1:], line_num)
@gpsaggese sir , this has been resolved

2024-03-13 00:14 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +                toc_flag = False  # Flag to indicate if we are within the TOC
@gpsaggese sir this has been resolved

2024-03-14 01:17 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +    try:
@gpsaggese , resolved used hgit.get_client_root wherever necessary

2024-03-14 04:22 UTC, nehalR777 commented
@samarth9008 @gpsaggese @sonaalKant , The suggestions have been implemented just need to tweak the code so that we can have the output as per our need , just need a clarification how the final link should look like. Will write a uni test for everything implemented.

2024-03-15 22:55 UTC, samarth9008 requested changes
Few nits

Lets unify the approach. Refer to this script for coding style

https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/replace_text.py

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +jackdoc: A tool to search for input in Markdown files and provide links to the files where the input was found.
->jackdoc: Locate input in docs dir and generate corresponding file links.

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +import dev_scripts.jackdoc as jackdoc
Not needed IMO as we do not import scripts.

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +        help="Skip results in the table of contents (TOC)",
Skip search results from table of contents (TOC)

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +def remove_toc(content):
type hints and return type missing. Check everywhere.

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +    logging.basicConfig(level=logging.INFO)
Is there any other function for setting the log level. Try searching in the codebase. Not sure though. If not this is fine.

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +def parse_arguments():
-> _parse()

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +    main()
The correct approach is

```
_main(_parse())
```

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +def main():
-> _main(parser)

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +    args = parse_arguments()
-> args = parser.parse_args()

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +                        continue  # Skip lines if --sections-only is enabled and not a section heading
Comment and code not in one line.

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +
No empty line.

2024-03-15 22:55 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +            _LOG.info(url)
Instead of generating local line can we generate http link as mentioned in this conversation

https://github.com/sorrentum/sorrentum/issues/704#issuecomment-1973292379

2024-03-21 00:57 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +        "search_term", help="Regex pattern to search in Markdown files"
@samarth9008 have changed this to -> Term to search in Markdown files

2024-03-21 00:58 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +# Define the relative path to the docs directory
@samarth9008 resolved.

2024-03-21 00:58 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +import dev_scripts.jackdoc as jackdoc
@samarth9008 , this has been removed.

2024-03-21 00:59 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +jackdoc: A tool to search for input in Markdown files and provide links to the files where the input was found.
@samarth9008 , this has been resoved

2024-03-21 00:59 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +        help="Skip results in the table of contents (TOC)",
@samarth9008 , Resolved

2024-03-21 01:02 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +
@samarth9008 resolved

2024-03-21 01:03 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +                        continue  # Skip lines if --sections-only is enabled and not a section heading
@samarth9008 , resolved

2024-03-21 01:33 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +def parse_arguments():
@samarth9008 fixed

2024-03-21 01:34 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +    main()
@samarth9008 resolved

2024-03-21 01:34 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +def main():
@samarth9008 resolved

2024-03-21 01:34 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +    args = parse_arguments()
@samarth9008 , Resolved

2024-03-21 05:02 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +            _LOG.info(url)
@samarth9008 resolved

2024-03-21 05:03 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +def remove_toc(content):
@samarth9008 resolved

2024-03-21 05:03 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +    logging.basicConfig(level=logging.INFO)
@samarth9008 , resolved

2024-03-21 05:33 UTC, nehalR777 commented
@samarth9008 @gpsaggese @sonaalKant , jackdoc is now ready , all suggestions have been implemented . 
->One thing thats remains is - Everything should be carefully unit tested. 
-Do you want me to create another PR for the testing everything?

-Please do review and let me know if anything else has to be fixed . 

Also a quick guide on the usage: 
- jackdoc --sections-only "code" will look for keywords in the sections and generate links like - https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/sorrentum.set_up_development_environment.how_to_guide.md#Clone-the-code as suggested by @samarth9008 [here](https://github.com/sorrentum/sorrentum/issues/704#issuecomment-1973292379)
- jackdoc "code" will look for all instances in the documentation that have code in it and the output will be like this- https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/all.development_documents.reference.md?plain=1#L29 as suggested by @gpsaggese [here](https://github.com/sorrentum/sorrentum/issues/704#issue-2162178573)
--skip-toc : Skip search results from the table of contents (TOC)
--subdir SUBDIR : Subdirectory to search within

2024-03-21 12:42 UTC, samarth9008 reviewed
High level review. Will review in deep once the mentioned changes are implemented.

2024-03-21 12:42 UTC, samarth9008 commented on dev_scripts/jackdoc.py
> +    found_in_files: List[Tuple[str, int]] = _search_in_markdown_files(
No type hints over here as well. We can take a look at the function and see what it is returning.

2024-03-21 20:09 UTC, nehalR777 commented
@samarth9008 changes have been made as per your suggestions. Please do review.

2024-03-22 00:43 UTC, nehalR777 commented
@samarth9008 by default we will now have the sections as output as you suggested and if we want to search the keyword occurrence anywhere in the docs folder we can use the --line-only flag

2024-03-22 21:05 UTC, samarth9008 requested changes
Assuming your code works but the coding style is not to the mark

Take a look at my previous comments and also internalize the coding style doc.

Also add relevant comments in the code so the reader understands quicly by reading the logic

Not reviewing further for now as I feel like I am repeating the usual thing which are mentioned in the given docs.

2024-03-23 01:31 UTC, nehalR777 commented
@samarth9008 have implemented the changes following the coding style , docstrings have been added to every function. Type hints are used wherever necessary , empty lines have been removed , have added relevant comments in the code so that the reader understands quickly by reading the logic.

2024-03-26 19:38 UTC, samarth9008 reviewed
Almost there.

2024-03-26 19:41 UTC, nehalR777 commented
@samarth9008 , thank you for the review , I will make the requested changes and get it reviewed again.

2024-03-26 20:25 UTC, nehalR777 commented
@samarth9008 have resolved the suggestions you mentioned.

2024-03-28 18:46 UTC, samarth9008 commented
The output looks good but any reason for `__main__` in front of the output

```
(amp.client_venv) samarthk@dev1:~/src/sorrentum1$ dev_scripts/jackdoc.py "type hints" --skip-toc
DEBUG:helpers.hsystem:> (cd . && cd "$(git rev-parse --show-toplevel)/.." && (git rev-parse --is-inside-work-tree | grep -q true)) 2>&1
DEBUG:helpers.hsystem:> (git rev-parse --show-toplevel) 2>&1
INFO:__main__:Input found in the following items:
INFO:__main__:https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md#Use-type-hints
INFO:__main__:https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.type_hints.how_to_guide.md#Why-we-use-type-hints
INFO:__main__:https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.type_hints.how_to_guide.md#What-to-annotate-with-type-hints
```

2024-03-28 18:55 UTC, nehalR777 commented
@samarth9008 -So, when you see INFO:__main__: in the output, it means the log messages are originating from the main module of the script executed directly. Do you want me to replace that with jackdoc instead?

Output will look like: INFO:jackdoc:https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md#Use-type-hints

2024-03-28 19:04 UTC, samarth9008 reviewed
Final nits.

2024-03-28 19:10 UTC, samarth9008 commented
Refer to the change I made in the last commit.

2024-03-28 19:11 UTC, samarth9008 commented
Don't forget to run linter on the files before pushing.

2024-03-28 19:12 UTC, nehalR777 commented
Noted @samarth9008

2024-03-28 19:35 UTC, nehalR777 commented on dev_scripts/jackdoc.py
> +    :return:the argument parser object.
@samarth9008 resolved

2024-03-28 19:37 UTC, nehalR777 commented
@samarth9008 have resolved the nits mentioned.

2024-03-29 18:11 UTC, nehalR777 commented
@gpsaggese , sir do we have any additional suggestions on this one?

2024-03-30 17:34 UTC, gpsaggese reviewed
The code is not bad, but still:
1) doesn't follow our conventions
2) is not tested

Let's merge and do another pass

2024-03-30 17:34 UTC, gpsaggese commented on dev_scripts/jackdoc.py
> +def _get_github_info() -> Tuple[str, str]:
This still overlaps with `hgit.get_client_root`.
We should add a function to get the user in hgit and use only lib functions that are also tested

2024-03-30 17:34 UTC, gpsaggese commented on dev_scripts/jackdoc.py
> +            subprocess.check_output(
If we really need to do a system we should use our own `hsystem.system_to_string` instead of reinventing the wheel

2024-03-30 17:34 UTC, gpsaggese commented on dev_scripts/jackdoc.py
> +    skip_toc: bool = False,
Missing *

2024-03-30 17:34 UTC, gpsaggese commented on dev_scripts/jackdoc.py
> +    docs_path = (
Difficult to read. Let's write for humans
```
docs_path = os.path.join(git_root, DOCS_DIR)
if subdir:
   docs_path = os.path.join(subdir)
```

2024-03-30 17:34 UTC, gpsaggese commented on dev_scripts/jackdoc.py
> +    def search_content(content: str) -> List[Tuple[str, str]]:
These functions should be unit tested

2024-03-30 17:35 UTC, merged