SorrTask693_unit_test_get_service_client
sorrentum/sorrentum pull request #725
Opened 2024-03-08 04:20 UTC by tkpratardan

@samarth9008 

Created the unit test for `haws.get_service_client()`. Please review and let me know if any changes are required.

cc: @gpsaggese @sonaalKant

2024-03-08 17:07 UTC, gpsaggese commented
Can you pls merge master so we can merge the PR?

2024-03-08 18:02 UTC, tkpratardan commented
Prof. @gpsaggese. I have resolved the conflicts. Please check and verify.

2024-03-09 09:59 UTC, gpsaggese reviewed
Good progress. Let's get this done and merge

2024-03-09 09:59 UTC, gpsaggese commented on helpers/test/test_haws.py
> +        Test `haws.get_service_client()` returns a client for s3.
-> S3 (everywhere in comments)

S3 is an abbreviation

docs/coding/all.coding_style.how_to_guide.md:316

2024-03-09 09:59 UTC, gpsaggese commented on helpers/test/test_haws.py
> +        hdbg.dassert_eq(client.meta.service_model.service_name, "s3")
In unit tests there should be only self.assert_*

See another PR

2024-03-09 14:33 UTC, tkpratardan commented on helpers/test/test_haws.py
> +        hdbg.dassert_eq(client.meta.service_model.service_name, "s3")
Sure, Prof. @gpsaggese. However, I have a question. Do we have any exceptions when we use the custom asserting functions from hdbg? Like when checking through iterables, etc.? Because I picked this up from my previous PR (#700) where @samarth9008 has pointed it out and suggested that I use the internal functions.

2024-03-09 16:56 UTC, gpsaggese commented on helpers/test/test_haws.py
> +        hdbg.dassert_eq(client.meta.service_model.service_name, "s3")
You can just tag my name, no need for titles. In front of coding, we are all amateurs.

This was a misunderstanding. You can see the discussion
https://github.com/sorrentum/sorrentum/pull/711#discussion_r1518131410

2024-03-09 18:12 UTC, samarth9008 requested changes
TODO(Samarth): Don't merge before creating a PR on cmamp and testing it over there also

2024-03-09 23:20 UTC, tkpratardan commented
@samarth9008 @gpsaggese @sonaalKant 
Fixed the nits and resolved the conflicts. Please verify

2024-03-11 13:13 UTC, merged