Fixing linter issues for SorrTask693_improve_hpandas_compare_dfs
sorrentum/sorrentum pull request #726
Opened 2024-03-08 23:50 UTC by tkpratardan

@gpsaggese @sonaalKant @samarth9008 
This is a stacked PR to merge the changes occurring by running linter on the files in #717 and simplify the workflow for the main PR. Please review.

2024-03-09 03:05 UTC, sonaalKant requested changes
LGTM. Some nits .

2024-03-09 03:05 UTC, sonaalKant commented on helpers/test/test_hpandas.py
> +        Helper function to get test multi-index dataframe. Example of dataframe
Can you add ``` around the code block linter has messed it up.

2024-03-09 03:05 UTC, sonaalKant commented on helpers/test/test_hpandas.py
> -                            column1     column2
Same here.

2024-03-09 17:00 UTC, gpsaggese reviewed
After changes suggested by @sonaalKant ok to merge.

BTW @tkpratardan always make sure to review your own PR to spot small problems (even if it's just a linter run).

2024-03-09 18:13 UTC, samarth9008 requested changes
TODO(Samarth): Don't merge before creating a PR on cmamp and testing it over there also

2024-03-09 23:22 UTC, tkpratardan commented
> After changes suggested by @sonaalKant ok to merge.
> 
> BTW @tkpratardan always make sure to review your own PR to spot small problems (even if it's just a linter run).

Sure @gpsaggese, and @sonaalKant. I am sorry for missing it out. Will make sure to be vigilant.

2024-03-10 16:21 UTC, tkpratardan commented on helpers/test/test_hpandas.py
> +        Helper function to get test multi-index dataframe. Example of dataframe
@sonaalKant 
I am not sure  I understand how to implement this. Can you please elaborate? If I understand it right, does it fence the docstrings from being modified by linting operation?

2024-03-13 05:01 UTC, sonaalKant commented on helpers/test/test_hpandas.py
> +        Helper function to get test multi-index dataframe. Example of dataframe
Yes, exactly.

2024-03-14 02:17 UTC, sonaalKant approved these changes

2024-03-16 12:13 UTC, gpsaggese reviewed
Good work

2024-03-16 12:57 UTC, merged