Scaffolding tests for `hpandas.compare_dfs()`
sorrentum/sorrentum pull request #733
Opened 2024-03-11 15:10 UTC by tkpratardan

@gpsaggese @sonaalKant @samarth9008 
This is `stacked PR2` for #682, where unit tests have been added for scaffolding. I have made the changes to the code in unit testing as pointed out [here](https://github.com/sorrentum/sorrentum/pull/717#discussion_r1516865798) and [here](https://github.com/sorrentum/sorrentum/pull/717#discussion_r1516868901)

As I understand, the code would be expected to fail in several test cases with the present version of `hpandas.compare_dfs()` from helpers, as there have been changes to the logic of the code as pointed out [here](https://github.com/sorrentum/sorrentum/pull/717#discussion_r1515296198)  and [here](https://github.com/sorrentum/sorrentum/pull/717#discussion_r1515294959). Also, the assertion messages are expected to be changed when comparing invariants as they are generated by the `pd.testing.assert_frame_equal()` method. 

Please let me know if this is what's expected to be done. 

FYR: 
The workflow for #682 is organized as follows:
1. Main PR: #717 (changes to the main function)
 2. Stacked PR1: #726 (fixing linter changes in the files being affected, viz., `helpers/hpandas.py` and `helpers/test/test_hpandas.py` )
 3. Stacked PR2: Current (Scaffolding tests for `hpandas.compare_dfs()`)

2024-03-13 05:19 UTC, sonaalKant requested changes
Good Job!! LGTM. 

Added some nits.

2024-03-13 05:19 UTC, sonaalKant commented on helpers/test/test_hpandas.py
> +        compare_nans = True.
Remove `.` and add ``` as this is code block. Also you can write a small sentence

2024-03-13 05:19 UTC, sonaalKant commented on helpers/test/test_hpandas.py
> +            )
Can we do the same as above, assert_equal on assertion raised?

2024-03-14 04:08 UTC, sonaalKant requested changes

2024-03-14 04:08 UTC, sonaalKant commented on helpers/test/test_hpandas.py
> +        Check functionality for `remove_inf = True` in presence of `diff_mode =
-> `remove_inf = False` right?

2024-03-14 05:39 UTC, tkpratardan commented on helpers/test/test_hpandas.py
> +        Check functionality for `remove_inf = True` in presence of `diff_mode =
Yes, I am sorry for the typo.

2024-03-16 12:42 UTC, sonaalKant approved these changes

2024-03-16 12:55 UTC, gpsaggese commented
Some tests are failing due to the new param.
```
helpers/test/test_hpandas.py::Test_compare_dfs::test10 (0.00 s) FAILED            [ 43%]
helpers/test/test_hpandas.py::Test_compare_dfs::test11 (0.00 s) FAILED            [ 43%]
helpers/test/test_hpandas.py::Test_compare_dfs::test12 (0.00 s) FAILED            [ 43%]
helpers/test/test_hpandas.py::Test_compare_dfs::test13 (0.00 s) FAILED            [ 43%]
helpers/test/test_hpandas.py::Test_compare_dfs::test2 (0.01 s) PASSED             [ 43%]
helpers/test/test_hpandas.py::Test_compare_dfs::test3 (0.01 s) PASSED             [ 43%]
helpers/test/test_hpandas.py::Test_compare_dfs::test4 (0.01 s) PASSED             [ 43%]
helpers/test/test_hpandas.py::Test_compare_dfs::test5 (0.01 s) PASSED             [ 43%]
helpers/test/test_hpandas.py::Test_compare_dfs::test6 (0.01 s) PASSED             [ 43%]
helpers/test/test_hpandas.py::Test_compare_dfs::test7 (0.01 s) PASSED             [ 43%]
helpers/test/test_hpandas.py::Test_compare_dfs::test8 (0.00 s) FAILED             [ 43%]
helpers/test/test_hpandas.py::Test_compare_dfs::test9 (0.00 s) PASSED             [ 43%]
```

Pls do a quick fix.

After this, we can merge. Good working unit testing.

2024-03-17 16:00 UTC, tkpratardan commented on helpers/test/test_hpandas.py
> +        """
@gpsaggese @sonaalKant 
I made changes to the assertion message to be consistent with the changes made [here](https://github.com/sorrentum/sorrentum/pull/717#discussion_r1527426647). Please let me know if this is according to the expectations

2024-03-17 16:00 UTC, tkpratardan commented
> Pls do a quick fix.
> 
> After this, we can merge. Good working unit testing.
@gpsaggese 
I am not sure I understand how to do this. Could you please elaborate?

2024-03-17 22:45 UTC, gpsaggese reviewed
Good stuff. Let's get all the tests to pass and then we can merge

2024-03-17 22:45 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +        Test NaN comparison with NaNs present at different location in two dataframes with `compare_nans = True`.
This is a good description. You want to highlight what is that you are testing not all the details (that's in the code).

You need to reflow the text to 80 cols (probably the linter does it for you)

2024-03-17 22:45 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +        """
Yes this looks good

2024-03-18 23:14 UTC, tkpratardan commented
> Good stuff. Let's get all the tests to pass and then we can merge

@gpsaggese 
I am a little confused by your suggestion because I am not sure how to get it done. Certain tests are designed in accordance with the modified code and are expected to fail in the current version on master branch. 
 
However, I have tested it on my local machine, and all the tests did pass, if that's what you mean.

2024-03-19 17:47 UTC, gpsaggese commented
> > Good stuff. Let's get all the tests to pass and then we can merge
> 
> @gpsaggese I am a little confused by your suggestion because I am not sure how to get it done. Certain tests are designed in accordance with the modified code and are expected to fail in the current version on master branch.
> 
> However, I have tested it on my local machine, and all the tests did pass, if that's what you mean.

The regressions on GH are reporting a failure https://github.com/sorrentum/sorrentum/actions/runs/8316607993/job/22756287509?pr=733

(We automatically run all the tests after every commit, and we trust only that and not what happens on people's laptops).

FAILED helpers/test/test_hpandas.py::Test_compare_dfs::test10 - TypeError: compare_dfs() got an unexpected keyword argument 'only_warning'
FAILED helpers/test/test_hpandas.py::Test_compare_dfs::test11 - TypeError: compare_dfs() got an unexpected keyword argument 'only_warning'
FAILED helpers/test/test_hpandas.py::Test_compare_dfs::test12 - TypeError: compare_dfs() got an unexpected keyword argument 'only_warning'
FAILED helpers/test/test_hpandas.py::Test_compare_dfs::test13 - TypeError: compare_dfs() got an unexpected keyword argument 'only_warning'
FAILED helpers/test/test_hpandas.py::Test_compare_dfs::test8 - TypeError: compare_dfs() got an unexpected keyword argument 'only_warning'

I would merge master in this branch and run only these tests on your laptop

```
docker> pytest helpers/test/test_hpandas.py::Test_compare_dfs
```

Makes sense? If not you can ping @sonaalKant asking for help

2024-03-22 17:21 UTC, tkpratardan commented
@gpsaggese @sonaalKant 
Fixed the issue. please check and verify.

2024-03-22 18:44 UTC, sonaalKant approved these changes
LGTM.

2024-03-23 14:53 UTC, gpsaggese reviewed
LG

2024-03-23 14:54 UTC, gpsaggese reviewed
Let's merge and then follow up.

2024-03-23 14:54 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +        with self.assertRaises(AssertionError):
We should check the assertion.

We don't want to just look for an assertion without knowing which one

2024-03-23 14:54 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +        with self.assertRaises(AssertionError):
Same thing

2024-03-23 14:54 UTC, merged

2024-03-23 15:01 UTC, tkpratardan commented on helpers/test/test_hpandas.py
> +        with self.assertRaises(AssertionError):
Yes, @sonaalKant and I were planning to redo the changes after the checks have passed.