Added new parameter to transform_bid_ask_long_data_to_wide and added unit tes
sorrentum/sorrentum pull request #744
Opened 2024-03-22 18:25 UTC by Vedanshu7

…it test

2024-03-23 15:15 UTC, gpsaggese commented on core/finance/bid_ask.py
> +    value_col_prefix: List[str] = ["log", "half"],
You need to pass `None` and then expand it in the code

This is known to be dangerous
https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html

2024-03-23 15:15 UTC, gpsaggese commented on core/finance/bid_ask.py
> +    :param value_col_prefix: prefixes for value-related columns; default is ["log", "half"].
no need to say what's the default. That belongs to the interface

2024-03-23 15:15 UTC, gpsaggese commented on core/finance/test/test_bid_ask.py
> +        deafult agrmunet value of `value_col_prefix`.
default argument

After sending a PR, pls review it yourself top-to-bottom for imperfections

2024-03-23 15:19 UTC, gpsaggese commented on core/finance/bid_ask.py
> +        if col.startswith((bid_prefix, ask_prefix) + tuple(value_col_prefix))
This is valid but difficult to read

Let's use something more readable like
```
prefixes = [bid_prefix, ask_prefix] + list(value_col_prefix)
...
if any(col.startswith(prefix) for prefix in prefixes)

```

2024-03-23 15:19 UTC, gpsaggese commented on core/finance/bid_ask.py
> +    value_col_prefix: List[str] = ["log", "half"],
should be plural `...prefixes`.

2024-03-23 15:53 UTC, Vedanshu7 commented on core/finance/bid_ask.py
> +    :param value_col_prefix: prefixes for value-related columns; default is ["log", "half"].
Resolved.

2024-03-23 15:53 UTC, Vedanshu7 commented on core/finance/bid_ask.py
> +    value_col_prefix: List[str] = ["log", "half"],
Resolved.

2024-03-23 15:54 UTC, Vedanshu7 commented on core/finance/test/test_bid_ask.py
> +        deafult agrmunet value of `value_col_prefix`.
Resolved.

2024-03-23 15:54 UTC, Vedanshu7 commented on core/finance/bid_ask.py
> +        if col.startswith((bid_prefix, ask_prefix) + tuple(value_col_prefix))
Resolved.

2024-03-23 15:54 UTC, Vedanshu7 commented on core/finance/bid_ask.py
> +    value_col_prefix: List[str] = ["log", "half"],
Resolved.

2024-03-26 14:15 UTC, jsmerix commented on core/finance/bid_ask.py
>          # TODO(Juraj): ad-hoc hack, address properly in #CmTask7387.
We can remove this comment now - this is the issue in which we are solving the problem

2024-03-26 14:20 UTC, jsmerix requested changes

2024-03-26 14:20 UTC, jsmerix commented on core/finance/test/test_bid_ask.py
> +            "level": [1, 1, 1],
Why did you change this?

2024-03-26 15:14 UTC, Vedanshu7 commented on core/finance/bid_ask.py
>          # TODO(Juraj): ad-hoc hack, address properly in #CmTask7387.
Resolved.

2024-03-26 18:45 UTC, Vedanshu7 commented on core/finance/test/test_bid_ask.py
> +            "level": [1, 1, 1],
while running the one-symbol, one-level test case. The transform_bid_ask_long_data_to_wide function is throwing an error for duplicate entries, and it couldn't be to reshape; the pivot function is failing.

This is my test data:

```
                                               level currency_pair  bid_price  bid_size  \
timestamp                                                             
2022-09-08 21:01:00+00:00      1      XRP_USDT       2.31       1.1   
2022-09-08 21:01:00+00:00      1      XRP_USDT       3.22       2.2   
2022-09-08 21:01:00+00:00      1      XRP_USDT       2.33       3.3   

                                                 ask_price  ask_size       knowledge_timestamp  \
timestamp                                                                  
2022-09-08 21:01:00+00:00       2.34       5.4 2022-09-08 21:01:15+00:00   
2022-09-08 21:01:00+00:00       3.24       5.5 2022-09-08 21:01:15+00:00   
2022-09-08 21:01:00+00:00       2.35       6.6 2022-09-08 21:01:15+00:00   

                                              half_spread  log_size  
timestamp                                         
2022-09-08 21:01:00+00:00        0.005      0.01  
2022-09-08 21:01:00+00:00        0.020      0.03  
2022-09-08 21:01:00+00:00        0.020      0.01  
```

this is the error trace:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 7
      5        #
      6 timestamp_col = "timestamp"
----> 7 wide_levels_df = cfibiask.transform_bid_ask_long_data_to_wide(
      8            long_levels_df, timestamp_col
      9 )
     11 print(wide_levels_df)

File /app/core/finance/bid_ask.py:210, in transform_bid_ask_long_data_to_wide(df, timestamp_col, bid_prefix, ask_prefix, final_col_format, value_col_prefixes)
    204 non_bid_ask_cols = [
    205     col for col in df.columns if col not in bid_ask_cols + ["level", "id"]
    206 ]
    207 # TODO(Max): Create an assertion that all values for levels are identical,
    208 # so we are merging the rows without duplicates (i.e., "knowledge_timestamp" and "end_download_timestamp").
    209 # Merge `level` into bid-ask values (e.g., bid_price_1, bid_price_2, etc.).
--> 210 pivoted_data = df.pivot(
    211     index=non_bid_ask_cols,
    212     columns=["level"],
    213     values=bid_ask_cols,
    214 )
    215 # Rename the columns to a desired {value}_{level} format.
    216 pivoted_data.columns = pivoted_data.columns.map(final_col_format.format)

File /venv/lib/python3.9/site-packages/pandas/core/frame.py:9028, in DataFrame.pivot(self, columns, index, values)
   9021 @Substitution("")
   9022 @Appender(_shared_docs["pivot"])
   9023 def pivot(
   9024     self, *, columns, index=lib.no_default, values=lib.no_default
   9025 ) -> DataFrame:
   9026     from pandas.core.reshape.pivot import pivot
-> 9028     return pivot(self, index=index, columns=columns, values=values)

File /venv/lib/python3.9/site-packages/pandas/core/reshape/pivot.py:553, in pivot(data, columns, index, values)
    549         indexed = data._constructor_sliced(data[values]._values, index=multiindex)
    550 # error: Argument 1 to "unstack" of "DataFrame" has incompatible type "Union
    551 # [List[Any], ExtensionArray, ndarray[Any, Any], Index, Series]"; expected
    552 # "Hashable"
--> 553 result = indexed.unstack(columns_listlike)  # type: ignore[arg-type]
    554 result.index.names = [
    555     name if name is not lib.no_default else None for name in result.index.names
    556 ]
    558 return result

File /venv/lib/python3.9/site-packages/pandas/core/frame.py:9625, in DataFrame.unstack(self, level, fill_value, sort)
   9561 """
   9562 Pivot a level of the (necessarily hierarchical) index labels.
   9563 
   (...)
   9621 dtype: float64
   9622 """
   9623 from pandas.core.reshape.reshape import unstack
-> 9625 result = unstack(self, level, fill_value, sort)
   9627 return result.__finalize__(self, method="unstack")

File /venv/lib/python3.9/site-packages/pandas/core/reshape/reshape.py:504, in unstack(obj, level, fill_value, sort)
    502 if isinstance(obj, DataFrame):
    503     if isinstance(obj.index, MultiIndex):
--> 504         return _unstack_frame(obj, level, fill_value=fill_value, sort=sort)
    505     else:
    506         return obj.T.stack(future_stack=True)

File /venv/lib/python3.9/site-packages/pandas/core/reshape/reshape.py:529, in _unstack_frame(obj, level, fill_value, sort)
    525 def _unstack_frame(
    526     obj: DataFrame, level, fill_value=None, sort: bool = True
    527 ) -> DataFrame:
    528     assert isinstance(obj.index, MultiIndex)  # checked by caller
--> 529     unstacker = _Unstacker(
    530         obj.index, level=level, constructor=obj._constructor, sort=sort
    531     )
    533     if not obj._can_fast_transpose:
    534         mgr = obj._mgr.unstack(unstacker, fill_value=fill_value)

File /venv/lib/python3.9/site-packages/pandas/core/reshape/reshape.py:154, in _Unstacker.__init__(self, index, level, constructor, sort)
    146 if num_cells > np.iinfo(np.int32).max:
    147     warnings.warn(
    148         f"The following operation may generate {num_cells} cells "
    149         f"in the resulting pandas object.",
    150         PerformanceWarning,
    151         stacklevel=find_stack_level(),
    152     )
--> 154 self._make_selectors()

File /venv/lib/python3.9/site-packages/pandas/core/reshape/reshape.py:210, in _Unstacker._make_selectors(self)
    207 mask.put(selector, True)
    209 if mask.sum() < len(self.index):
--> 210     raise ValueError("Index contains duplicate entries, cannot reshape")
    212 self.group_index = comp_index
    213 self.mask = mask

ValueError: Index contains duplicate entries, cannot reshape
```

2024-03-27 02:45 UTC, Vedanshu7 commented on core/finance/test/test_bid_ask.py
> +            "level": [1, 1, 1],
@jsmerix When encountering duplicate rows in the non-bid-ask columns during pivoting, the pivot function is throwing an error. Options for solutions include taking the mean, summing the data, using a specific custom aggregation function, or dropping duplicates. Can you please guide me on which option I should choose to move forward?

2024-03-27 02:51 UTC, Vedanshu7 commented on core/finance/test/test_bid_ask.py
> +            "level": [1, 1, 1],
Or if all the columns in non-bid-ask have duplicate values, then it should bypass the pivoting?

2024-03-27 09:07 UTC, jsmerix commented on core/finance/test/test_bid_ask.py
> +            "level": [1, 1, 1],
No need to update the function in any way, the input data for the test should not include duplicate timestamp for a given symbol and level

2024-03-27 15:13 UTC, Vedanshu7 commented on core/finance/test/test_bid_ask.py
> +            "level": [1, 1, 1],
Resolved.

2024-03-27 15:51 UTC, jsmerix requested changes
All of the test methods have the same pattern:

- get data
- call function
- compare with expected

Could we try to factor out common behavior to a `_test` method and simply pass the variables?

2024-03-27 15:55 UTC, Vedanshu7 commented
> All of the test methods have the same pattern:
> 
> * get data
> * call function
> * compare with expected
> 
> Could we try to factor out common behavior to a `_test` method and simply pass the variables?

Sure

2024-03-28 13:39 UTC, jsmerix approved these changes

2024-04-05 18:17 UTC, Vedanshu7 commented
@gpsaggese Can you please review this pull request at your earliest convenience?

2024-04-07 17:44 UTC, gpsaggese reviewed
LGTM

2024-04-07 17:45 UTC, merged