Sorr task752 add unit test db data #752
sorrentum/sorrentum pull request #753
Opened 2024-03-29 03:44 UTC by Jd8111997

@jsmerix  @sonaalKant I added a function class to test mock interaction with `load_db_data` function. 
Could you guys please check the logic for the function and let me know whether I am going in the correct direction.

2024-03-29 09:59 UTC, jsmerix commented on im_v2/common/db/test/test_db_utils.py
> +        pd.testing.assert_frame_equal(result, mock_df_result)
This part is not really necessary in my POV, you're just checking if your mock returns what you mocked.

2024-03-29 10:00 UTC, jsmerix requested changes
Good direction, let's also pay attention to design the test class reusably, factor out common code as the number of test cases grow

2024-04-01 09:51 UTC, jsmerix requested changes
Good progress.

2024-04-01 09:51 UTC, jsmerix commented on im_v2/common/db/test/test_db_utils.py
> +import unittest.mock as umock, patch
I guess this is just a draft update, but this import is incorrect - you can also see the GH action failing

2024-04-01 09:51 UTC, jsmerix commented on im_v2/common/db/test/test_db_utils.py
> +        self.end_ts = pd.Timestamp("2024-01-31")
Couple of suggestions here:
- If this is set once and not changing we don't need this to be in a fixture
- If this code was supposed to run before each test, the method name should be different + the comment above updated

2024-04-01 09:51 UTC, jsmerix commented on im_v2/common/db/test/test_db_utils.py
> +    @patch('im_v2.common.db.db_utils.hsql.execute_query_to_df')
I think this is the type of patch that would make sense to do in a fixture in order not to repeat the line in every test case.

2024-04-01 09:51 UTC, jsmerix commented on im_v2/common/db/test/test_db_utils.py
> +        Test case : Basic query construction with all the parameters provided.
Conventions:
- docstring is written in imperative
- Following an empty line you can provide additional information

2024-04-01 19:45 UTC, Jd8111997 commented on im_v2/common/db/test/test_db_utils.py
> +import unittest.mock as umock, patch
You're absolutely correct. My apologies for the oversight.

2024-04-01 19:52 UTC, Jd8111997 commented on im_v2/common/db/test/test_db_utils.py
> +        self.end_ts = pd.Timestamp("2024-01-31")
@jsmerix I don't understand your first feedback. Isn't fixture is used to set up preconditions or states / attributes needed for the tests to run, such as creating test data, initializing objects, or configuring the environment ?
Additionally, in some test cases, these attributes might get modified, and thus, I re-initialize them after every test case to maintain consistency and independence between tests.

2024-04-03 13:01 UTC, jsmerix commented on im_v2/common/db/test/test_db_utils.py
> +        self.end_ts = pd.Timestamp("2024-01-31")
It's a cosmetic thing, based on the usage I observed these are more like constants rather then something that gets modified - after all why would you modify a class attribute `src_table` in a single test case rather than just creating a local variable? But not something to lose sleep over, okay to leave as is.

2024-04-03 13:24 UTC, jsmerix requested changes
One final remark, otherwise nicely done.

2024-04-03 13:24 UTC, jsmerix commented on im_v2/common/db/test/test_db_utils.py
> +        Test case: Limit parameter is larger than total number of rows returned by database query
Let's follow the conveiton of imperative in first sentence of docstring (same for others)

2024-04-05 01:22 UTC, gpsaggese commented on im_v2/common/db/test/test_db_utils.py
> +        # Prepare mock data
. At the end of comments

2024-04-05 01:22 UTC, gpsaggese commented on im_v2/common/db/test/test_db_utils.py
> +            with self.assertRaises(ValueError):
We need to check the value of the assertion, otherwise it's too loose.

2024-04-05 01:22 UTC, gpsaggese commented on im_v2/common/db/test/test_db_utils.py
> +
Linter

2024-04-05 01:22 UTC, gpsaggese commented
@DanilYachmenev can you pls nitpick the style until it's perfect

2024-04-05 08:23 UTC, jsmerix requested changes

2024-04-05 08:23 UTC, jsmerix commented on im_v2/common/db/test/test_db_utils.py
> +        with umock.patch('im_v2.common.db.db_utils.hsql.execute_query_to_df') as mock_execute_query_to_df:
I don't really understand what's going on here, why have we switched to repeating code instead of mocking once?

2024-04-05 16:39 UTC, Jd8111997 commented on im_v2/common/db/test/test_db_utils.py
> +            with self.assertRaises(ValueError):
@gpsaggese, I completely agree with you on this. It is too ambiguous. However, since we are mocking the behaviors for both the `db_connection` and `execute_query_to_df` methods, how do we determine the actual `ValueError` message? As I understand it, we need to have access to the actual database to replicate the exact error message that would occur in a real execution.

2024-04-07 17:23 UTC, DanilYachmenev commented on im_v2/common/db/test/test_db_utils.py
> +import helpers.hdatetime as hdateti
Always run linter on all the changed files before sending PR for review
https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md#run-linter

2024-04-07 17:23 UTC, DanilYachmenev commented on im_v2/common/db/test/test_db_utils.py
> +        # Invalid currency pairs
Finish all the comments with a dot`.`

2024-04-07 17:23 UTC, DanilYachmenev commented on im_v2/common/db/test/test_db_utils.py
> +    def test_load_db_data(self):
to DRY the code, just name test methods like `test1` , `test2`, etc
no need to repeat the same name all the time

2024-04-07 17:23 UTC, DanilYachmenev commented on im_v2/common/db/test/test_db_utils.py
> +        # Mocking execute_query_to_df method
Avoid using param names in comments whenever possible
because the name of the params are changing and this will require to keep an eye in the comment as well
unnecessary, potentially misleading

you can just say `# Mock the query.`

2024-04-07 17:23 UTC, DanilYachmenev commented on im_v2/common/db/test/test_db_utils.py
> +            # Assert that an expected_query is called.
check in all the comments
together with putting dot at the end

2024-04-07 17:23 UTC, DanilYachmenev commented on im_v2/common/db/test/test_db_utils.py
> +            with self.assertRaises(ValueError):
@Jd8111997 see `test_load_db_table3()` in 
`im_v2/common/data/client/test/test_im_raw_data_client.py`

you need to assert the error message

2024-04-07 17:27 UTC, DanilYachmenev commented
@Jd8111997 also remember to update PR labels
pls read https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md

2024-04-08 02:52 UTC, Jd8111997 commented on im_v2/common/db/test/test_db_utils.py
> +            with self.assertRaises(ValueError):
Thanks @DanilYachmenev, I will take a look.

2024-04-08 17:49 UTC, jsmerix commented on im_v2/common/db/test/test_db_utils.py
> +        with umock.patch('im_v2.common.db.db_utils.hsql.execute_query_to_df') as mock_execute_query_to_df:
> also tried to initialize a mock_execute_query_to_df object separately in a both setUp and tearDown method but that too didn't work. 

I cannot give you advice on this since I didn't see your code but that approach should work, it's a standard way of using mocks, examples:

https://github.com/sorrentum/sorrentum/blob/a6ea36f6cc1cbcace7640e3c7e97d0795a3f1751/im_v2/ccxt/data/extract/test/test_ccxt_extractor.py#L21

https://github.com/sorrentum/sorrentum/blob/a6ea36f6cc1cbcace7640e3c7e97d0795a3f1751/im_v2/common/data/extract/test/test_extract_utils.py#L26

2024-04-08 21:03 UTC, Jd8111997 commented on im_v2/common/db/test/test_db_utils.py
> +        with umock.patch('im_v2.common.db.db_utils.hsql.execute_query_to_df') as mock_execute_query_to_df:
@jsmerix Thank you for the suggestion. It worked.

2024-04-08 22:01 UTC, Jd8111997 commented on im_v2/common/db/test/test_db_utils.py
> +            with self.assertRaises(ValueError):
@DanilYachmenev I saw the code in `im_v2/common/data/client/test/test_im_raw_data_client.py`. I still have the same concern regarding how to get the actual expected error/output precisely in a case when we are trying to mock the method and not running on actual databases.

2024-04-09 09:27 UTC, jsmerix commented on im_v2/common/db/test/test_db_utils.py
> +        self.mock_execute_query_df.stop()
Any particular reason why you used both? Wouldn't it be simpler to only use `set_up_test`

2024-04-09 22:50 UTC, gpsaggese commented on im_v2/common/db/test/test_db_utils.py
> +            )
I've added a note to the unit test documentation

### Always explain self.assertRaises

- Testing for an assertion needs always to be done with the following idiom
  to explain exactly what we are catching and why
  ```python
  with self.assertRaises(AssertionError) as cm:
      hlitagit.git_patch_create(
          ctx, mode, modified, branch, last_commit, files
      )
  act = str(cm.exception)
  exp = r"""
  * Failed assertion *
  '0'
  ==
  '1'
  Specify only one among --modified, --branch, --last-commit
  """
  self.assert_equal(act, exp, fuzzy_match=True)
  ``

2024-04-10 03:11 UTC, Jd8111997 commented on im_v2/common/db/test/test_db_utils.py
> +        self.mock_execute_query_df.stop()
Fixed it!

2024-04-10 03:17 UTC, Jd8111997 commented on im_v2/common/db/test/test_db_utils.py
> +            )
@gpsaggese @jsmerix I have a question. In the example you provided, you've used the `exp` variable to handle the exception more precisely. My question is, how can we retrieve the exact exp message for the method we're attempting to mock? Since we're not directly executing queries on the actual database, how can we determine what the exact error message would be?"

In our example, we are mocking both `db_connection` object and `execute_query_to_df` method.

2024-04-10 19:24 UTC, gpsaggese commented on im_v2/common/db/test/test_db_utils.py
> +            )
IIUC, you should put whatever assertion is throwing.

2024-04-11 04:16 UTC, Jd8111997 commented on im_v2/common/db/test/test_db_utils.py
> +            )
Thanks @gpsaggese.

2024-04-11 15:08 UTC, gpsaggese reviewed
Minor tweaks and then let's merge

2024-04-11 15:08 UTC, gpsaggese commented on im_v2/common/db/test/test_db_utils.py
> +
No empty space.

You want to say
```
# Prepare data.
...
# Run test.
...
# Check results.
```

2024-04-11 15:08 UTC, gpsaggese commented on im_v2/common/db/test/test_db_utils.py
> +        # Assert that function is returning None.
The code is clear enough. No need for comment.

2024-04-11 15:08 UTC, gpsaggese commented on im_v2/common/db/test/test_db_utils.py
> +        expected_query = f"SELECT * FROM {self.src_table} WHERE timestamp >= {self.start_ts} AND timestamp <= {self.end_ts}"
```
# Check results.
```
goes here

2024-04-12 21:56 UTC, merged